### ISSUE TITLE
Feature: As a developer, I want aiSSEMBLE to disable linting when I initially upgrade a project to 1.8.x or higher so that my build does not error due to linting issues

### ISSUE THREAD

**Issue by liangyun123** [boozallen/aissemble#110]
## Description
This ticket addresses upgrading existing projects to 1.8.x or higher and new projects created in 1.8.x to use Pylint so that builds for existing projects do not immediately fail on upgrade. 

## DOD
- [x] Include a baton migration that will by default disable pylint on Habushu for projects before 1.8.0 and upgrading to 1.8.x.
- [x] Modify the root pom.xml archetype to include the habushu pulgin within the plugin management with both sourceFailOnLintErrors and testFailOnLintErrors enabled. 
- [x] Update documentation:
  * in New Feature section: discuss how to enable Pylint and **some** common fixes required:
    * Behave module in test
    * (if not a baton migration) inference module needs to whitelist Pydantic package. 
  * in New Feature section: discuss the changes to post actions for conversion to an onnx model. 
  * Newly added Baton migrations. 

BDD Scenario:
```gherkin
Feature: Python linting is disabled for projects upgrading to 1.8.0

  Scenario: A standard 1.7.0 project
    Given A root pom without Habushu in the plugin management 
    When The 1.8.0 python linting migration executes
    Then The root pom is updated with Habushu in plugin management
    And Habushu is configured with sourceFailOnLintErrors and testFailOnLintErrors disabled

  Scenario: Missing configuration section
    Given A root pom with Habushu in the plugin management and does not contain the configuration tag
    When The 1.8.0 python linting migration executes
    Then The root pom is updated with the configuration tag
    And Habushu is configured with sourceFailOnLintErrors and testFailOnLintErrors disabled

  Scenario: Missing both sourceFailOnLintErrors and testFailOnLintErrors
    Given A root pom with Habushu in the plugin management and does not contain both sourceFailOnLintErrors and testFailOnLintErrors
    When The 1.8.0 python linting migration executes
    Then Habushu is configured with sourceFailOnLintErrors and testFailOnLintErrors disabled

  Scenario: sourceFailOnLintErrors and/or testFailOnLintErrors is already set
    Given A root pom with Habushu in the plugin management and does not contain either sourceFailOnLintErrors or testFailOnLintErrors
    When The 1.7.0 python linting migration executes
    Then The 1.7.0 python linting migration is skipped

```

## Test Strategy/Script
Test 1: Testing new projects where Pylint is enabled by default
1. Create a new downstream project by running:
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.8.0-SNAPSHOT -DgroupId=com.test -DartifactId=test-project1101 -DprojectGitUrl=url -DprojectName=test-project1101 && cd test-project1101
```
2. Add the attached `ExampleMachineLearning.json` file to `test-project1101-pipeline-models/src/main/resources/pipeline`.
3. From the root pom.xml, comment the code:
```
    <module>test-project1101-docker</module>
    <module>test-project1101-deploy</module>
```
4. Run `mvn clean install -Dmaven.build.cache.skipCache=true` until no further manual actions.
5. The resulting build should succeed without error. Verify in the terminal output that pylint is ran and without the `--exit-zero` tags. 

Test 2: Testing upgrade where Pylint is not configured. 
1. Create a new downstream project by running:
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.7.0 -DgroupId=com.test -DartifactId=test-project1102 -DprojectGitUrl=url -DprojectName=test-project1102 && cd test-project1102
```
2. Add the attached `ExampleMachineLearning.json` file to `test-project1102-pipeline-models/src/main/resources/pipeline`.
3. From the root pom.xml, comment the code:
```
    <module>test-project1102-docker</module>
    <module>test-project1102-deploy</module>
```
4. Run `mvn clean install` until no further manual actions. 
6. Change the aissemble version to 1.8.0-SNAPSHOT in the root pom.xml.
7. The resulting build should succeed without error. Verify in the terminal output that pylint is ran and with the `--exit-zero` tags. Verify in the root pom.xml contains the habushu plugin in the pluginManagement with sourceFailOnLint and testFailOnLint configured to false.  

Test 3: Testing upgrade where Habushu is partly configured.
1. Create a new downstream project by running:
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.7.0 -DgroupId=com.test -DartifactId=test-project1103 -DprojectGitUrl=url -DprojectName=test-project1103 && cd test-project1103
```
2. Add the attached `ExampleMachineLearning.json` file to `test-project1102-pipeline-models/src/main/resources/pipeline`.
3. From the root pom.xml, comment the code:
```
    <module>test-project1103-docker</module>
    <module>test-project1103-deploy</module>
```
4. Run `mvn clean install` until no further manual actions. 
5. Change the aissemble version to 1.8.0-SNAPSHOT in the root pom.xml. Attach the following plugin to pluginManagement tags:
```
				<plugin>
					<groupId>org.technologybrewery.habushu</groupId>
					<artifactId>habushu-maven-plugin</artifactId>
          <configuration>
            <exportRequirementsFile>true</exportRequirementsFile>
          </configuration>
				</plugin>
```
6. The resulting build should succeed without error. Verify in the terminal output that pylint is ran and with the `--exit-zero` tags. Verify in the root pom.xml contains the habushu plugin in the pluginManagement with sourceFailOnLint and testFailOnLint configured to false.  
## References/Additional Context
[ExampleMachineLearning.json](https://github.com/user-attachments/files/15792498/ExampleMachineLearning.json)

**Comment by liangyun123** [comment]
DoD competed with @ewilkins-csi.

**Comment by csun-cpointe** [comment]
OTS completed!!

**Comment by csun-cpointe** [comment]
test passed!!
