### ISSUE TITLE
Allow Helm charts to be deployed into custom namespaces

### ISSUE THREAD

**Issue by ahartwellCpointe** [boozallen/aissemble#12]
Currently, Helm charts are just deployed to the default namespace, which means you are limited to only having one project deployed at a time. To deconflict this, we want the charts of downstream projects to be deployed into a new namespace named for the project

**Comment by ahartwellCpointe** [comment]
*Test Steps*
1. Check out the latest version of the aissemble code on the feature-custom-namespaces branch
2. Build the following modules
  - foundation-archetype
```
mvn clean install -pl :foundation-archetype
```
  - foundation-mda
```
mvn clean install -pl :foundation-mda
```
  - Change directory into the extensions-helm module and build all extensions-helm modules
```java
cd extensions/extensions-helm/
mvn clean install
```
3. Switch to the directory in which you would like to generate a project.
4. Generate a new project with the command    
```java
mvn archetype:generate -U -DarchetypeGroupId=com.test -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.7.0-SNAPSHOT -DgroupId=com.test -DartifactId=test-project -DprojectGitUrl=url -DprojectName=test-project
```
5. Add the attached pipelines, record, and dictionary models to the corresponding directories under test-project-pipeline-models/src/main/resources
6. Switch to the project's root directory in your terminal
7. Run mvn clean install once. This build will fail due to the nature of this local test.
8. In your local aissemble codebase, update the version field of each of the Chart.yaml files in the extensions-helm modules to match the current aissemble version, like this:
```java
version: 1.7.0-SNAPSHOT
```
9. In your generated project, you should now have a kafka-cluster folder under test-project-deploy/src/main/resources/apps/kafka-cluster. Go into this directory and run the following command, after replacing <PathToYourAissembleProject> with the filepath of your local copy of aissemble
```java
sed -i  '' -e ':a' -e 'N' -e '$!ba' -e 's#  - name: \(.*\)\n    version: 1.7.0-SNAPSHOT\n    repository: .*#  - name: \1\n    version: 1.7.0-SNAPSHOT\n    repository: file://<PathToYourAissembleProject>/extensions/extensions-helm/\1#g' Chart.yaml
```
10. Navigate to the generated project's root directory
11. Run mvn clean install and resolve any manual actions
12. Modify the three executions of the exec-maven-plugin in your test-project-pipelines/spark-pipeline/pom.xml and /test-project-pipelines/pyspark-pipeline/pom.xml by making the following replacement with the same filepath for <PathToYourAissembleProject> as before:
```
 <arguments>
    <argument>template</argument>
    - <argument>aissemble-spark-application-chart</argument>
    + <argument><PathToYourAissembleProject>/extensions/extensions-helm/aissemble-spark-application-chart</argument>
    <argument>--repo</argument>
```
13. Add the following executions to your test-project-deploy/pom.xml
```java
<execution>
  <id>elasticsearch-deploy</id>
  <phase>generate-sources</phase>
  <goals>
     <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>elasticsearch-deploy</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>elasticsearch-kubernetes</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>elasticsearch-deploy-v2</id>
  <phase>generate-sources</phase>
  <goals>
      <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>elasticsearch-deploy-v2</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                 to customize the deployment artifacts. -->
    <propertyVariables>
             <appName>elasticsearch-kubernetes-v2</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>inference-deploy</id>
  <phase>generate-sources</phase>
  <goals>
      <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>inference-deploy</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>inference-kubernetes</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>inference-deploy-v2</id>
  <phase>generate-sources</phase>
  <goals>
      <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>inference-deploy-v2</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>aissemble-inference-kubernetes</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>metadata-deploy-v2</id>
  <phase>generate-sources</phase>
  <goals>
      <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>metadata-deploy-v2</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>metadata-kubernetes-v2</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>aissemble-custom-lineage-consumer-deploy-v2</id>
  <phase>generate-sources</phase>
  <goals>
            <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>aissemble-custom-lineage-consumer-deploy-v2</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>lineage-custom-consumer-kubernetes</appName>
    </propertyVariables>
  </configuration>
</execution>
<execution>
  <id>lineage-http-consumer-deploy-v2</id>
  <phase>generate-sources</phase>
  <goals>
            <goal>generate-sources</goal>
  </goals>
  <configuration>
    <basePackage>com.test</basePackage>
    <profile>lineage-http-consumer-deploy-v2</profile>
    <!-- The property variables below are passed to the Generation Context and utilized
                  to customize the deployment artifacts. -->
    <propertyVariables>
        <appName>lineage-http-consumer-kubernetes</appName>
    </propertyVariables>
  </configuration>
</execution>
```
14. Run mvn clean install again. This build will also fail at the deploy module
15. Repeat step 9 for all of the new folders under test-project-deploy/src/main/resources/apps
16. Run "mvn clean generate-sources" and resolve manual actions until there are none left
17. The previous step's manual actions will have added a pipeline-invocation-service deployment to your project that will need to be updated. Replace the dependency block at the bottom of your test-project-deploy/src/main/resources/apps/pipeline-invocation-service/Chart.yaml with the following, using the same filepath for <PathToYourAissembleProject> as before
```
dependencies:
  - name: aissemble-pipeline-invocation-chart
    version: 1.7.0-SNAPSHOT
    repository: file://<PathToYourAissembleProject>/extensions/extensions-helm/aissemble-pipeline-invocation-chart
  - name: aissemble-pipeline-invocation-lib-chart
    version: 1.7.0-SNAPSHOT
    repository: file://<PathToYourAissembleProject>/extensions/extensions-helm/aissemble-pipeline-invocation-lib-chart
```
18. Run "mvn clean install"
19. Make the following two changes to your Tiltfile
  - For each of the "helm template" commands for your data delivery pipelines, replace "aissemble-spark-application-chart" with "<PathToYourAissembleProject>/extensions/extensions-helm/aissemble-spark-application-chart"
  - Remove "--repo oci://ghcr.io/boozallen" from the command
20. Remove the line "k8s_resource('elasticsearch')" from the Tiltfile
21. Run "tilt up"
  - **_NOTE_** - you will see multiple errors upon tilting up. These are caused by this test project deploying the v1 and v2 versions of multiple charts simultaneously, which is not intended behavior. This causes issues with the content that is added to your Tilfile. The error messages for these duplicate resources explain how to fix them, so you will simply need to address the duplicates that cause problems in your deployment.
22. Verify that all of the kubernetes resources deployed to a namespace named test-project with the exception of the kafka-cluster pod

**Comment by nartieri** [comment]
Tested and verified by successfully tilting up locally and ensuring the resources were deployed into the project specific namespace as opposed to the default namespace.
