### ISSUE TITLE
Feature: Add support for JDK 17 - Core library

### ISSUE THREAD

**Issue by ekoniec1** [boozallen/aissemble#133]
## Description
Currently, JDK 11 is required in order to use aiSSEMBLE.  OpenJDK support for 11 is [ending soon](https://access.redhat.com/articles/1299013#OpenJDK_Life_Cycle) and 17 is well supported across the open source community. For example, JDK 17 is compatible with [Spark 3.3+](https://issues.apache.org/jira/browse/SPARK-33772) and even required for [Quarkus 3.7+](https://quarkus.io/blog/java-17/).  Upgrading to JDK 17 will allow developers to take advantage of the latest JDK language features, performance improvements, and security fixes.

For this ticket, we will focus to make sure the build succedding until the `foundation-messaging` module

## DOD
- [ ] Allow for JDK 17 to be utilized for building and running aiSSEMBLE pipelines
  - [x] update aissemble-parent to support java 17
  - [ ] get the build succeeding up to the module `foundation-messaging` and all modules should have build success including unit tests and integration-test
     - [ ] modules (make sure all dependency modules support java 17)
        - [x] root pom
        - [x] build-parent
        - [x] build-support
            - [x] aissemble-enforcer-extension
        - [x] bom
            - [x] bom-component
            - [x] bom-instantiation
        - [x] foundation
            - [x] foundation-mda-plugins
              - [x] artifacts-maven-plugins
              - [x] foundation-model-plugin
              - [x] mda-maven-plugin
            - [x] foundation-archetype
            - [x] foundation-common
            - [ ] foundation-mda
            - [ ] foundation-core-java
            - [ ] foundation-core-python
            - [ ] foundation-messaging
                - [ ] foundation-messaging-java
                - [ ] foundation-messaging-python     
 ~- [ ] build success~
 ~- [ ] test success~
 ~- [ ] integration test success~
 ~- [ ] make sure all dependency modules support java 17~
     - [ ] make sure we clean up unused dependency modules
     - [ ] All modification should be on the feature branch `feature-java17`

----------------------------- Follow on work ------------------------------
  - [ ] data-lineage
  - [ ] python messaging
  - [ ] pdp
  - [ ] metadata
  - [ ] data access
  - [ ] drift detection
  - [ ] pipeline invocation service
  - [ ] configuration service
  - [ ] spark (including data transform)
  - [ ] whatever left

## Test Strategy/Script
- Run the build with integration test profile and make sure it succeed through `foundation-messaging`

## References/Additional Context
N/A

**Comment by peter-mcclonski** [comment]
Moved `hive-metastore-service` docker image from Java 11 to Java 17 as part of #127

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi @nartieri @carter-cundiff

**Comment by ewilkins-csi** [comment]
**OTS** looks good!

**Comment by ewilkins-csi** [comment]
✅ **Final Test** passed
1. `mvn clean install -Pintegration-test` on branch `feature-java17` succeeds up to and including `foundation-messaging-java`. (Fails at module 33/145 `extensions-authzforce-attribute`)
![Screenshot 2024-09-19 at 2 53 47 PM](https://github.com/user-attachments/assets/c2d1e01e-ce53-423f-af7b-12130b988d62)
