### ISSUE TITLE
BUG: Tilt Up fails if build cache is used due to failed Docker builds

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#142]
## Description
Any time a project with Docker images is built and has a hit in the Maven build cache for any of the Docker modules, project deployment fails because those modules don't have the appropriate files staged in the _target_ directory.

## Steps to Reproduce
1. Create a new project
2. Add a simple data-delivery pipeline  _[example](https://github.com/user-attachments/files/15805736/SimplePipeline.json)_
3. Run `./mvnw clean install` and follow manual actions
4. Repeat until there are no more manual actions printed
5. Deploy the project with `tilt up`
6. Note that the builds for project images fail with the following error:
```
Build Failed: ImageBuild: failed to compute cache key: failed to calculate checksum of ref 2ffefd1f-cac0-4055-b6ea-1eb13255fccc::v8ge44kfavcvmfkbw0mkdxkzd: failed to walk /var/lib/docker/tmp/buildkit-mount1603518359/target: lstat /var/lib/docker/tmp/buildkit-mount1603518359/target: no such file or directory
```

## Expected Behavior
After `tilt up`, all resources start successfully in the Tilt dashboard.

## Actual Behavior
Any resources that deploy project Docker images fail.  E.g.:
 - policy-decision-point
 - spark-worker-image

## Additional Context
**Version:** aiSSEMBLE 1.7.0

**Comment by epwilkins** [comment]
#482 made this OBE
