### ISSUE TITLE
Migrate downstream projects to use the updated Python module naming convention

### ISSUE THREAD

**Issue by jacksondelametter** [boozallen/aissemble#15]
In aiSSEMBLE, the following Python modules were renamed to reflect aiSSEMBLE.

- foundation-core-python &rarr; aissemble-foundation-core-python
- foundation-model-training-api &rarr; aissemble-foundation-model-training-api
- foundation-versioinig-service &rarr; aissemble-foundation-versioning-service
- foundation-drift-detection-client &rarr; aissemble-drift-detection-client
- foundation-enryption-policy-python &rarr; aissemble-encryption-policy-python
- foundation-model-lineage &rarr; aissemble-foundation-model-lineage
- foundation-data-lineage-python &rarr; aissemble-foundation-data-lineage-python
- foundation-messaging-python-client &rarr; aissemble-foundation-message-python-client
- foundation-pdp-client-python &rarr; aissemble-pdp-client-python
- foundation-transform-core-python &rarr; aissemble-foundation-transfor-core-python
- extensions-model-training-api-sagemaker &rarr; aissemble-extensions-model-training-api-sagemaker
- extensions-data-delivery-spark-py &rarr; aissemble-extensions-data-delivery-spark-py
- extensions-encryption-vault-python &rarr; aissemble-extensions-encryption-vault-python
- extensions-transform-spark-python &rarr; aissemble-extensions-transform-spark-python
- test-data-delivery-pyspark-model &rarr; aissemble-test-data-delivery-pyspark-model
- test-data-delivery-pyspark-model-basic &rarr; aissemble-test-data-delivery-pyspark-model-basie
- machine-learning-inference &rarr; aissemble-machine-learning-inference
- machine-learning-training &rarr; aissemble-machine-learning-training
- machine-learning-training-base &rarr; aissemble-machine-learning-training-base
- machine-learning-sagemaker-training &rarr; aissemble-machine-learning-sagemaker-training

A migration feature needs to be added in order for current downstream projects to use the new Python modules when upgrading aiSSEMBLE.

**Comment by akanshamishra617** [comment]
Hi there,

I'm interested in contributing to the development of a migration feature for this module renaming.

I've noticed several core Python modules within aiSSEMBLE have been renamed to include the "aiassemble-" prefix. This is a great step for clarity and organization.

To ensure a smooth upgrade path for existing projects, a migration feature seems essential. I'd be happy to help develop this feature.

Here are some initial thoughts:

The migration feature could potentially map old module names to their corresponding new names during the upgrade process.
This would allow existing projects to continue functioning seamlessly after upgrading aiSSEMBLE.
I'm open to discussing different approaches and collaborating on a solution.

Would you be open to a pull request outlining a potential implementation? Additionally, are there any specific guidelines or preferences for contributing to this type of feature?

**Comment by d-ryan-ashcraft** [comment]
@akanshamishra617 

Appreciate your question and willingness to help!  

This feature is almost complete - but you can definitely check it out as the [pull request](https://github.com/boozallen/aissemble/pull/31).  

The general approach is consistent with how we have been working migrations on aissemble for a while now:

- Whenever possible, migrations should seamlessly happen upon upgrade to the version of aissemble in which is becomes active with no manual intervention
- If sensible, write a generic migration that can be configured to support the current need
- Backup files automatically should there be a need for the user to roll back (though we expect projects to also be versioned)

We are using [Baton](https://github.com/TechnologyBrewery/baton) to drive our migrations - it's a very simple open source project that facilitates lightweight, but structured migrations in manner that is very easy to integrate into the aissemble build process.  You can find some other aissemble migrations here: https://github.com/boozallen/aissemble/tree/dev/foundation/foundation-upgrade (we've removed the old migrations from prior releases to reduce code bloat when migrating to this repository).

Thanks again!

**Comment by jacksondelametter** [comment]
This feature was complete on May 3, should have been closed a few months ago!
