### ISSUE TITLE
Feature: Create an initial Baton migration to migrate from using the Orphedomos plugin to the Fabric8 docker maven plugin

### ISSUE THREAD

**Issue by chang-annie** [boozallen/aissemble#154]
## Description
We have found that Orphedomos is lacking key features we need and instead of re-inventing the wheel, we have found that fabric8 plug-in is widely used, supported, and contains the features we need.

For this ticket, we want to create an initial baton migration that migrates aiSSEMBLE from using Orphedomos to the fabric8 docker maven plug-in. 

## DOD
- [x] confirm pom file configuration for [fabric8 docker maven plugin](https://github.com/fabric8io/docker-maven-plugin) that can replace our current Orphedomos maven plugin implementation
- [x] create initial baton migration that will migrate pom files containing references to Orphedomos maven plugin which do not include references to wheel dependencies to use [fabric8 docker maven plugin](https://github.com/fabric8io/docker-maven-plugin) instead. Migration should be inactive for now. 
- [x] Activate migration (should run on pom files except build-parent pom and -tests-docker pom)

## Test Strategy/Script
- pull in dev branch of aissemble and build
```
mvn clean install
```
- create downstream project using `1.7.0` version of aiSSEMBLE
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.7.0\
  -DgroupId=com.boozallen.aissemble.test \
  -DartifactId=issue-154\
  -DprojectGitUrl=git.example.com/issue-154 \
  -DprojectName="issue-154"
``` 
- Add the following pipeline to `issue-154-pipeline-models/src/main/resources/pipelines/SparkPipeline.json`
```
{
  "name": "SparkPipeline",
  "package": "com.example",
  "type": {
    "name": "data-flow",
    "implementation": "data-delivery-spark"
  },
  "dataLineage": true,
  "steps": [
    {
      "name": "ExampleSyncStep",
      "type": "synchronous",
      "alerting": {
        "enabled": false
      },
      "provenance": {
        "enabled": false
      },
      "dataProfiling": {
        "enabled": false
      }
    }
  ]
}
```  
- Build and follow all manual actions. Repeat until no more manual actions.
- Upgrade project to `1.8.0-SNAPSHOT` by updating version in build-parent within your root pom.xml
- Rebuild your downstream project 
- If you get the following error:
```
[INFO] DOCKER> ERROR: failed to solve: ghcr.io/boozallen/openjdk:11-slim: failed to resolve source metadata for ghcr.io/boozallen/openjdk:11-slim: ghcr.io/boozallen/openjdk:11-slim: not found
[ERROR] DOCKER> Error status (1) when building
```
- Then update your `issue-154-tests/issue-154-tests-docker/src/main/resources/docker/Dockerfile` line 7 to
```
FROM openjdk:11-slim
```
- Inside your `issue-154-docker/pom.xml file`, confirm there is no `orphedomos-maven-plugin`. Instead, you should see the new Fabric8 `docker-maven-plugin`
- before:
```
<plugin>
    <groupId>org.technologybrewery.orphedomos</groupId>
    <artifactId>orphedomos-maven-plugin</artifactId>
    <configuration>
        <skip>true</skip>
        <imageVersion>${project.version}</imageVersion>
        <imageName>${project.artifactId}</imageName>
    </configuration>
</plugin>
```  
- after
```
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>default-build</id>
            <configuration>
                <skip>true</skip>
                <images>
                    <image>
                        <name>${project.artifactId}:${project.version}</name>
                    </image>
                </images>
            </configuration>
        </execution>
    </executions>
</plugin>
``` 
- Confirm migration did not run for `issue-154-tests-docker/pom.xml file`. You should still see references to orphedomos-maven-plugin within the plugins block
- Confirm that the downstream docker module pom files (for example, `issue-154-docker/issue-154-spark-worker-docker/pom.xml`) had their packaging types updated from `orphedomos` to `docker-build`
- before:
```
<packaging>orphedomos</packaging>
``` 
- after:
```
<packaging>docker-build</packaging>
```

**Comment by aaron-gary** [comment]
Test steps are passing
