### ISSUE TITLE
Feature: As a consumer of the V2 Spark Infrastructure chart, I want to be able to utilize my spark ecosystem seamlessly without manual workarounds.

### ISSUE THREAD

**Issue by peter-mcclonski** [boozallen/aissemble#157]
## Description
Building upon #149 and preceding tickets, we would like to resolve manual workarounds necessary to make the v2 spark-infrastructure chart work out of the box.  We note that there will be future work to integrate the chart with the Universal Config Service.  Because the UCS work is a precondition to release of this feature, this work will remain in a feature branch at the completion of this issue.

## Definition of Done
- [x] The `aissemble-spark-infrastructure-deploy-v2` profile will be prompted for automatically when needed
  - [x] Legacy profiles including those for `hive-metastore-db`, `hive-metastore-service`, and `aissemble-spark-infrastructure-deploy` (v1) will be deprecated
    - [x] Update any `foundation-mda` tests to no longer refer to deprecated profiles.
  - [x] None of the above legacy profiles will be prompted for manual addition.
- [x] The default generated `application.properties` for `data-access` pipelines will be updated to point to the appropriate endpoint (`jdbc:hive2://spark-infrastructure-sts-service:10001/default;transportMode=http;httpPath=cliservice`)
  - [x] A baton migration shall be established which performs the necessary updates for existing projects with data-access pipelines
- [x] Both generated and upstream SparkApplication configurations shall be updated to function with the new structure
- [x] Documentation shall be produced to guide users through updating to the new v2 structure
- [x] Draft release notes for v1.9.0 will be produced, and updated to include information on the new v2 helm chart profile.

## Test Strategy/Script
1. Pull the latest version of the aiSSEMBLE `feature/spark-infrastructure-v2-default` branch.
2. Execute `mvn clean install`
1. Generate a new project using the following command:
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.8.0-SNAPSHOT \
                          -DartifactId=test-project\
                          -DgroupId=org.test \
                          -DprojectName='Test' \
                          -DprojectGitUrl=test.org/test-project\
&& cd test-project
```
3. Add the following pipeline to `test-project-pipeline-models/src/main/resources/pipelines/`
```
{
  "name": "PysparkPersist",
  "package": "com.boozallen",
  "type": {
    "name": "data-flow",
    "implementation": "data-delivery-pyspark"
  },
  "steps": [
    {
      "name": "PersistData",
      "type": "synchronous",
      "persist": {
        "type": "hive"
      }
    }
  ]
}
```
4. Add the following record to `test-project-pipeline-models/src/main/resources/records/`
```
{
  "name": "CustomRecord",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example custom record for Pyspark Data Delivery Patterns",
  "fields": [
    {
      "name": "customField",
      "type": {
        "name": "customType",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}
```
5. Add the following dictionary to `test-project-pipeline-models/src/main/resources/dictionaries/`
```
{
  "name": "PysparkDataDeliveryDictionary",
  "package": "com.boozallen.aiops.mda.pattern.dictionary",
  "dictionaryTypes": [
    {
      "name": "customType",
      "simpleType": "string"
    }
  ]
}
```
6. Execute `mvn clean install -Dmaven.build.cache.skipCache=true` repeatedly, resolving all presented manual actions until none remain.
7. Within `test-project-pipelines/pyspark-persist/src/pyspark_persist/step/persist_data.py`, define the implementation for `execute_step_impl` as follows:
```
    def execute_step_impl(self) -> None:
        from ..record.custom_record import CustomRecord
        from ..schema.custom_record_schema import CustomRecordSchema
        custom_record = CustomRecord.from_dict({"customField": "foo"})
        record2 = CustomRecord.from_dict({"customField": "bar"})
        df = self.spark.createDataFrame(
            [
                custom_record,
                record2
            ],
            CustomRecordSchema().struct_type
        )
        self.save_dataset(df, "my_new_table")
```
8. Within `test-project-pipelines/pyspark-persist/pom.xml`, replace each reference to `${aissemble.helm.repo.protocol}://${aissemble.helm.repo}/aissemble-spark-application` to the path on your local system to the updated spark-application within the aissemble codebase.
9. Within your `Tiltfile`, replace references to the `aissemble-spark-application` within the aissemble GHCR OCI repository with the path on your local system to the updated spark-application within the aissemble codebase.
10. Execute `mvn clean install -Dmaven.build.cache.skipCache=true` once.
11. To avoid an unrelated bug, open your Tiltfile, and remove the entry for `pipeline-invocation-service`.
12. Execute `tilt up`
13. Once all resources are ready, trigger the `pyspark-persist` pipeline
14. Use `kubectl get pods | grep data-access` to get the name of the data access pod.
15. Use `kubectl exec -it <DATA_ACCESS_POD_NAME> -- bash` to enter the data access pod
16. Execute `curl -X POST localhost:8080/graphql -H "Content-Type: application/json" -d '{ "query": "{ CustomRecord(table: \"my_new_table\") { customField } }" }'` and ensure that data including two records is returned, ie: `{"data":{"CustomRecord":[{"customField":null},{"customField":null}]}}`
17. Note on step 16: If you don't get any values back, in a fresh prompt, execute `kubectl get svc | grep sts`.  It can take a minute or two to provision the service.
18. Navigate to `localhost:18080` and ensure that the Spark History Server is visible and has recorded the pipeline execution for `pyspark-persist`.
19. Tilt down and delete the created project.
20. Generate a new project using the following command:
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.7.0 \
                          -DartifactId=test-project\
                          -DgroupId=org.test \
                          -DprojectName='Test' \
                          -DprojectGitUrl=test.org/test-project\
&& cd test-project
```
21. Execute steps 3 thru 6.
22. Follow the upgrade steps detailed in the updated DRAFT_RELEASE_NOTES.md to migrate to 1.8.0-SNAPSHOT.
23. Note: You may need to add the following snippet to each of your project's pyproject.toml files:
```
[[tool.poetry.source]]
name = "devpypi"
url = "https://test.pypi.org/simple/"
priority = "supplemental"
```
25. Execute steps 7 thru 18.

**Comment by csun-cpointe** [comment]
OTS completed!!

**Comment by carter-cundiff** [comment]
Testing passed:
1.8.0-SNAPSHOT:
![image](https://github.com/boozallen/aissemble/assets/129905339/b272d3c1-bef4-4feb-9e20-c9df062c9b85)
![image](https://github.com/boozallen/aissemble/assets/129905339/9632aa28-e037-4b3f-85f3-05f09d319990)
1.7.0 -> 1.8.0-SNAPSHOT:
![image](https://github.com/boozallen/aissemble/assets/129905339/55e289de-44bc-4fb5-8f18-d4a6088eca5b)
![image](https://github.com/boozallen/aissemble/assets/129905339/66478a59-710e-4fc9-9d84-46330dad0440)
