### ISSUE TITLE
BUG: build cache does not incorporate plugin updates

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#159]
## Description
When using aissemble, changes to Maven plugins that are on SNAPSHOT versions do not correctly invalidate the cache.  This requires all testing to be done with the cache disabled when working with plugin updates, which takes more time and as is easy to forget and get a false-positive/negative results.  

## Steps to Reproduce
Please note that these test steps apply to any aissemble module or downstream aissemble instantiation.  We are using `fermenter-mda` for these test steps because this type of test is the fastest path to see the challenge.

1. Update the `build-parent` module to use the latest SNAPSHOT version of `fermenter-mda` (2.10.4-SNAPSHOT)
2. Build a module leveraging `fermenter-mda` in order to create a fresh build with this version of fermenter.  This should build because aissemble is not currently using a `fermenter-mda`SNAPSHOT release - so this step is needed to prime the cache.
```
mvn clean install -pl :test-data-delivery-spark-model-basic
```
3. Rerun the above step to note that it hits that cache:
```
mvn clean install -pl :test-data-delivery-spark-model-basic
```
4. Clone fermenter-mda:
```
git@github.com:TechnologyBrewery/fermenter.git
```
5. Make a change to the fermenter source code (can be a comment, changed output string, whatever) and rebuild.  This *should* create a new version of the plugin that will invalidate that build cache within aissemble.
```
mvn clean install
```
6. Rerun the above aissemble module build with the expectation that it invalidates the cache.  But you will find it still hits that cache:
```
mvn clean install -pl :test-data-delivery-spark-model-basic
```

## Test Steps
Use the _Steps to Recreate_ above, with the following notes:
- **PRECONDITION:** Update `build-parent/pom.xml` with the following:
```diff
+ <version.fermenter>2.10.4-SNAPSHOT</version.fermenter>
- <version.fermenter>2.10.3</version.fermenter>
```
- Step 6 will now pass.
- Next run the archetype test to ensure that the changes to that pom work correctly:
```
mvn test -pl :foundation-archetype -Parchetype-test
```

Please note this can also be done with _any_ of the following plugins as well, as they are also included in the fix (this represents the set of plugs directly within aissemble as well as those plugins that are frequently contributed to by the aissemble team):
* `artifacts-maven-plugin`
* `foundation-maven-plugin`
* `mda-maven-plugin`
* `habushu-maven-plugin`
* `fermenter-mda`
* `baton-maven-plugin`

**Comment by cpointe-ibllanos** [comment]
Was able to test that newer plugin artifacts invalidate the build cache and confirm that caching still works after the first build.
