### ISSUE TITLE
Feature: Update to Pydantic 2.7.x

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#161]
## Description
aissemble is on the legacy version pydantic (`1.10.x`).  We should move up to `2.7.x` to gain new features and improvements that are not being added to the legacy codebase at this time.  

This is especially doable since there is an incremental approach we can use:

> Pydantic V1.10 vs. V2
> Pydantic V2 is a ground-up rewrite that offers many new features, performance improvements, and some breaking changes
> compared to Pydantic V1.
> 
> If you're using Pydantic V1 you may want to look at the [pydantic V1.10 Documentation](https://docs.pydantic.dev/) or, [1.10.X
> fixes git branch](https://github.com/pydantic/pydantic/tree/1.10.X-fixes). Pydantic V2 also ships with the latest version of
> Pydantic V1 built in so that you can incrementally upgrade your code base and projects: from pydantic import v1 as pydantic_v1.

## Definition of Done (DOD):
Update pydantic 1.10.x to 2.8.x or above. 
Fix any breaking changes due to upgrade of pydantic to new versions ([migration guide](https://docs.pydantic.dev/latest/migration/) is available to help with fixing version changes) 
Ensure complete aiSSEMBLE build is succeed. 
Run integration test.
Run archtype test.

## Testing Steps:

1. Make sure poetry correctly points to pydantic latest version

- Git into feature branch.
- cd into one of modules listed in the comment
- Ex)
`cd <your path to github>/aissemble/Aissemble-extension-model-training-api-sagemaker`
- run this command to verify pydantic is 2.8.x or above 
`poetry show`
2. Make sure aiSSEMBLE can be built without any issues.
- use `mvn clean instal`l to verify build success
- Run Integrated test of aiSSEMBLE using following command 
`mvn clean install -P integration-test`
- Run Archetype test of aiSSEMBLE using following command: 
`mvn clean install -P archetype-test`
3. build downstream project one with pyspark implementaion and ml pipeline and test 1.7 to 1.8 to verify there is no breaking change.
- build branch of aissemble 
`mvn clean install`
- create downstream project using 1.7.0 of aiSSEMBLE artifact id, giturl and project can be any name of your choosing for test. 
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.7.0\
  -DgroupId=com.boozallen.aissemble.test \
  -DartifactId=issue-161\
  -DprojectGitUrl=git.example.com/issue-161 \
  -DprojectName="issue-161”
```
- This will generate code, go into generate code and add the following pipeline to {downstreamproject}/src/main/resources/pipelines/MlPipelineInference.json

```
{
    "name": "MlPipelineInference",
    "package": "com.example",
    "type": {
      "name": "machine-learning",
      "implementation": "machine-learning-mlflow",
      "versioning": {
        "enabled": false
      }
    },
    "steps": [
      {
        "name": "PipelineInferenceStep",
        "type": "inference",
        "inbound": {
          "type": "messaging",
          "channelName": "train"
        }
      }
    ]
  }
```

- Build using mvn clean install if manual actions are listed in build output, follow all manual actions.
- Repeat until no more manual actions.
- Upgrade project to 1.8.0-SNAPSHOT by updating version in build-parent within your root pom.xml
- Rebuild your downstream project using 
`mvn clean install`
- Verify build succeeded.

**Comment by jaebchoi** [comment]
Completed DoD with @jacksondelametter @J-Clingerman @habibimoiz

**Comment by jaebchoi** [comment]
Completed OTS with @aaron-gary

**Comment by chang-annie** [comment]
closing ticket as done! all test steps are passing
- [x] confirmed pydantic version is 2.8.x 
- [x] confirmed successful full build of aiSSEMBLE 
- [x] integration-test profile succeeds 
- [x] archetype-test profile succeeds 
- [x] upgraded downstream project with ML pipeline from 1.7.0 to 1.8.0-SNAPSHOT

**Comment by chang-annie** [comment]
closing ticket as done! all test steps are passing
- [x] confirmed pydantic version is 2.8.x 
- [x] confirmed successful full build of aiSSEMBLE 
- [x] integration-test profile succeeds 
- [x] archetype-test profile succeeds 
- [x] upgraded downstream project with ML pipeline from 1.7.0 to 1.8.0-SNAPSHOT
