### ISSUE TITLE
Feature: Update messaging integration test infrastructure.

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#166]
## Description
Several of the images/libraries we use to execute integration tests are a bit out of date.  We should be update them to leverage the latest enhancements and security fixes. The following can be updated:

- TestContainers
- RedPanda (lightweight Kafka impl)
- Artemis (lightweight ActiveMQ impl)

## DOD
Acceptance criteria required to realize the requested feature
- [x] Update TestContainers in POMs and pyproject.toml files
- [x] Update redpanda images
- [x] Update artemis images

## Test Strategy/Script
OTS:
 * Run `mvn clean install -Pintegration-test` and ensure build passes

Final Test:
 * Verify latest build in CI passed

**Comment by ewilkins-csi** [comment]
**DoD**/**OTS** with @Cho-William

**Comment by Cho-William** [comment]
Final test passed, see screenshot:
<img width="1272" alt="Screenshot 2024-06-25 at 12 35 14 PM" src="https://github.com/boozallen/aissemble/assets/149192267/b0f83b87-d1ed-4fec-8b65-64003ab27655">
