### ISSUE TITLE
Feature: As an aiSSEMBLE developer, I want baseline docker modules to build with fabric8 so I can leverage multi architecture builds

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#168]
## Description
Currently we use the [orphedomos maven plugin](https://github.com/TechnologyBrewery/orphedomos) for all our docker builds. This does not support multi architecture builds, resulting is us performing two parallel aiSSEMBLE builds on the different architectures to create our docker images. By utilizing the [fabric8 docker maven plugin](https://github.com/fabric8io/docker-maven-plugin) for our docker builds, we can create images for both architectures in a single aiSSEMBLE build. This issue aims to convert our Python docker modules to using fabric8 with a separate issue for the Java docker modules and eventual multi architecture build.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Clean up module dependencies to include the single direct python dependency for each docker module below
  - [x]  Update python dependencies to be type `habushu` for all transitive dependencies

Removed due to follow on ticket needed for [Habushu #164](https://github.com/TechnologyBrewery/habushu/issues/164)
- [ ] ~~Update the modules to utilize the [Habushu containerize-dependencies goal](https://github.com/TechnologyBrewery/habushu?tab=readme-ov-file#leveraging-the-containerize-dependencies-goal-to-prepare-a-containerized-virtual-environment) for including python monorepo dependencies~~
  - [ ] ~~Goal will automatically collect any transitive dependencies~~
  - [ ] ~~Manually modify the `Dockerfile` pending the completion of [Habushu #149](https://github.com/TechnologyBrewery/habushu/issues/149)~~
- [x] Replace orphedomos with fabric8 for building all docker modules

## Test Strategy/Script
- Run the following in aiSSEMBLE `mvn clean install -pl :extensions-docker -amd`
  - Verify all the docker images are created with the `1.8.0-SNAPSHOT` tag
- Run the following in aiSSEMBLE `mvn clean install -pl :aissemble-fastapi -Pci,x86 -Dmaven.build.cache.skipCache=true`
  - Verify the docker image is created with the `1.8.0-SNAPSHOT-amd64` tag
  - Verify the architecture is `amd64` with the following command:
    ```
    docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" ghcr.io/boozallen/aissemble-fastapi:1.8.0-SNAPSHOT-amd64
    ```
- Run the following in aiSSEMBLE `mvn clean install -pl :aissemble-fastapi -Pci,arm64 -Dmaven.build.cache.skipCache=true`
  - Verify the docker image is created with the `1.8.0-SNAPSHOT-arm64` tag
  - Verify the architecture is `arm64` with the following command:
    ```
    docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" ghcr.io/boozallen/aissemble-fastapi:1.8.0-SNAPSHOT-arm64
    ```

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by carter-cundiff** [comment]
DOD with @ewilkins-csi and @Cho-William

**Comment by csun-cpointe** [comment]
OTS completed!!

**Comment by csun-cpointe** [comment]
test passed!!
