### ISSUE TITLE
Create initial build workflow (Actions)

### ISSUE THREAD

**Issue by aaron-gary** [boozallen/aissemble#17]
We need to create the initial build workflow that will create a runner with the following installed:

Python
Poetry
Pyenv
Docker
Helm
Maven 
JDK

**Comment by d-ryan-ashcraft** [comment]
Recommend we do not use pyenv on the actions - adds about 3-4 minutes to each build.  Recommend checking out what we did in `booz-allen-maven-licenses` with the straight (and fast) Python install as well as `-Dhabuhus.usePynv=false`: https://github.com/boozallen/booz-allen-maven-licenses/blob/dev/.github/workflows/build.yaml

**Comment by d-ryan-ashcraft** [comment]
I think this might be a dup of #2?

**Comment by aaron-gary** [comment]
> I think this might be a dup of #2?

Correct.  Thanks for surfacing this.  Will move all work over to #2
