### ISSUE TITLE
Feature: As an aiSSEMBLE user, I want the MDA Docker module templates to leverage fabric8, so that I can manage Docker builds with fabric8 in downstream projects

### ISSUE THREAD

**Issue by Cho-William** [boozallen/aissemble#171]
## Description
This issue is part of a series of issues targeting moving aiSSEMBLE from [orphedomos](https://github.com/TechnologyBrewery/orphedomos) to [fabric8](https://github.com/fabric8io/docker-maven-plugin). Issue #168 is targeting making this update in the baseline's python Docker modules, and Issue #154 is targeting one (separate) Docker module in the baseline, as well as the migration for downstream projects. 

This issue addresses updating the baseline's MDA generation such that downstream projects will leverage fabric8 instead of orphedomos.  

## DOD
- [x] Update relevant files in `foundation-mda` and `foundation-archetype` to leverage fabric8's [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) instead of orphedomos for the relevant downstream project's `pom.xml` files (see implementation details)
- [x] Ensure updated templates and generation are (reasonably) in line with the Issue [#154](https://github.com/boozallen/aissemble/issues/154) migrations
- [x] Ensure the docker image build runs as part of the default maven build (see Implementation Details and Affected Files)
- [x] Update the orphedomos sagemaker configurations manual actions to reference the correct fabric8 configurations
- [x] Update the release notes draft covering the change to fabric8
- [x] Update the antora docs for SageMaker configuration change
- [x] Adjust the archetype resources pom.xml to include `foundation-mda` and `foundation-upgrade` as (workaround) dependencies

## DOD Questions
- are we no longer going to force users to pass an extra argument to run the docker module builds
  - yes, although it seems there are redundant docker builds in the tilt file, the cache should have them available

## Implementation Details
- templates/archetype poms for downstream projects to change will include:
  -  the parent docker module `pom.xml` found in `<project-name>/<project-name>-docker`  
  - each individual docker module's `pom.xml` found in `<project-name>/<project-name>-docker/<project-name>-*`
  - the test docker `pom.xml` found in `<project-name>/<project-name>-tests/<project-name>-tests-docker`
- existing profile that disables docker builds by default will be removed for now, but will likely be reintroduced in the future
- testing changes for this issue will rely on the completion of the two related Issues mentioned above

## Affected pom.xml Files
- `foundation/foundation-archetype/src/main/resources/archetype-resources/__rootArtifactId__-docker`
- `foundation/foundation-archetype/src/main/resources/archetype-resources/__rootArtifactId__-tests/__rootArtifactId__-tests-docker/pom.xml`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/data.access.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/airflow.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/custom.lineage.consumer.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/inference.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/mlflow.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/policy.decision.point.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/sagemaker-training.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/spark-worker.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/training.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/vault.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/general-docker/versioning.docker.pom.xml.vm`
- `foundation/foundation-mda/src/main/resources/templates/notifications/notification.sagemaker.docker.pom.vm`

## Test Strategy/Script
1. Generate a 1.8.0-SNAPSHOT downstream project: 
```
mvn archetype:generate \
-DarchetypeGroupId=com.boozallen.aissemble \
-DarchetypeArtifactId=foundation-archetype \
-DarchetypeVersion=1.8.0-SNAPSHOT \
-DgroupId=com.example \
-DartifactId=example \
-DprojectGitUrl=url \
-DprojectName=example \
&& cd example
```
2. Add the two pipelines: 
[ExampleMachineLearningPipeline.json](https://github.com/user-attachments/files/16088491/ExampleMachineLearningPipeline.json)
[SparkPipeline.json](https://github.com/user-attachments/files/16088492/SparkPipeline.json)
3. Build the project ONCE with `mvn clean install -Dmaven.build.cache.skipCache=true`
4. Successively run the following until all manual actions are resolved: `mvn clean generate-sources -Dmaven.build.cache.skipCache=true`
5. Remove the `<skip>true</skip>` `docker-maven-plugin` configuration from `example-docker/pom.xml`
6. Comment out the `pip` `requirements.txt` installation (line 25) of `example-docker/example-logistic-training-docker/src/main/resources/docker/Dockerfile`
7. Complete a full build with `mvn clean install -Dmaven.build.cache.skipCache=true`
8. Confirm successful build of the docker images
9. Run `tilt up; tilt down`
10. Confirm successful deployment with tilt

**Comment by Cho-William** [comment]
DOD completed with @ewilkins-csi and @carter-cundiff

**Comment by Cho-William** [comment]
OTS completed with @chang-annie

**Comment by csun-cpointe** [comment]
test passed!!
