### ISSUE TITLE
Feature: As a baseline developer, I want docker image builds to be multi-architecture in CI so they can be built together on a single node

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#179]
## Description
Currently we use the [orphedomos maven plugin](https://github.com/TechnologyBrewery/orphedomos) for all our docker builds. This does not support multi architecture builds, resulting is us performing two parallel aiSSEMBLE builds on the different architectures to create our docker images. By utilizing the [fabric8 docker maven plugin](https://github.com/fabric8io/docker-maven-plugin) for our docker builds, we can create images for both architectures in a single aiSSEMBLE build. 

As part of enabling multi-architecture docker image builds effort, this issue will focus on enabling our CI to build multi-architecture docker images on a single node.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Turn on multi-architecture builds for the `ci` profile
- [x] Local builds should continue to function the same, building only the native architecture as the "main" image (no architecture specifier)
- [x] Ensure a [manifest list](https://docs.docker.com/reference/cli/docker/manifest/#create-and-push-a-manifest-list) is created as part of the build process
- [x] Update the JenkinsfileBuild.groovy script on the [CI build branch](https://github.boozallencsn.com/aissemble/aissemble/tree/fix-ci) to build on only one Jenkins node, and remove the manual manifest list creation logic
- [x] Update the JenkinsfileRelease.groovy script on the same branch similarly
- [x] Q: check if the fabric8 will create different platform tags for the docker image => A: No

## Test Strategy/Script
- OTS only:
   - Verify below steps in the  [Jenkins CI test build](https://jenkins.aiops.boozallencsn.com/job/aissemble-build-test/) 
- Verify the most recent CI build passed and make sure it only uses single node (no x86 or arm64 label presents in the log) and search through the most recent build log with `--platform linux/amd64,linux/arm64`, you should find all 22 docker images built with multi-platform command.
- Verify that **only** the https://github.com/boozallen/aissemble/pkgs/container/aissemble-versioning 1.8.0-SNAPSHOT tag created in the most recent timestamp
- Verify that the most recent [git action build](https://github.com/boozallen/aissemble/actions) passed.

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by carter-cundiff** [comment]
DOD looks good

**Comment by Cho-William** [comment]
OTS passed

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/boozallen/aissemble/assets/129905339/2ad38944-6197-4ab9-87a5-e0d86009c53c)
![image](https://github.com/boozallen/aissemble/assets/129905339/7a36268d-e2eb-4a54-bb87-bd32e309cbe3)
![image](https://github.com/boozallen/aissemble/assets/129905339/782eacea-9def-4ba4-b6c0-903bcb56f8ee)
