### ISSUE TITLE
Feature: As an aiSSEMBLE user, I want the ci and integration-test profiles of the MDA Docker templates to leverage fabric8, so that I can manage Docker builds with fabric8 in downstream projects

### ISSUE THREAD

**Issue by Cho-William** [boozallen/aissemble#191]
## Description
Issues #171, #168, and #154, established the majority of aiSSEMBLE's transition from Orphedomos to fabric8. However, the `ci` and `integration-test` profiles in the templates for downstream projects still use Orphedomos. This issue will update these to leverage fabric8, thus closing out this transition effort.

## DOD
- [x] update the `ci` and `integration-test` profiles found in downstream templates to use fabric8
- [x] finalize the baton migration to also address the profiles
- [x] ensure downstream project migration is functional
- [x] update release notes draft where necessary
- [x] update migration to include executions block for profile configs

## BDD Scenarios
```feature
# added scenario  
# has table for ci and integration-test
Scenario Outline: Pom file with Orphedomos plugin configuration in a profile is migrated to Fabric8 docker-maven-plugin
```

## Implementation Details
- impacted file(s) for `ci` profile:
  - `foundation/foundation-archetype/src/main/resources/archetype-resources/__rootArtifactId__-docker/pom.xml`
- impacted file(s) for `integration-test` profile: 
  - `foundation/foundation-archetype/src/main/resources/archetype-resources/__rootArtifactId__-tests/__rootArtifactId__-tests-docker/pom.xml`
- remove pom filtering from existing fabric8 migration

## Test Strategy/Script
1. **OTS Only:** In the aissemble baseline on feature branch, run
```
mvn clean install -pl :foundation-upgrade,:foundation-archetype -am -Dmaven.build.cache.enabled=false
```
2. Fully generate a `1.7.0` aiSSEMBLE project: 
```
mvn archetype:generate \
-DarchetypeGroupId=com.boozallen.aissemble \
-DarchetypeArtifactId=foundation-archetype \
-DarchetypeVersion=1.7.0 \
-DgroupId=com.example \
-DartifactId=example \
-DprojectGitUrl=url \
-DprojectName=example \
&& cd example
```
3. Add this spark pipeline to the project [SparkPipeline.json](https://github.com/user-attachments/files/16164576/SparkPipeline.json)
4. Run `mvn clean install -Dmaven.build.cache.enabled=false` until all manual actions are resolved
7. Increment the build parent version to `1.8.0-SNAPSHOT` in the project's root pom file
8. Build the project with `mvn clean install` once
10. Run `mvn clean` then ensure no orphedomos references are in the project (can do global string search with IDE)
11. Set `<docker.project.repository.url>ghcr.io</docker.project.repository.url>` in the project root pom
13. Comment out the zookeeper yaml and k8s_yaml call in the test helm tilt file found at: `*-tests/example-tests-helm/src/main/resources/Tiltfile`
14. Remove the `boozallen/` prefix in the `ref` of the pdp docker build in `*-tests/example-tests-helm/src/main/resources/Tiltfile`
15. remove the `${DOCKER_BASELINE_REPO_ID}boozallen/` prefix in the `*-tests/*-tests-docker` docker file `FROM` call
16. Set the image name in `example-tests/example-tests-helm/src/main/resources/test-chart/values.yaml` so that it is just `example-tests-docker` (should have not repository prefix)
17. Ensure that the `ci` profile can build: `mvn clean install -Pci -Dmaven.build.cache.enabled=false`
18. Ensure that the project's `integration-test` profile can build: `mvn clean install -Pintegration-test -Dmaven.build.cache.enabled=false`
19. note: the s3 local tilt output may show some repeated lines of the following log: `INFO --- [et.reactor-0] localstack.request.aws     : AWS s3.HeadObject => 404 (NoSuchKey)`, however this can be ignored as the pipeline is still functional
20. you should get the following error (to be expected):

```
NAME: pipeline-test
LAST DEPLOYED: Thu Jul 11 11:01:38 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     test
Last Started:   Thu Jul 11 11:01:39 2024
Last Completed: Thu Jul 11 11:01:59 2024
Phase:          Failed
Error: 1 error occurred:
	* pod test failed
```
21. navigate to `*-tests/*-tests-helm/src/main/resources` and tilt down
22. remove the `test` pod with `kubectl delete pod test`, if that fails, simply reset your kubernetes cluster via rancher (without deleting container images)
23. In a new directory fully generates a `1.8.0-SNAPSHOT`: 
```
mvn archetype:generate \
-DarchetypeGroupId=com.boozallen.aissemble \
-DarchetypeArtifactId=foundation-archetype \
-DarchetypeVersion=1.8.0-SNAPSHOT \
-DgroupId=com.example2 \
-DartifactId=example2 \
-DprojectGitUrl=url \
-DprojectName=example2 \
&& cd example2
```
24. repeat steps 3-22, but skip steps 5 and 6

**Comment by Cho-William** [comment]
DOD completed @carter-cundiff @ewilkins-csi @nartieri

**Comment by Cho-William** [comment]
Integration Test Tiltfile changes (will need to be fixed in follow-on ticket):
- disable zookeeper
- docker build of PDP does not seem to work

**Comment by Cho-William** [comment]
OTS completed with @carter-cundiff and @csun-cpointe

**Comment by carter-cundiff** [comment]
Testing passed
