### ISSUE TITLE
BUG: Pipeline invocation service uses incompatible --repo flag with new spark application helm chart

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#195]
## Description
The pipeline invocation service makes a call to helm install the `aissemble-spark-application` chart using your pipeline SparkApplication as the values for the chart. This helm install call uses the outdated way of accessing the spark application helm chart with the `--repo` flag. Due do the new helm charts being stored in [OCI-based registries](https://helm.sh/docs/topics/registries/), you cannot access them using the `--repo` flag and must instead use a direct reference to the chart. 

## Steps to Reproduce
Clear, specific, and detailed steps taken to enable reproduction of the bug for investigation.
1. Create a new project from archetype:
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.8.0-SNAPSHOT -DgroupId=com.test -DartifactId=test-195 -DprojectGitUrl=url -DprojectName=test-195 && cd test-195
```

2. Add the attached [SparkPipeline.json](https://github.com/user-attachments/files/16145599/SparkPipeline.json) to `example-pipeline-models/src/main/resources/pipelines/`
3. Run `mvn clean install -Dmaven.build.cache.skipCache=true` until all the manual actions are complete
4. `tilt up;tilt down`
5. In another terminal, trigger the pipeline with the invocation service using the following command:
```
curl --location 'http://localhost:30004/invoke-pipeline/start-spark-operator-job' \
--header 'Content-Type: application/json' \
--data '{
    "applicationName": "spark-pipeline",
    "profile": "dev",
    "overrideValues": {}
}'
```

6. Wait around 30s and verify the pipeline ran successfully by viewing it's logs with the following command:
```
kubectl logs spark-pipeline-driver
```

## Expected Behavior
- The pipeline runs successfully and you can view it's logs

## Actual Behavior
- The pipeline invocation service fails to start the pipeline

## Additional Context
- Log output from the invocation service:
```
2024-07-09 17:11:46,319 ERROR [com.boo.ais.pip.inv.ser.uti.exe.HelmCommandExecutor] (executor-thread-0) Executing Helm command: helm install spark-pipeline --repo ghcr.io/boozallen --version 1.8.0-SNAPSHOT --values /deployments/sparkApplicationValues/spark-pipeline-base-values.yaml --values /deployments/sparkApplicationValues/spark-pipeline-dev-values.yaml --set spec.serviceEnabled=false aissemble-spark-application
2024-07-09 17:11:46,348 INFO  [com.boo.ais.pip.inv.ser.uti.exe.HelmCommandExecutor] (Exec Stream Pumper) Error: INSTALLATION FAILED: could not find protocol handler for: 
2024-07-09 17:11:46,351 ERROR [com.boo.ais.pip.inv.ser.PipelineInvocationAgent] (executor-thread-0) Error encountered submitting application spark-pipeline to the cluster: : com.boozallen.aissemble.pipeline.invocation.service.util.exec.ShellExecutionException: Could not invoke command! See output above.
```

## DOD
- [x] Update the pipeline invocation service to work with the OCI based spark application helm chart

## Test Strategy/Script
- **OTS Only:** 
  - Run the following in aiSSEMBLE: `mvn clean install -pl :extensions-pipeline-invocation-service,:aissemble-pipeline-invocation`
- Follow the steps to reproduce above
- Verify you get the expected behavior

**Comment by csun-cpointe** [comment]
DoD looks good!!

**Comment by Cho-William** [comment]
Final Test Passed! Lead Time: 2 days
![Uploading Screenshot 2024-07-10 at 5.38.42 PM.png…]()
