### ISSUE TITLE
Feature: As a user of universal configurations, I want to deploy a mutating admissions webhook so that I can ingest my configurations

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#209]
## Description
A [Kubernetes web hook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks:~:text=monitor%20admission%20webhooks.-,What%20are%20admission%20webhooks%3F,-Admission%20webhooks%20are) is a service that runs in a Kubernetes cluster and monitors the cluster according to a set of predefined rules. These rules are defined within the webhook yaml and can specify which events to catch such as when a pod is created. When these events occur, the web hook is invoked and an AdmissionReview object is passed to our mutate method defined as a quarkus endpoint. The AdmissionReview object contains an AdmissionRequest which holds the YAML data for the pod that was created. This data can be intercepted and updated as needed. The new data is then packaged into the AdmissionResponse which is updated in the Kubernetes object. This can be used to inject environment variables or update other parts of the YAML.

**Questions**:
- Do we want to include the resource modifications as part of this ticket, or just create the webhook?
  - A: Will be handled in follow on ticket

## DOD
- [x] Create a new endpoint within `foundation-configuration-store` to act as the [MutatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook)
  - [x] Investigate priority of multiple webhooks for the same resource - order is not guaranteed or configurable 
  - [x] Endpoint will simply log it was called, follow on ticket will handle injection logic
- [x] Update `aissemble-configuration-store-chart` helm chart to utilize the new webhook
  - [x] Webhook should be called on all resources for CREATE and UPDATE only 
  - [x] Follow on will implement resource selection logic

### BDD Scenarios:
```
Scenario: The configuration service can process Kubernetes resources
```
## Test Strategy/Script
- **OTS Only**:
  - Run the following
    ```
    mvn clean install -pl :foundation-mda,:foundation-configuration-store,:aissemble-quarkus,:aissemble-configuration-store,:aissemble-quarkus-chart,:aissemble-configuration-store-chart -Dmaven.build.cache.skipCache=true
    ```

- Create a downstream project from the archetype using the following command:
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.8.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-209 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-209 \
  && cd test-209
```
- Add to the fermenter-mda plugin executions in `test-209-deploy/pom.xml`
```
<execution>
    <id>configuration-store</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>generate-sources</goal>
    </goals>
    <configuration>
        <basePackage>com.boozallen.aissemble.test</basePackage>
        <profile>configuration-store-deploy-v2</profile>
        <!-- The property variables below are passed to the Generation Context and utilized
             to customize the deployment artifacts. -->
        <propertyVariables>
            <appName>configuration-store</appName>
        </propertyVariables>
    </configuration>
</execution>
```
- Build the project with `mvn clean install -pl :test-209-deploy` and complete the manual action
- **OTS Only**:
  - Update the `test-209-deploy/src/main/resources/apps/configuration-store/Chart.yaml` repository field to use your local helm chart:
  ```
  dependencies:
    - name: aissemble-configuration-store-chart
      version: 1.8.0-SNAPSHOT
      repository: file://../../../../../../../aissemble/extensions/extensions-helm/aissemble-configuration-store-chart
  ```
  - Build the project again with `mvn clean install -pl :test-209-deploy`

- Download and unzip the attached [209-helper.zip](https://github.com/user-attachments/files/16394217/209-helper.zip)
- **Mac users** 
  - Copy the src directory to the root of the project and update the `configuration_files_path` in the `Tiltfile` to the following:
  ```
  configuration_files_path = 'src/main/resources/configurations'
  ```
- **WSL Users**:
  -  Copy the src directory to windows file system and update the `project_path` and `configuration_files_path` in the `Tiltfile` to the following:
  ```
  project_path='/mnt/c/Users/YOUR_USER/PATH/TO/290-helper`
  configuration_files_path = 'src/main/resources/configurations'
  ```

- Comment out the `Kafka` resource in the `Tiltfile`
- `tilt up` and wait until the `configuration-store` resource is ready
- Create a file `pod.yaml` with the following content:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "infinity"]

```

- In the same directory where you created the `pod.yaml`, run the following:
```
kubectl apply -f pod.yaml
```

- Verify the pod deploy successfully with:
```
kubectl get pods -n default
```

- Verify the following was logged in `configuration-store` tilt resource:
```
INFO  com.boozallen.aissemble.configuration.mutating.webhook.ConfigMutatingWebhook.validate():43 - Webhook was run!
INFO  com.boozallen.aissemble.configuration.mutating.webhook.ConfigMutatingWebhook.validate():44 - Request: GroupVersionKind(group=, kind=Pod, version=v1, additionalProperties={})
```
_Note: there will be some other logs for `kind=Event`_

- `tilt down`
- Run the following to verify the output is `No resources found`:
```
kubectl get jobs,pods,secrets,mutatingwebhookconfigurations -n config-store-ns
```

## References/Additional Context
https://kubernetes.io/blog/2024/04/26/multi-webhook-and-modular-authorization-made-much-easier/

**Comment by carter-cundiff** [comment]
DOD with @ewilkins-csi and @nartieri

**Comment by ewilkins-csi** [comment]
✅  _**OTS** passed_

**Comment by carter-cundiff** [comment]
Testing passed with @aaron-gary
