### ISSUE TITLE
Feature: Baton migration scripts for renamed aiops references in extensions-security 

### ISSUE THREAD

**Issue by habibimoiz** [boozallen/aissemble#216]
## Description
In GH Issue #194, all of the aiops references have been refactored to aissemble. As part of that effort, the security package imports have been migrated. This will focus on migrating those pieces that consist in customized downstream projects. 

## DOD

- [x] Write Baton migration scripts for any files that need to be renamed. 
- [x] Write Baton migrations for any Objects that need to be renamed. 

## Test Strategy/Script

**Test 1:** Ensuring the migrations BDD scenarios pass in aiSSEMBLE.

1. Run the following: mvn clean install -pl :foundation-upgrade 
2. Verify that this module builds and all of the tests pass successfully. 
 
**Test 2:** Test baton migration in downstream project

1. Download the zipped file in the attachments labeled: authzforce1.zip
    - This is a downstream project that uses PDP and authzforce modules. 
2. Unzip the project, and open the following file:
    - authzforce1/authzforce1-pipelines/spark-pipeline/src/main/java/org/boozallen/aissemble/Ingest.java
3. Verify lines 19-24 are referencing imports from the old packaging naming convention ("aiops").
4. Lines 46-55 are referencing objects from the PDP and authzforce modules. Verify that these objects are still referencing the old naming convention ("aiops").
5. Navigate to the root pom.xml and change the aiSSEMBLE version from 1.7.0 to 1.8.0-SNAPSHOT (on line 15).
6. Run the following: mvn clean install.
7. Verify you receive a successful build. 
8. Navigate to the following file: authzforce1/authzforce1-pipelines/spark-pipeline/src/main/java/org/boozallen/aissemble/Ingest.java
9. Verify lines 19-24 are now referencing imports from the changed PDP and authzforce modules (aiops --> aissemble).
10. Verify lines 46-55 are now referencing objects from the PDP and authzforce modules (aiops --> aissemble).

## References/Additional Context

_n/a_

**Comment by habibimoiz** [comment]
[authzforce1.zip](https://github.com/user-attachments/files/16381688/authzforce1.zip)

**Comment by chang-annie** [comment]
closing issue - all test steps are passing

- [x] foundation-upgrade builds successfully 
- [x] upgrade successful 
- [x] baton migrates successfully migrate aiops -> aissemble for imports and variable names
