### ISSUE TITLE
Update default memory for Spark

### ISSUE THREAD

**Issue by tianliang0038** [boozallen/aissemble#23]
As a data engineer, I want the default memory for Spark applications to be increased so it works out of the box for more than just toy examples

**Comment by tianliang0038** [comment]
**DOD**
* Investigate and address memory limit issues in spark pipelines/pods, known for frequent failures due to memory constraints.
** we should assess how additional memory setting will impact the minimum recommended settings so it's not overburdening the machine, and change the memory based on that 
* Update templates for the pipelines
 ** Pyspark data delivery pipeline
 ** Spark java data delivery pipeline
 * Validate the fix by adjusting memory settings and confirming resolution
 * Update baton migration table within the release notes (abandoned)
 * Create baton migration for updating spark application to the new values. (abandoned)
{code}
Feature: Migrate a spark application to use the new memory value
  Scenario: Migrate a spark application with new memory value in the base values
    Given a project that has a spark application
    And the base value contains the old memory value
    When the 1.7.0 spark application memory migration executes
    Then the memory is updated to new value

  Scenario: Skip spark application memory migration with non-default values in the base values
    Given a project that has a spark application
    And the base values.yaml does not have default memory values
    When the 1.7.0 spark application memory migration executes
    Then the spark application memory migration is skipped
{code}

*Test For 1.7.0-SNAPSHOT spark pipelines* (spark and pyspark)
 ** Pull the latest baseline project
 ** Run
{code:java}
mvn clean install -f foundation/foundation-mda
{code}
# Build a pipeline with the attached PysparkPipeline.json and SparkPipeline.json file to <YOUR-PIPELINE-NAME>-pipeline-models/src/main/resources/pipelines
{code}
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.7.0-SNAPSHOT \
                          -DartifactId=aiops-3232 \
                          -DgroupId=org.test \
                          -DprojectName='Test AIOPS-3232' \
                          -DprojectGitUrl=test.org/aiops-3232\
&& cd aiops-3232 {code}
# Run the following:
{code}
mvn clean install{code}
# Follow the manual action and then run 
{code} mvn clean generate-sources{code}
# Verify that driver.memory is 2048m, and executor.memory in pyspark-pipeline-base-values.yaml is 4096m in pyspark-pipeline-base-values.yaml and spark-pipeline-base-values.yaml, and 2048m in pyspark-pipeline-dev-values.yaml and spark-pipeline-dev-values.yaml

**Comment by tianliang0038** [comment]
[PysparkPipeline.json](https://github.com/boozallen/aissemble/files/15193696/PysparkPipeline.json)
[SparkPipeline.json](https://github.com/boozallen/aissemble/files/15193697/SparkPipeline.json)

**Comment by csun-cpointe** [comment]
Final test passes with verifying the generated yaml files with expected memories
