### ISSUE TITLE
Feature: Switch to official Spark Operator release

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#251]
## Description
There was a bug in Spark Operator that we had to manually fix with a custom fork/compilation of Spark Operator.  That change bug fix was finally [merged in](https://github.com/kubeflow/spark-operator/pull/1979) on May 17.  We should upgrade to the version with our fix and remove the custom image if possible.  It might also make sense to jump to the latest version of the Spark Operator chart while we're at it.

## DOD
- [x] aiSSEMBLE no longer clones and compiles the [Tech Brewery fork](https://github.com/TechnologyBrewery/spark-on-k8s-operator) of Spark Operator
- [x] Dynamic allocation of executors still works as expected

## Test Script
1.  Generate a new project
```
mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                       '-DarchetypeArtifactId=foundation-archetype' \
                       '-DarchetypeVersion=1.8.0-SNAPSHOT' \
                       '-DartifactId=test-251' \
                       '-DgroupId=org.test' \
                       '-Dpackage=org.test' \
                       '-DprojectGitUrl=test.org/test-251.git' \
                       '-DprojectName=Test Project' -B && cd test-251
```
2. Add the attached [**PysparkPipeline.json**](https://github.com/user-attachments/files/16457532/PysparkPipeline.json) to _test-251-pipeline-models/src/main/resources/pipelines_
3. Build the project and follow all manual actions, repeating until no more actions are printed
```
mvn clean install
```
4. Do a full build of the project and complete any new manual actions
```
mvn clean install -Dmaven.build.cache.skipCache
```
5.  **OTS Only** Switch the spark-operator chart to use the locally modified chart
    1. Add `upgrade-v2-chart-files-aissemble-version-migration` to the disabled migrations in the root _pom.xml_
    2. Update _test-251-deploy/src/main/resources/apps/spark-operator/Chart.yaml_ to point to the local chart version 1.0.0
    3. Update _test-251-deploy/src/main/resources/apps/spark-operator/values.yaml_ to set `aissemble-spark-operator-chart.spark-operator.image.pullPolicy` to **Never**
    4. Rebuild the deploy module: `mvn clean install -pl :test-251-deploy`
6. Deploy the project
```
tilt up
```
7. Execute the _pyspark-pipeline_ resource in Tilt
8. Verify the pipeline completes successfully with no exceptions from the `CoarseGrainedExecutor` class

**Comment by carter-cundiff** [comment]
OTS passed

**Comment by csun-cpointe** [comment]
test passed!!
**Pipeline completes successfully with no exceptions from the CoarseGrainedExecutor class**
![Screenshot 2024-08-01 at 10 16 35 AM](https://github.com/user-attachments/assets/34feadb1-be95-47f1-97f9-2e39cd9cb3bc)
![Screenshot 2024-08-01 at 10 16 43 AM](https://github.com/user-attachments/assets/5dc43c30-7477-4737-90e5-b2997ccfbac2)
