### ISSUE TITLE
Feature: As an aiSSEMBLE user, I want helm charts for necessary infrastructure so that I can easily deploy my project

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#252]
## Description
Currently, every aissemble project must deploy argocd in order to deploy aissemble.  These deployments are not actively maintained on most (if not all) projects.  We should formalize their support with a helm chart that includes support for ArgoCD, nginx ingress, and GPU Operator (optional). Additionally, This will greatly help conformance with IA guidelines.

## DOD
- [x] Create helm charts for the following resources:
  - [x] ArgoCD - utilize [Argo helm chart](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd)
  - [x] Nginx ingress - utilize [Kubernetes helm chart](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx)
    - [x] Configure ArgoCD to work with the ingress
  - [ ]  GPU Operator (Stretch Goal) - utlilize [NVIDIA helm chart](https://github.com/NVIDIA/gpu-operator/blob/main/deployments/gpu-operator/Chart.yaml)
- [x] Charts should include reasonable defaults and guidance for deploying them
- [x] Create a parent helm chart with options to enable/disable the the above sub-charts
  - [x] Include jenkins in this chart

## Test Strategy/Script
- **Before Testing**:
  - Update your rancher desktop settings to disable Traefik (Preferences -> Kubernetes -> Enable Traefik). Your rancher desktop will need to restart after the change.
  - Install the Argo CD CLI if you have not already: https://argo-cd.readthedocs.io/en/stable/cli_installation/
- **OTS Only**:
  - Run the following to build the chart locally:
    ```
    mvn clean install -pl :aissemble-infrastructure-chart -Dmaven.build.cache.skipCache=true
    ```
  - Use the local `*.tgz` file for all `helm` commands, for example:
    ```
    helm install aissemble-infrastructure YOUR/PATH/aissemble-infrastructure-chart-1.9.0-SNAPSHOT.tgz
    ```
- Install the helm chart with the following command:
```
helm install aissemble-infrastructure oci://ghcr.io/boozallen/aissemble-infrastructure-chart --version 1.9.0-SNAPSHOT
```
- Wait for all the pods to be completed/running using the following command:
```
kubectl get pods --all-namespaces | grep -v 'kube-system'
```
- In a separate terminal, run the following command to allow us to reach our ingress controller:
```
kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
```
- Run the following command to get the Argo CD generated password:
```
argocd admin initial-password -n argocd
```
- Verify you can login to the `admin` account using the generated password at the URL: `http://argocd.localdev.me:8080/`
- Verify you can login to the Argo CD CLI using the generated password with the following command:
```
argocd login grpc.argocd.localdev.me:8080
```
- Run the following command to get the Jenkins generated password:
```
kubectl exec --namespace jenkins -it svc/jenkins -c jenkins -- /bin/cat /run/secrets/additional/chart-admin-password && echo
```
- Verify you can login to the `admin` account using the generated password at the URL: `http://jenkins.localdev.me:8080/`
- Uninstall the helm chart with the following command and delete the created namespaces:
```
helm uninstall aissemble-infrastructure
kubectl delete namespace argocd jenkins ingress-nginx
```
- Install only the Jenkins sub chart:
  - Run the following command:
  ```
  helm install aissemble-infrastructure oci://ghcr.io/boozallen/aissemble-infrastructure-chart --version 1.9.0-SNAPSHOT --set argo-cd.enabled=false --set ingress-nginx.enabled=false
  ```
  - Verify only pods for Jenkins are deployed with the following command:
  ```
  kubectl get pods --all-namespaces | grep -v 'kube-system'
  ```
  - Uninstall the helm chart with the following command:
  ```
  helm uninstall aissemble-infrastructure
  ```
- Install only the Ingress Nginx sub chart:
  - Run the following command:
  ```
  helm install aissemble-infrastructure oci://ghcr.io/boozallen/aissemble-infrastructure-chart --version 1.9.0-SNAPSHOT --set argo-cd.enabled=false --set jenkins.enabled=false
  ```
  - Verify only pods for Ingress Nginx are deployed with the following command:
  ```
  kubectl get pods --all-namespaces | grep -v 'kube-system'
  ```
  - Uninstall the helm chart with the following command:
  ```
  helm uninstall aissemble-infrastructure
  ```
- Install only the Argo CD sub chart:
  - Run the following command:
  ```
  helm install aissemble-infrastructure oci://ghcr.io/boozallen/aissemble-infrastructure-chart --version 1.9.0-SNAPSHOT --set jenkins.enabled=false --set ingress-nginx.enabled=false
  ```
  - Verify only pods for Argo CD are deployed with the following command:
  ```
  kubectl get pods --all-namespaces | grep -v 'kube-system'
  ```
  - Uninstall the helm chart with the following command:
  ```
  helm uninstall aissemble-infrastructure
  ```

- Recommend re-enabling traefic in rancher desktop after completing testing

**Comment by carter-cundiff** [comment]
DOD with @csun-cpointe

**Comment by carter-cundiff** [comment]
Completed OTS with @csun-cpointe

**Comment by ewilkins-csi** [comment]
### **Final Test**
1. ✅ Validate ArgoCD browser login
![Screenshot 2024-08-09 at 4 31 30 PM](https://github.com/user-attachments/assets/0f6774f2-7ffb-4d37-835f-e8ef0cb4978b)
2. ✅ Validate ArgoCD CLI login
![Screenshot 2024-08-09 at 4 32 24 PM](https://github.com/user-attachments/assets/d47c9bfb-1ada-4333-a1c2-bc7490faafd4)
3. ✅ Validate Jenkins browser login
![Screenshot 2024-08-09 at 4 33 21 PM](https://github.com/user-attachments/assets/af85a89d-5840-4374-b565-a96294bb18a2)
4. ✅ Validate Jenkins-only deployment
![Screenshot 2024-08-09 at 4 38 33 PM](https://github.com/user-attachments/assets/0325b701-daf8-403f-95ea-7cdac0558476)
5. ✅ Validate Nginx-only deployment
![Screenshot 2024-08-09 at 4 39 36 PM](https://github.com/user-attachments/assets/e023eae7-53cd-4724-aeef-80bacb6059f1)
6. ✅ Validate ArgoCD-only deployment
![Screenshot 2024-08-09 at 4 41 13 PM](https://github.com/user-attachments/assets/6ebd81bb-e3e5-472a-bd1c-d51dfd477bb1)
