### ISSUE TITLE
Feature: Ensure Dockerfile filtering does not interfere with ARG/ENV values.

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#255]
## Description
Fabric8's docker-maven-plugin provides [filtering](https://dmp.fabric8.io/#build-filtering) functionality that is enabled by default. We [addressed this](https://github.com/boozallen/aissemble/pull/201) for `ENV` substitutions through out the code base, but didn't cover `ARG` substitutions.  Unfortunately, we can't take the same approach of dropping the braces (`{}`) because some of the substitutions are embeded in strings (e.g. `python-${PYTHON_VERSION}-dist-utils`).  To avoid this entirely, we should take the recommendation from Fabric8 to set the filtering delimiter to `@`.

## DOD
- [x] Quarkus-based images are updated to use `@` delimiter
- [x] All docker images build successfully with the updated delimiter

## Test Strategy/Script
1. Build the PDP image with a clashing property: 
```sh
mvn clean install -pl :aissemble-policy-decision-point -am -DJAVA_APP_DIR=/fake/path
```
2. Run the policy decision point image: 
```sh
docker run --rm -p8080:8080 ghcr.io/boozallen/aissemble-policy-decision-point:1.8.0-SNAPSHOT
```
3. Verify the service is running: `curl localhost:8080/api/healthcheck`
4. Create a JWT for the user _aissemble_:
```sh
curl -X POST -H "Content-Type: application/json" localhost:8080/api/authenticate -d '{
  "username": "aissemble",
  "password": ""
}'
```
5. Submit a decision request with the token generated in the previous step and verify `PERMIT` is returned
```sh
curl -X POST -H "Content-Type: application/json" localhost:8080/api/pdp -d '{
  "jwt": "TOKEN",
  "resource": "",
  "action": "data-access"
}'
```

**Comment by csun-cpointe** [comment]
Tests passed!!
