### ISSUE TITLE
Feature: Upgrade Quarkus to 3.6+

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#263]
## Description
In order to prepare for adding JDK 17 support to the baseline, we should update Quarkus to the latest possible version that still supports Java 11 (Quarkus 3.7 [dropped support for 11](https://quarkus.io/blog/java-17/)).

## DOD
- [x] Quarkus is updated to 3.6

## Test Strategy/Script
1. Check out the feature branch `feature-java17`
2. Run the integration tests
```sh
mvn clean install -Pintegration-test
```
3. Run the archetype test
```sh
mvn clean install -pl :foundation-archetype -Parchetype-test
```

**Comment by ewilkins-csi** [comment]
**DoD** with @carter-cundiff @csun-cpointe and @nartieri

**Comment by ewilkins-csi** [comment]
After this upgrade, there were some issues with Policy Decision Point, Pipeline Invocation, and the Configuration Store webhook.  It seems that the bulk or all of these issues will be resolved by upgrading to JDK 17.  So instead of implementing hacks to workaround the issue, we will keep this work on a feature branch until the full upgrade is done.  That will keep us from doing a bunch of work that is redundant/removed by the end of this ticket series.  In light of that, testing will focus on the operational aspects of the services and the build ITs/archetype test.

**Comment by ewilkins-csi** [comment]
**OTS** results:
`mvn clean install -Pintegration-test` was successful:
<img width="839" alt="Screenshot 2024-08-26 at 10 22 02 AM" src="https://github.com/user-attachments/assets/c95ebd6a-180c-45cb-b66b-3ff9e66673bd">


`mvn clean install -pl :foundation-archetype -Parchetype-test` was successful:
<img width="839" alt="Screenshot 2024-08-26 at 10 05 38 AM" src="https://github.com/user-attachments/assets/d199eabe-d300-4dcd-b4a2-cdd910d85ebc">

**Comment by csun-cpointe** [comment]
OTS completed ✅

**Comment by csun-cpointe** [comment]
final test passed!!
