### ISSUE TITLE
Feature: Add the ability to inject config store values via local properties files.

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#266]
## Description
Following up ticket to [#209](https://github.com/boozallen/aissemble/issues/209), now that we have webhook service up and running, we want to be able to inject configs into a properties files that are mounted on the container.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Update the mutating webhook to filter resources:
   - [x] On resource creation only
   - [x] With appropriate metadata label
  ~- [ ] Of Kind ConfigMap~
- [x] Inject the required config store property values into the newly created ConfigMap
   - [x] Define a substitution key that the config store will override with the appropriate value
   - [x] Create a patch for injecting the value to the configMap yaml
- [x] Update the Config Store documentation with detail how to inject values to the ConfigMap
## BDD Scenario:
Scenario: The configuration service can inject values to newly created configMap

## Test Strategy/Script
- Create a downstream project from the archetype using the following command:
  ```
  mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.9.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-266 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-266 \
  && cd test-266
  ```
- Add a simple pipeline to test-266-pipeline-models
[SparkPipeline.json](https://github.com/user-attachments/files/16603518/SparkPipeline.json)

- Add to the fermenter-mda plugin executions in test-266-deploy/pom.xml
```
<execution>
    <id>configuration-store</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>generate-sources</goal>
    </goals>
    <configuration>
        <basePackage>com.boozallen.aissemble.test</basePackage>
        <profile>configuration-store-deploy-v2</profile>
        <!-- The property variables below are passed to the Generation Context and utilized
             to customize the deployment artifacts. -->
        <propertyVariables>
            <appName>configuration-store</appName>
        </propertyVariables>
    </configuration>
</execution>
```
- Build the project with `mvn clean install` and complete the manual action
- Download and unzip the attached 
[266-helper.zip](https://github.com/user-attachments/files/16605025/266-helper.zip)

- Mac users
  - In the root directory, find the `Tiltfile-config` file and copy the src directory to the root of the project and update the `configuration_files_path` to the following:
```
configuration_files_path = '266-helper/src/main/resources/configurations'
```
- WSL Users:
  - Copy the src directory to windows file system and update the `project_path` and `configuration_files_path` in the `Tiltfile` to the following:
  
```
  project_path='/mnt/c/Users/YOUR_USER/PATH/TO/266-helper`
configuration_files_path = 'src/main/resources/configurations'
 
```
- In the `test-266-deploy/src/main/resources/app/hive-metastore-service/templates/configmap.yaml` file:
   - add below content to the `metadata`:

```
    labels:
      aissemble-configuration-store: enabled
```

- In the `test-266/test-266-deploy/src/main/resources/apps/hive-metastore-service/values.yaml` file
    - replace **fs.s3a.access.key** value `123` with `$getConfigValue(groupName=aws-credentials;propertyName=AWS_ACCESS_KEY_ID)`
    - replace **fs.s3a.secret.key** value `456` with `$getConfigValue(groupName=aws-credentials;propertyName=AWS_SECRET_ACCESS_KEY)`

- To start up config store service before all other services, create a new `Tiflefile-config` file and move `configuration-store` resource from `Tiltfile` to the `Tifefile-config`. e.g.:
```
# For WSL users, the configuration files need to be in an accessible path. Update the project path to the root file system. Example: '/mnt/c' or '/mnt/wsl/rancher-desktop'
project_path = os.path.abspath('.')

# Update configuration_files_path to match the path of the config files to be loaded into the configuration store. Example 'my-project-deploy/src/main/resources/config'
configuration_files_path = 'src/main/resources/configurations'

load('ext://helm_resource', 'helm_resource')
helm_resource(
    name='configuration-store',
    release_name='configuration-store',
    chart='test-266-deploy/src/main/resources/apps/configuration-store',
    namespace='config-store-ns',
    flags=['--values=test-266-deploy/src/main/resources/apps/configuration-store/values.yaml',
           '--values=test-266-deploy/src/main/resources/apps/configuration-store/values-dev.yaml',
           '--set=aissemble-configuration-store-chart.configurationVolume.volumePathOnNode=' + project_path + '/' + configuration_files_path,
           '--create-namespace']
)
```

- Run `tilt up -f Tiltfile-config --port 10351; tilt down -f Tiltfile-config` and wait until the `configuration-store` resource is ready 
- In a separated terminal, run `tilt up; tilt down` to tilt up all other services

- Check the metastore-site.xml in `hive-metastore-service` has been updated with the correct config store value
```
kubectl exec -it `<hive-metastore-service-xxxxx>` -- sh
cat /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
```
- Verify the `fs.s3a.access.key` and `fs.s3a.secret.key` values in the `hive-metastore-service` metastore-site.xml file have been updated
```
<property>
    <name>fs.s3a.access.key</name>
    <value>env-access-key-id</value>
  </property>
  <property>
    <name>fs.s3a.secret.key</name>            
<value>ENC(5vpYAWu/7sWCedm54CI2LZQ5O1TRCSwNdm0YMcAXj2b4sE5rk86iks7ITxzPfksnbDjy7AvI8TreVqykXGy6zA==)</value>
  </property>
```

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by csun-cpointe** [comment]
DoD completed with @carter-cundiff and @nartieri

**Comment by csun-cpointe** [comment]
OTS completed with @ewilkins-csi

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/1b961a48-786f-4150-8051-cc492968c30e)
