### ISSUE TITLE
TASK: Update helm chart README's to correctly reference OCI charts in the install command

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#281]
## Description
Currently in our helm chart README's, each module includes a basic usage helm command along the lines of:
```
helm install <CHART-NAME> ghcr.io/boozallen/<CHART=NAME> --version <AISSEMBLE-VERSION>
```
This syntax is incorrect and will fail to install the chart. The proper syntax should include `oci://` on the beginning of the chart url:
```
helm install <CHART-NAME> oci://ghcr.io/boozallen/<CHART=NAME> --version <AISSEMBLE-VERSION>
```
## DOD
- [x] Update helm chart README's to use the correct syntax

## Test Strategy/Script
- Go to the current [chart README](https://github.com/boozallen/aissemble/tree/dev/extensions/extensions-helm/aissemble-metadata-chart#readme) for metadata
- Copy the helm install command and run it with the current aiSSEMBLE version `1.9.0-SNAPSHOT`
- Verify the chart installs successfully
- Uninstall the chart: `helm uninstall metadata`

**Comment by carter-cundiff** [comment]
DOD/OTS completed with @csun-cpointe

**Comment by csun-cpointe** [comment]
test passed!!
