### ISSUE TITLE
Feature: Provide migration path for projects transitioning from v1 Spark Operator helm chart to v2

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#284]
## Description
The spark operator v2 helm chart was previously created and set as the default in new projects, however, migration instructions were never created for updating existing projects. We need to create guidance for users to update their existing spark operator chart to the new v2 one.

## DOD
- [x] Deprecate the v1 profile: `aissemble-spark-operator-deploy`
  - [x] Message should include that v1 is only compatible with `1.7.0` image
  - [x] Update migration to skip updating spark operator v1 image version
  - [x] Fix link in deprecation warning messages 
- [x] Update chart README with instructions for migrating to the v2 chart:
  - [x] Include new property locations and any specialty instructions
- [x] Update documentation noting the migration is available in the following locations:
  - [x] Create `1.8.1` patch release notes
    - [x] Link to general migration instructions in antora docs
  - [x] Update list of available V2 profiles on [containers.adoc antora page](https://boozallen.github.io/aissemble/aissemble/current/containers.html)

## Implementation Notes
- [x] Create `1.8.1` patch release branch off of `1.8.0` tag
  - [x] Run `mvn versions:set` command to update to `1.8.1-SNAPSHOT`
  - [x] Manually update two files in `/tests`
  - [x] Update antora docs
- [x] Create feature branch off patch release branch
- [x] Merge into `1.8.1` patch release branch
- [x] Cherry pick back to `dev`

### Spark Operator Upgrade
- **OTS Only:**
  - Build the entire aiSSEMBLE project to create all the `1.8.1-SNAPSHOT` artifacts locally
- Create a archetype project on version `1.7.0`:
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.7.0 \
  -DgroupId=com.test \
  -DartifactId=test-284 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-284 \
  && cd test-284
```
- Add the [SparkPipeline.json](https://github.com/user-attachments/files/16752612/SparkPipeline.json) file to the `test-284-pipeline-models/src/main/resources/pipelines` directory
- Run `mvn clean install` until all the manual actions are complete 
  - **NOTE:** As part of the first set of manual actions for the `test-284-deploy/pom.xml`, update the spark operator execution block to use the `aissemble-spark-operator-deploy` profile (remove the `-v2` on the end)
- Once the manual actions are complete, run `mvn clean install -Dmaven.build.cache.skipCache=true` once to get any remaining manual actions
- Update `<parent>` in the root `pom.xml` to use build parent version `1.8.1-SNAPSHOT`
- Run `mvn org.technologybrewery.baton:baton-maven-plugin:baton-migrate` to apply the migrations
  - Verify spark-operator is using `1.7.0` image tag in `test-284-deploy/src/main/resources/apps/spark-operator/values.yaml`
- **OTS Only:**
  - Replace `<argument>${version.aissemble}</argument>` with `<argument>1.8.0</argument>` in `test-284-pipelines/spark-pipeline/pom.xml`
  - Update spark application helm template command to use `1.8.0` in the `Tiltfile`
  - Disable the `upgrade-v2-chart-files-aissemble-version-migration` migration
  - Replace `version: "1.8.1-SNAPSHOT"` with `version: "1.8.0"` in the v2 helm `chart.yaml`'s
  - Update `hive-metastore-db` pull policy to `IfNotPresent` in `test-284-deploy/src/main/resources/apps/hive-metastore-db/values.yaml`
- Replace `<groupId>io.fabric8</groupId>` with `<groupId>org.technologybrewery.fabric8</groupId>` in `test-284-docker/pom.xml` and `test-284-tests/test-284-tests-docker/pom.xml`
- Disable the ivy cache in `test-284-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-base-values.yaml` by adding the following values:
  ```
  sparkApp:
    spec:
      volumes: []
      driver:
        volumeMounts: []
      executor:
        volumeMounts: []
  ```
- Build the project once with `mvn clean install`
  - Verify you get the deprecation warning for the `aissemble-spark-operator-deploy` profile
- `tilt up`
- Once all the resources are ready, run the `spark-pipeline` resource
  - Verify you see the following log: `ERROR ExampleSyncStep: Implement executeStepImpl(..) or remove this pipeline step!`
- Verify the pipeline runs successfully
- `tilt down`
- Follow the [migration instructions](https://boozallen.github.io/aissemble/aissemble/current-dev/containers.html#_kubernetes_artifacts_upgrade) and [README](https://github.com/boozallen/aissemble/tree/dev/extensions/extensions-helm/aissemble-spark-operator-chart#readme) for upgrading to spark-operator V2
  - **NOTE:** All V1 properties contain the same defaults in the V2 chart, so you are safe to delete the existing chart directory and use the newly generated one 
- **OTS Only:**
  - Replace `version: 1.8.1-SNAPSHOT` with `version: 1.8.0` in `test-284-deploy/src/main/resources/apps/spark-operator/Chart.yaml`
- After completing the migration, run `mvn clean install -Dmaven.build.cache.skipCache=true` once
- `tilt up`
- Once all the resources are ready, run the `spark-pipeline` resource
  - Verify you see the following log: `ERROR ExampleSyncStep: Implement executeStepImpl(..) or remove this pipeline step!`
- Verify the pipeline runs successfully
- `tilt down`

### Deprecation in New Project
- **OTS Only:**
  - Switch over to the branch [284-spark-operator-v2-cherry-pick](https://github.com/boozallen/aissemble/tree/284-spark-operator-v2-cherry-pick) and run the following:
  ```
  mvn clean install -pl :foundation-mda -Dmaven.build.cache.skipCache=true
  ```
- Delete the old project and create a new archetype project on version `1.9.0-SNAPSHOT`:
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.9.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-284 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-284 \
  && cd test-284
```

- Add the following execution blocks to `test-284-deploy/pom.xml`:
```
                    <execution>
                        <id>spark-operator</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <basePackage>com.test</basePackage>
                            <profile>aissemble-spark-operator-deploy</profile>
                            <!-- The property variables below are passed to the Generation Context and utilized
                                 to customize the deployment artifacts. -->
                            <propertyVariables>
                                <appName>spark-operator</appName>
                            </propertyVariables>
                        </configuration>
                    </execution>
                    <execution>
                        <id>metadata</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <basePackage>com.test</basePackage>
                            <profile>metadata-deploy</profile>
                            <!-- The property variables below are passed to the Generation Context and utilized
                                 to customize the deployment artifacts. -->
                            <propertyVariables>
                                <appName>metadata</appName>
                            </propertyVariables>
                        </configuration>
                    </execution>
```
- Build the project once with `mvn clean install`
  - Verify you get the deprecation warning for the `aissemble-spark-operator-deploy` and  `metadata-deploy` profiles

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by ewilkins-csi** [comment]
**OTS** test steps pass ✅
