### ISSUE TITLE
BUG: All generated docker images fail to build

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#286]
## Description
Any docker images generated into a downstream project will fail to build after running `mvn clean install`.  It appears that the baseline and version build arguments are not correctly configured in the Dockerfile. (`ARG` declarations are required but missing.)

## Steps to Reproduce
Clear, specific, and detailed steps taken to enable reproduction of the bug for investigation.
1. Generate a project from the latest snapshot archetype:
```
mvn archetype:generate \                                                                   
    -DarchetypeGroupId=com.boozallen.aissemble \
    -DarchetypeArtifactId=foundation-archetype \
    -DarchetypeVersion=1.9.0-SNAPSHOT \
    -DgroupId=com.example \
    -DartifactId=issue-286 \
    -DprojectGitUrl=url \
    -DprojectName=issue-286 \
&& cd issue-286
```
3. Add any pipeline (this affects all generated docker modules, and all pipelines have at least one docker module they pull in)
4. Generate out the project following manual actions
5. Rerun the project created above build without caching:
```
mvn clean install -Dmaven.build.cache.skipCache=true
```
7. Deploy the project via Tilt

## Expected Behavior
Deployments should automatically and successfully build any project-specific docker images (e.g. Policy Decision Point, Spark Worker, etc.).

## Actual Behavior
The Docker image fails to build in Tilt with an `invalid reference format` message.

## Additional Context
- aiSSEMBLE Version 1.9.0-SNAPSHOT
- Error output:
![Screenshot 2024-08-21 at 4 28 55 PM](https://github.com/user-attachments/assets/b497cd2f-00be-4ed5-a113-444e316f2a1c)

## Test Steps
1. Validate that the new negative test case for the migration passes by running the following in the aissemble repo:
   ```
   mvn clean install -pl :foundation-upgrade -Dmaven.build.cache.skipCache=true
   ```
3. Follow the steps to recreate above
4. Tilt up completes with out `invalid reference format` message

**Comment by d-ryan-ashcraft** [comment]
Recreated the issue:
```
STEP 1/3 — Building Dockerfile: [issue-286-policy-decision-point-docker]
Building Dockerfile for platform linux/arm64:
  # Script for creating policy decision point service image
  #
  # GENERATED DOCKERFILE - please ***DO*** modify.
  #
  # Generated from: templates/general-docker/policy.decision.point.docker.file.vm
  
  
  
  
  FROM ${DOCKER_BASELINE_REPO_ID}boozallen/aissemble-policy-decision-point:${VERSION_AISSEMBLE}
  
  USER 1001
  
  COPY ./target/aissemble-security.properties /deployments/krausening/


     Building image

Build Failed: ImageBuild: failed to parse stage name "boozallen/aissemble-policy-decision-point:": invalid reference format
```

**Comment by d-ryan-ashcraft** [comment]
This issues is related to a migration, `ml-flow-dockerfile-migration`, that is matching any `Dockerfile` that contains the following (which is basically ALL of them):
- `ARG DOCKER_BASELINE_REPO_ID`
- `ARG VERSION_AISSEMBLE`

To improve regression testing and make this faster to validate, we replicated it with a new unit test:
```
[ERROR] Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.764 s <<< FAILURE! -- in com.boozallen.aissemble.upgrade.migration.TestSpecifications
[ERROR] Migration MLFlow Dockerfile.A Dockerfile not using MLFlow is not impacted by this migration -- Time elapsed: 0.008 s <<< FAILURE!
java.lang.AssertionError: The migration is processing Dockerfile it should NOT be migrating!
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at com.boozallen.aissemble.upgrade.migration.v1_9_0.MLFlowDockerfileMigrationSteps.the_image_is_unchanged(MLFlowDockerfileMigrationSteps.java:66)
        at ✽.the image is unchanged(file:///Users/ryan/dev/aissemble-oss/aissemble/foundation/foundation-upgrade/src/test/resources/specifications/v1_9_0/ml-flow-dockerfile-migration.feature:11)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   The migration is processing Dockerfile it should NOT be migrating!
```

**Comment by meliz19** [comment]
The `invalid reference format` issue was resolved in this ticket. A [separate issue](https://github.com/boozallen/aissemble/issues/292) related to Python versioning was discovered in the process of testing this ticket.
