### ISSUE TITLE
Setup GitHub Action for releasing aissemble

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#3]
As the aissemble codebase is migrated into the github.com/aissemble repository, we should create a release process that lives with it and is available at the same level of visibility (for read access, only maintainers should be allowed to cut a release).

This process should migrate the internal process used in the past to GitHub Actions.

**Definition of Done**
- Create input fields for the following in the release GitHub Action
  - releaseVersion
  - developmentVersion
  - releaseBranch - Optional: Used to manually specify the release branch to use, should use a default if not specified
  - existingVersion - Optional: Used to specify current version, should use a default if not specified
- Update Antora docs to use the new version in the release GitHub Action
- Cut a release candidate of the aiSSEMBLE project using Maven in the release GitHub Action
- Add security to allow only maintainers the ability to cut a release of aiSSEMBLE  
- Verify that artifacts are pushed to the appropriate repositories

**Test Steps (OTS)**
- Go to the GitHub Actions https://github.com/boozallen/aissemble/actions 
- Verify a successful action for Release aissemble number 168
- Go to the aissemble-release-1.9 branch commit history https://github.com/boozallen/aissemble/commits/aissemble-release-1.9/
- Click on the **Updating scripts and templates to 1.9.0** commit
- In the antora.yaml file, verify the display_version was changed to 1.9.0 and the pre release was changed to false
- In the custom facet json files, verify references to 1.9.0-SNAPSHOT was changed to 1.9.0
- Go back to the commit history. Click on the **Updating scripts and templates to 1.10.0-SNAPSHOT** commit
- In the antora.yaml file, verify the version was changed to 1.10.0, the display_version was changed to 1.10.0-SNAPSHOT and the pre release was changed to true
- In the custom facet json files, verify references to 1.9.0 was changed to 1.10.0-SNAPSHOT
- Go to the GitHub Actions https://github.com/boozallen/aissemble/actions 
- Verify a successful action for Release aissemble number 127
- Verify the aissemble-root 1.9.0-rc1 artifact was uploaded https://central.sonatype.com/artifact/com.boozallen.aissemble/aissemble-root/1.9.0-rc1
- Verify the foundation-core-java 1.9.0-rc1 artifact was uploaded https://central.sonatype.com/artifact/com.boozallen.aissemble/foundation-core-java
- Verify the foundation-core-python 1.9.0-rc1 artifact was uploaded https://pypi.org/project/aissemble-foundation-core-python/#history
- Verify the Quarkus Docker image 1.9.0-rc1 artifact was uploaded (Note: This image was pruned) https://github.com/boozallen/aissemble/pkgs/container/aissemble-quarkus
- Verify the aissemble-airflow-chart 1.9.0-rc1 artifact was uploaded https://github.com/boozallen/aissemble/pkgs/container/aissemble-airflow-chart

**Test Steps (Final Test)**
- Go to the GitHub Actions https://github.com/boozallen/aissemble/actions 
- Verify a successful action for **Release aissemble** number 190
- Go to the aissemble-release-1.9 branch commit history https://github.com/boozallen/aissemble/commits/aissemble-release-1.9/
- Click on the **Updating Antora documentation for version 1.9.0-rc2** commit
- In the **antora.yaml** file, verify the display_version was changed to 1.9.0-rc2
- In the custom facet json files, verify references to 1.9.0-SNAPSHOT was changed to 1.9.0-rc2
- Go back to the commit history. Click on the **Updating Antora documentation for version 1.10.0-SNAPSHOT** commit
- In the **antora.yaml** file, verify the version was changed to 1.10.0 and the display_version was changed to 1.10.0-SNAPSHOT
- In the custom facet json files, verify references to 1.9.0-rc2 was changed to 1.10.0-SNAPSHOT
- Verify there is an aissemble-root-1.9.0-rc2 tag https://github.com/boozallen/aissemble/releases/tag/aissemble-root-1.9.0-rc2
- Verify the aissemble-root 1.9.0-rc2 artifact was uploaded https://central.sonatype.com/artifact/com.boozallen.aissemble/aissemble-root
- Verify the foundation-core-java 1.9.0-rc2 artifact was uploaded https://central.sonatype.com/artifact/com.boozallen.aissemble/foundation-core-java
- Verify the foundation-core-python 1.9.0-rc2 artifact was uploaded https://pypi.org/project/aissemble-foundation-core-python/#history
- Verify the Quarkus Docker image 1.9.0-rc2 artifact was uploaded https://github.com/boozallen/aissemble/pkgs/container/aissemble-quarkus
- Verify the aissemble-airflow-chart 1.9.0-rc2 artifact was uploaded https://github.com/boozallen/aissemble/pkgs/container/aissemble-airflow-chart

**Comment by jacksondelametter** [comment]
Completed DOD with @ewilkins-csi @cwoods-cpointe @JeffreyRoss

**Comment by csun-cpointe** [comment]
OTS complete!
