### ISSUE TITLE
BUG: Configuration Store: `"aissemble-configuration-store-webhook-certs" not found` error when disabling the webhook

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#310]
## Description
Deploying the configuration-store app using argocd with the `webhook.enable` set to `false`, the configuration store app status becomes `Degraded` and the `configuration-store` pod fails with the `MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found` error
[
![Screenshot 2024-08-29 at 4 12 42 PM](https://github.com/user-attachments/assets/86522af3-92e0-41d8-bb4b-c35d1404089d)
](url)
![Screenshot 2024-08-29 at 4 03 50 PM](https://github.com/user-attachments/assets/f9d8ee11-6bfd-463b-ae61-dcc2691e8415)

## Steps to Reproduce
Clear, specific, and detailed steps taken to enable reproduction of the bug for investigation.
- Create a downstream project with baseline version 1.9.0-SNAPSHOT
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.9.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-310 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-310 \
  && cd test-310
```
- Add the [SparkPipeline.json](https://github.com/user-attachments/files/16781488/SparkPipeline.json) file to the test-defect-pipeline-models/src/main/resources/pipelines directory

- Add to the fermenter-mda plugin executions in test-defect-deploy/pom.xml
```
<execution>
    <id>configuration-store</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>generate-sources</goal>
    </goals>
    <configuration>
        <basePackage>com.boozallen.aissemble.test</basePackage>
        <profile>configuration-store-deploy-v2</profile>
        <!-- The property variables below are passed to the Generation Context and utilized
             to customize the deployment artifacts. -->
        <propertyVariables>
            <appName>configuration-store</appName>
        </propertyVariables>
    </configuration>
</execution>
```
- Run mvn clean install until all the manual actions are complete
- Once the manual actions are complete, run mvn clean install -Dmaven.build.cache.skipCache=true once to get any remaining manual actions

- In the `-deploy/src/main/resources/apps/configuration-store/values.yaml` file, add below content under `aissemble-configuration-store-chart`:
     ```
     webhook:
         enable: false
     ```

  and under `aissemble-quarkus-chart:`
     ```
     aissemble-quarkus-chart:
       toggleableConfiguration:
         toggle: false
     ```
- In the `-deploy/src/main/resources/apps/configuration-store/values-dev.yaml` file, remove the service `loadBalancer`:
```
    service:
      type: LoadBalancer
```

## Expected Behavior
A clear and concise description of the outcome you expected from the actions taken.
The `configuration-store` should be deployed successfully without any errors: 
- Run `tilt up; tilt down` to tilt up all services
- Verify the configuration-store starts without any errors and there is no webhook resource request in the `configuration-store` service log
- Tilt down all services
- Remove the added content above from the `-deploy/src/main/resources/apps/configuration-store/values.yaml`
- Run `tilt up; tilt down` to tilt up all services
- Run `kubectl get deployment configuration-store -n config-store-ns -o yaml` and make sure `volumes` contains

```
- name: certs
        secret:
          defaultMode: 420
          secretName: aissemble-configuration-store-webhook-certs
```
and under `volumeMounts` contains
```
- mountPath: /etc/webhook/cert
          name: certs
          readOnly: true
```

## Actual Behavior
A clear and concise description of the outcome you experienced from the actions taken.
The `configuration-store` fail to start with below error:
```

Attaching to existing pod (configuration-store-7b88dbf686-7krb2). Only new logs will be streamed.
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found
[event: pod config-store-ns/configuration-store-7b88dbf686-7krb2] MountVolume.SetUp failed for volume "certs" : secret "aissemble-configuration-store-webhook-certs" not found

```

## Additional Context
- Log output
- Screenshots (if applicable)
- Solution Baseline Version
- Environment details (local, cloud, Azure, AWS, etc.)

**Comment by csun-cpointe** [comment]
OTS completed with @carter-cundiff

**Comment by carter-cundiff** [comment]
Testing passed:
Without webhook:
![image](https://github.com/user-attachments/assets/057e21c4-8e51-4298-b12c-b4230052bbb6)

With webhook:
![image](https://github.com/user-attachments/assets/02b76f19-7ceb-4416-b8a3-db6cdc15e50f)
