### ISSUE TITLE
Feature: Generate Config Store by default and ensure proper documentation is in place under Supporting Component

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#322]
## Description
Now that the config store MVP is ready to go, we would like to enable it to be generated automatically into downstream projects by default. This includes creating manual actions for adding downstream and providing documentation outlining how to use it.

## DOD
- [x] Enable configuration-store deployment by default in downstream project
  - [x] Create manual action for adding the configuration-store execution to the deploy pom for projects without it
    - [x] **Stretch Goal:** #219
    - [x] Verify krausening is the default store backing and vault is not generated in 
- [x] Update the related documentation
  - [x] Release notes link to antora doc page
  - [x] Move the current [antora doc guide ](https://boozallen.github.io/aissemble/aissemble/current/guides/guides-configuration-store.html) to a page within supporting components
  - [x] Update content to insure it's all relevent to the MVP
    - [x] Remove details about policy configuration 

## Test Strategy/Script
**Test New Project**
- **OTS Only:**
  - Run the following: `mvn clean install -pl :foundation-mda -Dmaven.build.cache.skipCache=true`

- Create project from `1.9.0-SNAPSHOT`:
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.9.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-322\
  -DprojectGitUrl=test.url \
  -DprojectName=test-322 \
  && cd test-322
```
- Add the [SparkPipeline.json](https://github.com/user-attachments/files/16752612/SparkPipeline.json) file to the `test-322-pipeline-models/src/main/resources/pipelines` directory
- Run `mvn clean install -Dfermenter.display.message.keys=true` once and verify you see the following manual action as part of the `test-322-deploy/pom.xml` group
```
[WARNING] Message Key: test-322-deploy/pom.xml_execution_configuration-store
<execution>
    <id>configuration-store</id>
    <phase>generate-sources</phase>
    <goals>
        <goal>generate-sources</goal>
    </goals>
    <configuration>
        <basePackage>com.test</basePackage>
        <profile>configuration-store-deploy-v2</profile>
        <!-- The property variables below are passed to the Generation Context and utilized
                to customize the deployment artifacts. -->
        <propertyVariables>
            <appName>configuration-store</appName>
        </propertyVariables>
    </configuration>
</execution>
```
- Add the following configuration to the root `pom.xml` `fermenter-mda` `pluginManagement` (line 150):
```
<configuration>
  <suppressedMessages>
    <message>test-322-deploy/pom.xml_execution_configuration-store</message>
  </suppressedMessages>
</configuration>
```
- Run `mvn clean install -Dmaven.build.cache.skipCache=true` and verify the manual action above for the config store does NOT appear this time
- Remove the `fermenter-mda` configuration block and run `mvn clean install -Dmaven.build.cache.skipCache=true` again
- Complete the manual actions and run `mvn clean install`
- Verify the `test-322-deploy/src/main/resources/apps/configuration-store` module is generated
 
**Test Upgrading Project**
- Create project from `1.8.1`:
- Build out the project
- Update project root `pom.xml` parent to `1.9.0-SNAPSHOT` and run `mvn clean install`
- Verify you get a manual action to add the configuration store

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by carter-cundiff** [comment]
DOD with @ewilkins-csi

**Comment by csun-cpointe** [comment]
OTS completed!!

**Comment by ewilkins-csi** [comment]
✅ **Final Test** passed
