### ISSUE TITLE
Feature: Github Actions build workflow does not hit Docker Hub rate limit error

### ISSUE THREAD

**Issue by colinpalmer-pro** [boozallen/aissemble#331]
## Description
When the aiSSEMBLE build GitHub Actions is executed, we eventually hit a Dockerhub rate limit near the end of the day. Based on the Docker account, we should not encounter an issue with the Docker rate limit.

Possible Solutions
- Determine if there is an issue with the account
  - Are we actually authenticating with the correct account, does the account have the expected limit, etc.
- Use the nexus mirror that we currently use for our Jenkins

## DOD
- [x] Ensure Authentication to Dockerhub with the correct account
- [x] Ensure the account has the expected privileges and limits
- [x] The build Github Action is able to run successfully without unauthenticated requests to docker hub (and thus not hitting the unauthenticated rate limit error)

#### OTS
Local
- Prune docker - `docker system prune -a`
  - Verify there are no aiSSEMBLE images: `docker image ls`
- Gather "before" rate limit data for your authenticated account and unauthenticated account
  - See https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/
  - We will compare this with our rate limits after the build to ensure that no unauthenticated requests were sent to docker hub
- Login to dockerhub from the cli
  - Either run `docker login -u <username>` or update ~/.docker/config.json with your credentials in the following manner:
```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<base64 encoded username:token or password>"
		}
	}
}
```
  - This simulates the docker login action of authenticating at the beginning of the ci build
- Build the aissemble project without cache and run integration tests: `mvn clean install -Dmaven.build.cache.skipCache=true -Pintegration-test`
- Ensure the build passes
- Gather "after" rate limit data for your authenticated account and unauthenticated account
  - See https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/
  - The unauthenticated rate limit should stay the same and the authenticated rate limit should decrease from the "before" number
- Spot check docker build logs for authentication:
  - Check the aissemble-vault module ([60/145]) and verify you see:
    - `[auth] library/alpine:pull token for registry-1.docker.io`
  - Check the aissemble-fastapi module ([77/145]) and verify you see:
    - `[auth] library/python:pull token for registry-1.docker.io`
   - Check the aissemble-hive-service module ([78/145]) and verify you see:
     - `[auth] apache/hive:pull token for registry-1.docker.io`
     - `[auth] library/eclipse-temurin:pull token for registry-1.docker.io`
   - Check the aissemble-jenkins-controller modules ([80/145]) and verify you see:
     - `[auth] jenkins/jenkins:pull token for registry-1.docker.io`
  - Check the aissemble-jenkins-agent module ([81/145]) and verify you see:
    - `[auth] jenkins/ssh-agent:pull token for registry-1.docker.io`
  - Check the aissemble-nvidia module ([84/145]) and verify you see:
    - `[auth] nvidia/cuda:pull token for registry-1.docker.io`
  - Check the aissemble-spark module ([86/145]) and verify you see:
    - `[auth] apache/spark-py:pull token for registry-1.docker.io`    
  - Check the aissemble-spark-operator module ([88/145]) and verify you see:
    - `[auth] kubeflow/spark-operator:pull token for registry-1.docker.io`

CI/GitHub Actions
- Ensure [build 156](https://github.com/boozallen/aissemble/actions/runs/11094801649) succeeded
- Spot check docker build logs for authentication (follow step from above section)
- Inspect dockerhub data to see images that were pulled during the run (view green highlighted rows, Rows 19-34 for OTS and Rows 5 and 12-26 for Final Test)
  - Data will show images from the fabric8 logs above as well as additional images pulled outside of fabric8
  - Images include:
    - vectorized/redpanda
    - moby/buildkit
    - nvidia/cuda
    - library/rabbitmq
    - library/python
    - library/eclipse-temurin
    - library/alpine
    - jenkins/ssh-agent
    - jenkins/jenkins
    - apache/spark-py
    - apache/hive
    - kubeflow/spark-operator
    - bitnamicharts/mysql

#### Final Test
- Verify successful ci build ([Build aissemble 254](https://github.com/boozallen/aissemble/actions/runs/11110974317))
- From the [Build aissemble 254](https://github.com/boozallen/aissemble/actions/runs/11110974317) page, select **build** and then expand the **Build aiSSEMBLE** dropdown
  - From the OTS Local section above, perform the "Spot check docker build logs for authentication" step (search/find specific auth logs)
    - This verifies authentication during fabric8 builds
- From the OTS CI/GitHub Actions section above, use the **docker-hub_pulls_FinalTest.xlsx** file and perform the "Inspect dockerhub data to see images that were pulled during the run" step
  - This verifies authentication during fabric8 builds and for modules that pull images without utilizing fabric8

## References/Additional Context
- Example of [build failure](https://github.com/boozallen/aissemble/actions/runs/10834813236/job/30064881570) due to 429 Too Many Requests Error
- [Docker Hub usage and rate limits](https://docs.docker.com/docker-hub/download-rate-limit/)

**Comment by colinpalmer-pro** [comment]
PR: https://github.com/boozallen/aissemble/pull/381

**Comment by JeffreyRoss** [comment]
Testing completed. Was able to verify images were pulled and build successful.
