### ISSUE TITLE
TASK: Release 1.8.1

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#333]
## Description
We are ready to cut the release for 1.8.0. We are still in process of getting GitHub actions ready for the release so will continue to use the old infrastructure for this release.

- [x] 1.8.1 artifacts have been published to public repositories
- [x] 1.8.1 release notes have been published
- [x] 1.8.1 documentation been published

## Test Strategy/Script
1. Ensure latest release notes are for 1.8.1 patch release
2. Ensure 1.8 upgrade instructions specify 1.8.1 instead of 1.8.0
3. Ensure latest [archetype docs](https://boozallen.github.io/aissemble/aissemble/current/archetype.html) say 1.8.1
4. Create a new project from the 1.8.1 archetype:
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.8.1 \
                       -DgroupId=org.test \
                       -DartifactId=verify-release \
                       -DprojectGitUrl=test.org/verify-release.git \
                       -DprojectName="Verify 1.8.1 Release" \
&& cd verify-release
```
5. Add a simple pipeline to verify-release-pipeline-models 
[SparkPipeline.json](https://github.com/user-attachments/files/16987379/SparkPipeline.json)
6. Build the project: ./mvnw clean install
7. Follow manual actions
8. Repeat prior two steps until no more manual actions are printed
9. Do an uncached build so the docker target directories are correct: ./mvnw clean install -Dmaven.build.cache.skipCache
10. Deploy the project via Tilt and verify it can be deployed

**Comment by ewilkins-csi** [comment]
**OTS** with @carter-cundiff and @csun-cpointe

**Comment by csun-cpointe** [comment]
Final test passed!!
