### ISSUE TITLE
Feature: Update ghcr.io prune workflow to leverage regex solution

### ISSUE THREAD

**Issue by cpointe-ibllanos** [boozallen/aissemble#338]
## Description
The GH prune workflow ([dataaxiom/ghcr-cleanup-action](https://github.com/dataaxiom/ghcr-cleanup-action/)) has new changes changes that we can leverage to simplify our existing workflow file.

Specifically, the ghcr-cleanup-action now supports regular expressions and allows multiple package names, allowing us to remove most, if not all, scripting (phase 1: fetch_image_info).

## DOD
- [x] Scripting is removed from GitHub prune action in favor of regex solution
- [x] Prune works as intended
- [ ] If we find issues that we can solve and contribute back, open a PR
## Test Strategy/Script 
- manually kick off the prune workflow (keep `dry-run: true`)
- Use the workflow logs for the `prune_ghcr (image-name)` steps to confirm the following
- The `Prune ghcr > Runtime configuration` section should look like the following:
```
Runtime configuration
  private repository          false
  project owner               boozallen
  repository                  aissemble
  package                     ^aissemble(?!.*?-chart$).*$
  expand-packages             true
  exclude-tags                ^\d+\.\d+\.\d+$
  keep-n-tagged               2
  dry-run                     true
  log-level                   INFO
  use-regex                   true
```
- Review the `Prune ghcr > Loaded Package Data` section - note the two most recent NON-release versions found. For most images, this should be `1.9.0-SNAPSHOT` and `1.8.2-SNAPSHOT`. 
-  **NOTE**: `aissemble-airflow`, `aissemble-kafka`, and `aissemble-mlflow` images are deprecated and will not have a `1.9.0-SNAPSHOT` tag
- Review the `Prune ghcr > Finding tagged images to delete, keeping 2 versions section` and confirm that the list does not include any release versions (e.g., `1.8.0`,`1.7.0`) or the two most recent non-release versions (e.g., `1.9.0-SNAPSHOT`, `1.8.2-SNAPSHOT`)
- Review the `Prune ghcr > Deleting packages` section and confirm that the list does not include any release versions or the two most recent non-release versions

Final Test:
- Confirm [Prune workflow](https://github.com/boozallen/aissemble/actions/workflows/prune.yml) is re-enabled
- Kick off the prune workflow with the dev branch and confirm successful
- Use the workflow logs for the `prune_ghcr (image-name)` steps to confirm the following
- The `Prune ghcr > Runtime configuration` section should look like the following:
```
Runtime configuration
  private repository          false
  project owner               boozallen
  repository                  aissemble
  package                     ^aissemble(?!.*?-chart$).*$
  expand-packages             true
  exclude-tags                ^\d+\.\d+\.\d+$
  keep-n-tagged               2
  log-level                   INFO
  use-regex                   true
```
- Review the `Prune ghcr > Loaded Package Data` section - note the two most recent NON-release versions found. For most images, this should be `1.9.0-SNAPSHOT` and `1.8.2-SNAPSHOT`. 
-  **NOTE**: `aissemble-airflow`, `aissemble-kafka`, and `aissemble-mlflow` images are deprecated and will not have a `1.9.0-SNAPSHOT` tag
- Review the `Prune ghcr > Finding tagged images to delete, keeping 2 versions section` and confirm that the list does not include any release versions (e.g., `1.8.0`,`1.7.0`) or the two most recent non-release versions (e.g., `1.9.0-SNAPSHOT`, `1.8.2-SNAPSHOT`)
- Review the `Prune ghcr > Deleting packages` section and confirm that the list does not include any release versions or the two most recent non-release versions
- Successfully pull a `1.8.0`, `1.8.1`, `1.7.0`, `1.8.2-SNAPSHOT` and `1.9.0-SNAPSHOT` docker image
```
docker pull ghcr.io/boozallen/[image-name]:1.8.0
docker pull ghcr.io/boozallen/[image-name]:1.7.0
docker pull ghcr.io/boozallen/[image-name]:1.9.0-SNAPSHOT
docker pull ghcr.io/boozallen/[image-name]:1.8.2-SNAPSHOT
docker pull ghcr.io/boozallen/[image-name]:1.8.1
```

## References/Additional Context
[Container retention policy doc](https://github.com/marketplace/actions/container-retention-policy#safely-handling-multi-platform-multi-arch-packages)

## References/Additional Context
More info can be found in [this](https://github.com/boozallen/aissemble/pull/296#issuecomment-2346919325) PR comment.

**Comment by chang-annie** [comment]
all test steps are passing!

- [x] ran prune workflow against dev branch - [logs](https://github.com/boozallen/aissemble/actions/runs/10943369113/job/30382614966)
- [x] confirmed runtime configuration is correct
```
 Runtime configuration
  private repository          false
  project owner               boozallen
  repository                  aissemble
  package                     ^aissemble(?!.*?-chart$).*$
  expand-packages             true
  exclude-tags                ^\d+\.\d+\.\d+$
  keep-n-tagged               2
  log-level                   INFO
  use-regex                   true
```
- [x] confirmed that two most recent non-release versions (typically `1.9.0-SNAPSHOT` and `1.8.2-SNAPSHOT`) are not being pruned
- [x] confirmed that `Excluding tags for deletion` includes all release versions `1.8.2`, `1.8.1`, `1.8.0`, `1.7.0` and they are not being pruned
- [x] successfully pulled a `1.8.0`, `1.8.1`, `1.7.0`, `1.8.2-SNAPSHOT` and `1.9.0-SNAPSHOT` docker image
