### ISSUE TITLE
Bug: Fix Spark Operator permissions and release 1.8.2

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#345]
## Description
Cherry-pick fix to RBAC settings for Spark Operator (ce08e16842) and broaden PDP migration for `aiops-security.properties` -> `aissemble-security.properties` so it catches more things like unit test files.

## DOD
- [x] Spark Operator RBAC fix cherry-picked
- [x] PDP Migration broadened
- [x] Release artifacts published
- [x] Release notes published
- [x] Docs published

## Test Strategy/Script
- Create a 1.7 project with a simple data pipeline
- Generate out the project
- Add an aiops-security.properties file in the `src/test/resources` directory of the pipeline
- Upgrade the root POM to aiSSEMBLE 1.8.2
- Run the build and ensure the aiops-security.properties file in the test directory has been renamed
- Deploy the project and ensure the pipeline can be triggered by the Pipeline Invocation service

**Comment by cwoods-cpointe** [comment]
Tested by upgrading a 1.7.0 project to 1.8.2.
Confirmed the release resolves the missing Spark Operator RBAC and the strict PDP Migration.
