### ISSUE TITLE
Feature: Update Metadata service for Java 17

### ISSUE THREAD

**Issue by jacksondelametter** [boozallen/aissemble#351]
## Description

Follow on to #133, where we want to migrate our whole repository to java 17. This issue will focus on migrating the metadata modules to enable provenance within downstream projects.

## Definition of Done
- [x] Update the following submodules to build with JDK 17
  - [x] `foundation-metadata-core`
  - [x] `foundation-metadata-producer`
  - [x] `extensions-metadata-service`
  - [x] `aissemble-metadata` (docker)
- [x] Ensure all pom dependencies are compatible
    - [x] Update to jakarta if applicable
    - [x] Update to official java 17 version if applicable
- [x] Clean up pom to remove unnecessary dependencies and add undeclared transient dependencies 
  - [x] Use `mvn dependency:analyze`

## Test Strategy/Script
- Update your machine to build with JDK 17. Run `mvn -v` to verify it's configured properly. The output should be similar to the following (**Note**: java distributions different thank `openjdk` are okay):
```
$ mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /path/to/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6
Java version: 17.0.8.1, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
```

- **OTS Only:**
  - Within the aiSSEMBLE repo, run the following and verify it builds successfully:
  ```
  mvn clean install -pl :aissemble-metadata,:foundation-metadata-producer,:foundation-archetype -am -Dmaven.build.cache.skipCache
  ```

- Create a downstream project:
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.10.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-351 \
  -DprojectGitUrl=test.url \
  -DprojectName=test-351 \
  && cd test-351
```

- Add the attached [SparkPipelineMetadata.json](https://github.com/user-attachments/files/17437001/SparkPipelineMetadata.json) to the `test-351-pipeline-models/src/main/resources/pipelines/` directory

- Run `mvn clean install` until all the manual actions are complete
- Run `mvn clean install -Dmaven.build.cache.skipCache` to get any remaining manual actions
- **OTS Only:**
  - Add the following to `test-351-deploy/src/main/resources/apps/metadata/values.yaml`:
  ```
  aissemble-metadata-chart:
    image:
      imagePullPolicy: IfNotPresent
  ```
- `tilt up`
- Wait for all the resources to be ready on the tilt ui
- In a separate terminal, run the following:
```
curl -X GET http://localhost:8082/metadata/healthcheck
```

- Verify it returns the following:
```
Metadata service is running...
```

- Start the `spark-pipeline-metadata` resource and wait for it to complete
- Wait until the `metadata` resource logs the following (Note: `VertxException: Thread blocked` are expected):
```
INFO HiveMetadataAPIService: Metadata saved
```

- In a separate terminal, run the following:
```
curl -X GET http://localhost:8082/metadata
```

- Verify it returns the following:
```
[{"resource":"Unspecified TestSyncStep resource","subject":"synchronous","action":"TestSyncStep","timestamp":"CURRENT_TIME_STAMP","additionalValues":{}}]
```

## References/Additional Context

**Comment by carter-cundiff** [comment]
OTS with @jacksondelametter

**Comment by ewilkins-csi** [comment]
**Final Test** passed ✅ 
- Health check:
    <img width="743" alt="Screenshot 2024-10-18 at 5 01 26 PM" src="https://github.com/user-attachments/assets/deb08b2b-4d32-4ebf-a1ea-1864a75490c0">
- Metadata saved:
    ![Screenshot 2024-10-18 at 5 11 52 PM](https://github.com/user-attachments/assets/55c40b33-e80d-4945-8090-bda8786bf441)
- Metadata fetched:
    <img width="743" alt="Screenshot 2024-10-18 at 5 12 42 PM" src="https://github.com/user-attachments/assets/e06e2d2e-f747-49d6-930a-b295dc392b16">
