### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Policy Decision Point

### ISSUE THREAD

**Issue by cwoods-cpointe** [boozallen/aissemble#354]
## Description
In https://github.com/boozallen/aissemble/issues/133 we modified the build-parent to use JDK 17. When building aiSSEMBLE with the updated build-parent, some modules do not build successfully. This is a series of ticket to fix broken modules. This issue will focus on the policy decision point functionality

## DOD
- [x] Modify the foundation-security and extensions-security modules to build successful
- [x] Deploy the PDP service through Helm
- [x] Verify the PDP service is reachable and the healthcheck works
- [x] Verify the service can generate a JWT
- [x] Verify we can authenticate using the JWT
- [x] Make note of any changes made to the service and the impact it has on generated MDA code for pipeline steps
-  All changes were made in foundation-security, extensions-security, aissemble-policy-decision, and aissemble-quarkus. This should not effect generated MDA code. 

## Test Steps
- In a terminal, execute `brew install --cask temurin@17` to install Java 17
- Set Java 17 as your default version. Change your JAVA_HOME variable to point to the JDK 17 HOME location. Note: I left out instructions to do this because of the variety of shells being used. 
- Clone the aiSSEMBLE repository https://github.com/boozallen/aissemble. 
- Execute `git checkout feature-java17` to checkout feature branch
- In the project's root directory, execute the following and verify successful builds
  -  `mvn clean install -pl :aissemble-policy-decision-point -am` Note: Make sure the image actually builds. 
  -  `mvn clean install -pl :aissemble-policy-decision-point-chart -am`
- Execute 
```
helm install --set image.tag=1.10.0-SNAPSHOT,image.imagePullPolicy=IfNotPresent,service.spec.type=LoadBalancer aissemble-policy extensions/extensions-helm/aissemble-policy-decision-point-chart/
```
- Execute `kubectl get pods`, verify the aissemble-policy-decision-point-chart-* is running
- Using Postman, run through the following
  - Send a Healthcheck request
    - Set method to GET
    - Set URL to http://localhost:8080/api/healthcheck
    - Click **Send**, verify you get the response **PDP Service is running...**
  - Get a JWT token
    - Set method to POST
    - Set URL to http://localhost:8080/api/authenticate
    - Set the body type to JSON
    - Set body contents to: `{"username": "aissemble","password": ""}`
    - Click **Send**, verify you get a JWT token in the response
  - Validate JWT token
    - Set method to POST
    - Set URL to http://localhost:8080/api/pdp
    - Set the body type to JSON
    - Set body contents to `{"jwt": "JWT_TOKEN","resource": "","action": "data-access"}` where JWT_TOKEN is the token from the previous request
    - Click **Send**, verify you get the response **PERMIT**

**Comment by carter-cundiff** [comment]
OTS passed

**Comment by csun-cpointe** [comment]
Test passed!
**Send a Healthcheck request**
<img width="600" alt="Screenshot 2024-09-27 at 10 09 57 AM" src="https://github.com/user-attachments/assets/add92a7e-d292-406b-b634-0991f90f2c2e">

**Get a JWT token**
<img width="600" alt="Screenshot 2024-09-27 at 10 10 35 AM" src="https://github.com/user-attachments/assets/3dcc07fd-7250-4971-a126-6bbd7fcb0e0d">

**Validate JWT token**
<img width="600" alt="Screenshot 2024-09-27 at 10 11 53 AM" src="https://github.com/user-attachments/assets/3c57ce84-e0d1-4e11-9404-eaf774ce1da6">
