### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Foundation Maven plugins

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#360]
## Description
Follow on #133 and #355 where we have upgrade the foundation core library to java 17 including the `foundation-maven-plugin` module, for this ticket we want to make sure the `foundation-maven-plugins` functionalities still work as expected.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Smoke test on the `mda-maven-plugin` functionalities
   - [x] Create downstream project with java 17 and ensure that all the kubernetes resources are copied under the -deploy/src/main/resources directory
     - Create a downstream project using java 17
            ```
             mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \                  
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.9.0-SNAPSHOT \
                       -DgroupId=org.test \
                       -DartifactId=test-maven-plugin \
                       -DprojectGitUrl=test.org/test-maven-plugin.git \
                       -DprojectName="Test Maven Plugin" && cd test-maven-plugin
            ```
     - Add the attached pipeline model:[MachineLearningPipeline.json](https://github.com/user-attachments/files/17119303/MachineLearningPipeline.json)
[PySparkPipeline.json](https://github.com/user-attachments/files/17119306/PySparkPipeline.json)
     - Repeatedly run `mvn clean install -Dmaven.build.cache.skipCache` and resolve the manual actions until no more manual actions
     - Verify the pipeline values files are copied under `-deploy/src/main/resources/apps/pipeline-invocation-service/target` directory
     - Verify `test-maven-plugin-docker/test-maven-plugin-spark-worker-docker/target/dockerbuild/py-spark-pipeline/py_spark_pipeline-1.0.0.dev0.tar.gz` exists.
- [x] Smoke test on the `artifacts-maven-plugin` module functionalities
   - Open up a terminal instance, create the folder `~/Documents/test_repository`.
   - Open up another terminal instance and at the baseline root directory, go to the folder `foundation/foundation-maven-plugins/artifacts-maven-plugin/src/test/resources/pom`
   - Open up the pom.xml file. Take note of some of the dependencies group IDs, artifact IDs, and versions
   - Execute the following command to deploy all the plugin's direct dependencies to the local repository
   ```
       mvn com.boozallen.aissemble:artifacts-maven-plugin:1.9.0-SNAPSHOT:propagate-all -Durl=file://<full path to created repository> 

   ```
   - Go to `~/Documents/test_repository/`. You should see artifacts directly declared it the pom.xml file. 
   - Go to `~/Documents/test_repository/codehaus/plexus/plexus-interpolation`. You should see artifacts that were not directly declare in the pom.xml file. 
- [x] Successfully build the `foundation-model-plugin` module

## Test Strategy/Script

- `git checkout feature-java17` and `git pull` the latest
- Run `mvn clean install -Dmaven.build.cache.skipCache` 
Note: it is expected that the build will failed at `extensions-authzforce-attribute` module
- Follow the Smoke test steps to make sure the all tests are success

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by carter-cundiff** [comment]
DOD/OTS passed
