### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Semantic data (incl. data transform & encryption)

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#363]
## Description
In #133  we modified the build-parent to use JDK 17. When building aiSSEMBLE with the updated build-parent, some modules do not build successfully. This is a series of ticket to fix broken modules. This issue will focus on the semantic data (including data transform and data encryption) functionality

## DOD
Acceptance criteria required to realize the requested feature
The builds for following modules work:
- [x] `extensions-encryption`
- [x] `extensions-transform`
- [x] `aissemble-vault`
- [ ] Note the migration needed if there are template changes
- [ ] Smoke test success on the `extenions-encryption` module (all tests are run with spit module setup)
   - [x] AES encryption
   - [x] Custom dictionary
   - [x] Data validation
   - [ ] Simple persistent format

## Test Strategy/Script
- Create a downstream project using java 17
   ```
             mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \                  
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.10.0-SNAPSHOT \
                       -DgroupId=org.test \
                       -DartifactId=test-363 \
                       -DprojectGitUrl=test.org/test-363.git \
                       -DprojectName="Test 363" && cd test-363

   ```
- Unzip the attached pipeline [resources.zip](https://github.com/user-attachments/files/17237632/resources.zip) and replace the `-pipeline-models/src/main/resources` folder:
- In the -shared/pom.xml file update to use split data record
     ```
                        <configuration>
                            <basePackage>com.boozallen</basePackage>
   -                        <profile>aissemble-data-records-combine-module</profile>
   +                        <profile>aissemble-data-records-separate-module</profile>
                        </configuration>
     ```
- Repeatedly run `mvn clean install -Dmaven.build.cache.skipCache` and resolve the manual actions until no more manual actions
**Note**: **Do not include** the data-access related modules
**Note**: Before include the `spark-pipeline` to the `pipelines` module, **update** the `-pipelines/spark-pipeline/pom.xml` data record dependency to use `-data-record-spark` module
```
        <dependency>
            <groupId>${project.groupId}</groupId>
-           <artifactId>test-363-data-records</artifactId>
+           <artifactId>test-363-data-records-spark</artifactId>
            <version>${project.version}</version>
        </dependency>
```
- Unzip the [Step&DriverClasses.zip](https://github.com/user-attachments/files/17237638/Step.DriverClasses.zip) and replace the  `EncryptDataTest.java` and `SparkPipelineDriver.java` files under `-pipelines/spark-pipeline-src/main/java/simple/test/` with the attached ones.
- Unzip the [krausening.zip](https://github.com/user-attachments/files/17236951/krausening.zip)
and replace the `spark-worker-docker/src/main/resourcs/krausening` folder
- Run `mvn clean install `
- Tilt up all services
- Wait until all services are ready and manually run the `spark-pipeline` service
- Verify the log that only the record satisfies the validation remain and the `ssn` is being encrypted and decrypted correctly
Note: the records are being dynamically generated but the Student Tester should always exist in the record after validation
```

=============== after validation ===================
24/10/03 00:07:22 INFO CodeGenerator: Code generated in 67.774791 ms
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|name          |ssn         |age|employment        |stringLength5To12|long2000To3000|short100To200|decimal10To20|double20To30|float30To40|
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|Student Tester|111-222-7777|10 |Elementary Student|AbCD3fG          |2001          |101          |11.00        |21.369      |32.246     |
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+

=============== after encryption ===================
+--------------+------------------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|name          |ssn                     |age|employment        |stringLength5To12|long2000To3000|short100To200|decimal10To20|double20To30|float30To40|
+--------------+------------------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|Student Tester|nn+lmJuvUOU2Zi5ZMqoGjg==|10 |Elementary Student|AbCD3fG          |2001          |101          |11.00        |21.369      |32.246     |
+--------------+------------------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+

=============== after decryption ===================
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|name          |ssn         |age|employment        |stringLength5To12|long2000To3000|short100To200|decimal10To20|double20To30|float30To40|
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+
|Student Tester|111-222-7777|10 |Elementary Student|AbCD3fG          |2001          |101          |11.00        |21.369      |32.246     |
+--------------+------------+---+------------------+-----------------+--------------+-------------+-------------+------------+-----------+

```

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by csun-cpointe** [comment]
DoD complete with @carter-cundiff @ewilkins-csi @nartieri

**Comment by csun-cpointe** [comment]
It is unclear whether `protectionPolicy` has been superseded by `securityPolicy` and if the `protectionPolicy` is a supported feature. We will leave it off for now, investigate and clean up later.

**Comment by ewilkins-csi** [comment]
**OTS** test passed ✅

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/26b42465-02fc-4b7d-8780-1b154df55188)
