### ISSUE TITLE
BUG: Configuration Store added to Tiltfile as suggested by manual action fails to start

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#370]
## Description
We intended to remove the manual action to add the config store to Tilt, but inadvertently just reverted it back to using the standard Tilt deployment action message. Adding the store in this way causes failures as noted in https://github.com/boozallen/aissemble/issues/353#issuecomment-2377326104.

## Steps to Reproduce
1. Create a project from 1.9.1
2. Build the project following manual actions
3. Tilt up
4. The config-store-webhook-init job will show as failed

## Expected Behavior
The build does not recommend adding the config store to the Tiltfile.

## Actual Behavior
The build recommends adding the config store in a way that does not work.

## Additional Context
- Version 1.9.1

## Definition of Done
- Fix bug above so that the expected behavior is implemented
- Release patch 1.9.2

### OTS
1. Create a project from 1.9.2 (**OTS:** 1.9.2-SNAPSHOT)
```sh
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.9.2-SNAPSHOT \
                       -DgroupId=org.test -DartifactId=verify-1-9-2 \
                       -DprojectGitUrl=test.org/verify-1-9-2.git \
                       -DprojectName="Verify 1.9.2 Release" \
&& cd verify-1-9-2
```
2. Add the following to _verify-1-9-2-deploy/pom.xml_ with the other Fermenter executions:
```xml
                    <execution>
                        <id>configuration-store</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <basePackage>src/main/</basePackage>
                            <profile>configuration-store-deploy-v2</profile>
                            <propertyVariables>
                                <appName>configuration-store</appName>
                            </propertyVariables>
                        </configuration>
                    </execution>
```
3. Run Fermenter and verify no manual action for adding the Configuration Store to Tilt is displayed
```sh
mvn clean generate-sources -am -pl :verify-1-9-2-deploy
```
### Final Test
1. Create a project from 1.9.2 (**OTS:** 1.9.2-SNAPSHOT)
```sh
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.9.2\
                       -DgroupId=org.test -DartifactId=verify-1-9-2 \
                       -DprojectGitUrl=test.org/verify-1-9-2.git \
                       -DprojectName="Verify 1.9.2 Release" \
&& cd verify-1-9-2
```
2. Run the build manual actions until none are displayed
```sh
mvn clean install
```
3. Run a final install without cache
```sh
mvn clean install -Dmaven.build.cache.skipCache
```
4. Deploy with `tilt up`
5. Verify everything starts and no **_configuration-store_** resources are listed

**Comment by nartieri** [comment]
Testing Status: Passed! 🎉 

![image](https://github.com/user-attachments/assets/e9e6fe89-5e0b-4dc2-9af1-78d62da49c63)
