### ISSUE TITLE
Feature: Add unit tests for pyproject.toml.vm Python version updates

### ISSUE THREAD

**Issue by meliz19** [boozallen/aissemble#379]
## Description
This is a follow on to #366. In that ticket, I updated the Python version in the `pyproject.toml.vm` files. The purpose of this ticket is to write unit tests to verify the Python version updates in all of the `pyproject.toml.vm` files.

## DOD
- [x]  Write unit tests for the following files to verify the Python version updates
- [x] `foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/combined.pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/separate.core.pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/data-delivery-data-records/separate.spark.pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/data-delivery-pyspark/pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/general-mlflow/pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/inference/pyproject.toml.vm`
- [x] `foundation/foundation-mda/src/main/resources/templates/sagemaker-training/pyproject.toml.vm`

## Test Strategy/Script
*Test 1: OTS*
- From the root project directory, run the following command. Verify it builds successfully. 
```
cd foundation/foundation-mda && ~/aissemble/mvnw clean install && cd -
```
*Test 2*
- Verify the unit tests passed in the CI build
## References/Additional Context
None

**Comment by meliz19** [comment]
Completed DoD with @d-ryan-ashcraft

**Comment by meliz19** [comment]
Completed OTS with @cwoods-cpointe @habibimoiz

**Comment by chang-annie** [comment]
test steps are passing! CI build succeeded and all the unit tests passed.
