### ISSUE TITLE
Feature: Update aiSSEMBLE docs with updated Java version in the Getting Started Page

### ISSUE THREAD

**Issue by habibimoiz** [boozallen/aissemble#383]
## Description
In [#133](https://github.com/boozallen/aissemble/issues/133) we modified the build-parent to use JDK 17. The focus of this issue is to update the Java version from 11 to 17 in the aiSSEMBLE docs.

## DOD
Acceptance criteria required to realize the requested feature
- [ ] Update aiSSEMBLE docs indicating the config-tool is now installing Java17 instead of Java 11. 

## Test Strategy/Script

- **Test 1:** Validate the aiSSEMBLE docs have been updated to indicate that Java17 is being installed rather than Java11. 

## References/Additional Context
- _tbd_

**Comment by habibimoiz** [comment]
DoD reviewed and approved by @chang-annie.

**Comment by habibimoiz** [comment]
2nd DoD reviewed and approved by @cwoods-cpointe.

**Comment by ewilkins-csi** [comment]
Already fixed
