### ISSUE TITLE
Feature: Investigate slow nightly CI build time & improve it

### ISSUE THREAD

**Issue by meliz19** [boozallen/aissemble#397]
## Description
Recently, the CI build time has increased significantly (3+ hours). Two Python modules, `aiSSEMBLE::Extensions::Docker::Model Training API Sagemaker` and `aiSSEMBLE::Extensions::Docker::Versioning` have been noted to take 42 and 32 min, respectively. The purpose of this ticket is to investigate the reason for this increase and identify a means of decreasing the build time for ~these modules~ aiSSEMBLE as a whole. 

## DOD
- [x] Investigate the cause of the extended Python module build times
- [x] Decrease the build time of `aiSSEMBLE::Extensions::Docker::Model Training API Sagemaker`
  - No one uses the Sagemaker modules, so we have decided to remove all of the Sagemaker modules from the main aiSSEMBLE build.
  - In short, I found a way to make the image build faster, so I will create two separate commits in the PR. See Findings for details.
- ~Decrease the build time of `aiSSEMBLE::Extensions::Docker::Versioning`~
  - In short, it's because we're building arm64 Docker images on an amd64 machine that it's taking so long to build these images. See Findings for details. We will explore improving the efficiency of the arm64 Docker image builds in the future. 
- [x] Remove all Sagemaker modules and related documentation from aiSSEMBLE.

### OTS Only
1. Clone or pull the latest version of `git@github.com:boozallen/aissemble.git`
2. Verify the project builds successfully.
```
.\mvnw clean install -Dmaven.build.cache.skipCache
```
### Final Test
1. Verify that the CI build is successful and that the following modules are no longer present in the Reactor summary.
```
aiSSEMBLE::Extensions::Model Training API Sagemaker
aiSSEMBLE::Extensions::Docker::Model Training API Sagemaker
aiSSEMBLE::Test::MDA::Machine Learning::Machine Learning Sagemaker Training
```

### Findings
- Lowering the minimum `python` version in `pyproject.toml` files increases the dependency resolution time. The reason for this is that Poetry uses strict package versioning requirements to ensure package reproducibility. 
- TL;DR It appears that adding redundant dependencies to poetry's `pyproject.toml` increases the dependency resolution time. 
  - The `aiSSEMBLE::Extensions::Model Training API Sagemaker` and `aiSSEMBLE::Extensions::Docker::Model Training API Sagemaker` modules reference the same `pyproject.toml` file. Currently, this file includes `sagemaker = ">=2.218.0"` and `mlflow = "^2.3.1"` as dependencies. `sagemaker = ">=2.218.0"` includes `mlflow` as a dependency. Removing `mlflow = "^2.3.1"` as an explicit dependency from the `pyproject.toml` decreases the `aiSSEMBLE::Extensions::Model Training API Sagemaker` module build time from ~6 min to ~3 min and decreases the `aiSSEMBLE::Extensions::Docker::Model Training API Sagemaker` module build time from ~43 min to ~ 15 min. I suspect the reason for this drastic decrease is because by removing the explicit `mlflow` dependency, Poetry doesn't force itself to compare the `mlflow = "^2.3.1"`'s dependencies with the `sagemaker` specified `mlflow` version and its dependencies.
- The `aissemble-versioning` module takes 30+ minutes to build. The reason for this is that the arm64 and amd64 docker builds take dramatically different times to run `poetry lock`, ~30min and ~3 min respectively. I don't see a simple/reasonable way to reduce this build time.

**Comment by meliz19** [comment]
Completed OTS with @cwoods-cpointe.

**Comment by habibimoiz** [comment]
Steps to test passed successfully.
