### ISSUE TITLE
Feature: Java 17 Upgrade Support Series - Pipeline persistence

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#398]
## Description
In #356 we upgraded the bulk of Spark pipeline functionality to Java 17. This tackles the follow-on work of updating the persistence logic of pipeline steps.  The available persistence types are:
 - hive
 - delta-lake
 - rdbms
   - **Note:** this used to be the `postgres` option but was updated to be `rdbms`. However, because many of the Java configs still refer to postgres it's unclear if this was tested with anything other than postgres.
   - **Update:** Java's `postgres` and `rdbms` options are separate but entangled so neither works
 - elasticsearch
 - neo4j

## DOD
Acceptance criteria required to realize the requested feature
- [x] A pipeline can write to and read from the following data sources while running on the new Java 17 Spark Worker:
   - [x] hive
   - [x] delta-lake
   - ~rdbms~
     - ~MySql (fallback to Postgres if RDBMS hasn't been properly generalized)~
     - ~Clean up config names (if time allows)~
   ---- stretch goal ----
   - [x] elasticsearch
     - Did not test reading from ES as I couldn't quite figure out the syntax and it was a low-priority item 
   - [x] neo4j
     - _Note:_ There is a pre-existing issue with Neo4j that prevents _reading_ data from a table. The data can be saved, just not read.
 - [x] Write migrations for updates
   - [x] Migrate SparkApplication delta-lake dependencies
   - [x] Migrate POM delta-lake dependencies

### Main Test
1. Create a new project on 1.10.0-SNAPSHOT.
    ```sh
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                           '-DarchetypeArtifactId=foundation-archetype' \
                           '-DarchetypeVersion=1.10.0-SNAPSHOT' \
                           '-DgroupId=org.test' \
                           '-Dpackage=org.test' \
                           '-DprojectGitUrl=test.org/test.git' \
                           '-DprojectName=Final Test 398' \
                           '-DartifactId=final-398' \
    && cd final-398
    ```
2. Set your Java version to **_17_** if it is not currently
3. Add a [Spark Pipeline model](https://github.com/user-attachments/files/17343578/PersistPipeline.json) with a step for each persist type & mode.
4. Fully generate the project by running `mvn clean install` and following manual actions
5. Unzip the [pipeline step code](https://github.com/user-attachments/files/17343590/pipelines.tar.gz) in the root of the project to add it to the pipeline. This logic passes a sample dataset between each storage format appending new data each time.
6. Build the project without the cache and follow the last manual action.
    ```sh
    mvn clean install -Dmaven.build.cache.skipCache
    ```
7. Deploy the project.
    ```sh
    tilt up; tilt down
    ```
8. Once all the resources have started (may take awhile) execute the pipeline. (It will be `persist-pipeline` in Tilt if you've used the provided model.)
9. Verify that the pipeline completes successfully.
10. Verify that a dataset was successfully written to each persistence type. _**Tip:** The logs are quite busy so filtering by "_StepBase:_" via the Tilt UI will help you find these lines much faster._
    ```sh
    ...
    24/10/11 15:35:14 INFO HiveStepBase: Saved HiveStep to Hive
    ...
    24/10/11 15:35:34 INFO DeltaLakeStepBase: Saved DeltaLakeStep to Delta Lake
    ...
    24/10/11 15:36:46 INFO Neo4jStepBase: Saved Neo4jStep to Neo4j
    ...
    24/10/11 15:36:48 INFO ElasticsearchStepBase: Saved ElasticsearchStep to Elasticsearch
    ```

### Upgrade Test
1. Create a new project on 1.9.2.
    ```sh
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                           '-DarchetypeArtifactId=foundation-archetype' \
                           '-DarchetypeVersion=1.9.2' \
                           '-DgroupId=org.test' \
                           '-Dpackage=org.test' \
                           '-DprojectGitUrl=test.org/test.git' \
                           '-DprojectName=Upgrade Test 398' \
                           '-DartifactId=upgrade-398' \
    && cd upgrade-398
    ```
2. Set your Java version to **_11_** if it is not currently
3. Add the delta-core_2.12 dependency to the root `pom.xml`
    ```diff
    ...
      <dependencies>
    +    <dependency>
    +      <groupId>io.delta</groupId>
    +      <artifactId>delta-core_2.12</artifactId>
    +      <version>2.4.0</version>
    +    </dependency>
        <!-- START: workaround to get maven build cache invalidation on new SNAPSHOTS of commonly updated plugins -->
        <dependency>
    ...
    ```
4. Add [Spark](https://github.com/user-attachments/files/17344738/SparkPipeline.json) and [Pyspark](https://github.com/user-attachments/files/17344737/PysparkPipeline.json) pipelines with a step that persists to `delta-lake`
5. Fully generate the project by running `mvn clean install` and following manual actions
6. Verify the following values files have the **delta-core** and **delta-storage** dependencies listed in `sparkApp.spec.deps.packages`:
    - _upgrade-398-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-base-values.yaml_
    - _upgrade-398-pipelines/pyspark-pipeline/src/pyspark_pipeline/resources/apps/pyspark-pipeline-base-values.yaml_
7. Update the `build-parent` version in the root `pom.xml` to **1.10.0-SNAPSHOT**
8. Update the `smallrye-reactive-messaging-kafka` dependency to look like the following within `upgrade-398-pipelines/spark-pipeline/pom.xml` (Workaround from #263 bug):
```
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-reactive-messaging-kafka</artifactId>
            <version>${version.smallrye.reactive.messaging}</version>
        </dependency>
```
9. Set your Java version to **_17_** if it is not currently
10. Run `mvn org.technologybrewery.baton:baton-maven-plugin:baton-migrate` _(install would fail with compile errors because of missing migrations for #263.)_
11. Verify the following values files have the delta jars updated to **3.2.1** and **delta-core** has been renamed to **delta-spark**:
    - _upgrade-398-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-base-values.yaml_
    - _upgrade-398-pipelines/pyspark-pipeline/src/pyspark_pipeline/resources/apps/pyspark-pipeline-base-values.yaml_
12. Verify the dependency added in step 3 has changed from **delta-core** to **delta-spark** and the _version_ is set to `${version.delta}`

**Comment by ewilkins-csi** [comment]
**DoD** with @carter-cundiff @csun-cpointe

**Comment by ewilkins-csi** [comment]
**OTS** with @csun-cpointe

**Comment by csun-cpointe** [comment]
Final tests passed!!

**Main Test Verification:**
![Screenshot 2024-10-11 at 2 17 32 PM](https://github.com/user-attachments/assets/8c0fa47b-4298-47a1-a562-cc11aa7263ff)
![Screenshot 2024-10-11 at 2 18 02 PM](https://github.com/user-attachments/assets/17083021-760d-481a-b75b-8bbb3854dfe5)

**Upgrade Test**
![Screenshot 2024-10-11 at 2 33 02 PM](https://github.com/user-attachments/assets/750ace9a-bdc1-4d1f-a094-9292d8c11b20)
![Screenshot 2024-10-11 at 2 36 01 PM](https://github.com/user-attachments/assets/590397cf-b3e8-4dcf-b1a3-ce956ff7c464)
