### ISSUE TITLE
Fix Cyclic helm tests in `test-mda-models`

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#4]
### Description

While migrating to the ghcr.io as aissemble's new helm repository, we encountered some cyclic tests in the the `test-mda-models` module.  The core issue is the `test-chart` execution of `maven-exec-plugin`, which generally looks like:
```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>test-chart</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>helm</executable>
                            <arguments>
                                <argument>template</argument>
                                <argument>aissemble-spark-application</argument>
                                <argument>--repo</argument>
                                <argument>${aissemble.helm.repo}</argument>
                                <argument>--version</argument>
                                <argument>${version.aissemble}</argument>
                                <argument>--values</argument>
                                <argument>
                                    src/aissemble_test_data_delivery_pyspark_model_basic/resources/apps/pyspark-data-delivery-basic-base-values.yaml,tests/resources/apps/pyspark-data-delivery-basic-test-values.yaml
                                </argument>
                                <argument>-s</argument>
                                <argument>templates/deployment.yaml</argument>
                            </arguments>
                            <outputFile>target/apps/pyspark-data-delivery-basic-test-chart.yaml</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
In this block, we reference a remote helm repo:
```xml
                                <argument>--repo</argument>
                                <argument>${aissemble.helm.repo}</argument>
```

Of course in the process of migrating to a new helm repo, no charts have been deployed here yet, which uncovered the cycle.  We should likely do the following:
- update to use the local version of the chart
- refactor to at least pull this up to a common `pluginDependency` definition in `test-mda-models` so it isn't repeated almost verbatim in four different modules.  More ideally, we'd eliminate the use of the `maven-exec-plugin` for this altogether as it is a generally a pretty good sign we have a workaround in place.  Since we've forked the `helm-maven-plugin`, why not support this with it?

This impacts the following four modules:
- `test-mda-data-delivery-model`
- `test-mda-data-delivery-model-basic`
- `aissemble-test-data-delivery-pyspark-model`
- `aissemble-test-data-delivery-pyspark-model-basic`

In the meantime, the `test-chart` execution has been disabled by pulling up the existing `skip-test` profile in those four modules into a common profile in `test-mda-models` and making it active by default.  There is a link to this issue on that block as well as each `test-chart` execution to help folks that might encounter it until it is fixed.  

### Definition of Done

- [x] update all four modules to use local version of chart in helm testing
- [x] Update to use helm-maven-plugin instead of maven-exec-plugin EDIT: helm-maven-plugin doesn't support changing output file name so will fall back to using maven-exec-plugin.
- [x] refactor to pull test helm logic into common pluginDependency in test-mda-models
- [x] Clean up all workaround logic to skip helm testing.
- [x] Verify mvn clean install is successful
- [x] Verify alll four modules can run helm testing upon mvn clean install

### Testing Instruction
- [ ] pull in latest build of aissemble
- [ ] Verify mvn clean install is successful
- [ ] Verify alll four modules runs testing successfully upon mvn clean install
- `test-mda-data-delivery-model`
- `test-mda-data-delivery-model-basic`
- `aissemble-test-data-delivery-pyspark-model`
- `aissemble-test-data-delivery-pyspark-model-basic`
EX) Cucumber test ran in test-mda-data-delivery-model-basic is triggered and passed

![Screenshot 2024-10-24 at 3 47 19 PM](https://github.com/user-attachments/assets/aa479540-74fc-4062-9fb3-48298842a656)
![Screenshot 2024-10-24 at 3 48 01 PM](https://github.com/user-attachments/assets/6e8ee62b-3b46-42e6-81e3-16ba0fb61725)

**Comment by cpointe-ibllanos** [comment]
I can assign this to myself once I am added to the org.

**Comment by jaebchoi** [comment]
DoD Completed with @meliz19

**Comment by jaebchoi** [comment]
OTS completed with @cwoods-cpointe

**Comment by meliz19** [comment]
Final test completed!
