### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Jenkins Images

### ISSUE THREAD

**Issue by jacksondelametter** [boozallen/aissemble#406]
## Description
In https://github.com/boozallen/aissemble/issues/133 we modified the build-parent to use JDK 17. When building aiSSEMBLE with the updated build-parent, some modules do not build successfully. This is a series of ticket to fix broken modules and verify they work correctly. This issue will focus on the Jenkins image functionality. 
## DOD
- [x] Modify the aiSSEMBLE Jenkins agent and controller to use JDK 17
- [x] Verify a successful build with the modification
- [x] Verify Jenkins can be accessed as well as the agent is using JDK 17

## Test Steps
- Clone the aiSSEMBLE repository https://github.com/boozallen/aissemble. 
- In the project's root directory, execute the following and verify successful builds
  -  `mvn clean install -pl :aissemble-jenkins -amd` Note: Make sure the aissemble-jenkins-controller and aissemble-jenkins-agent images actually build. 
  -  `mvn clean install -pl :aissemble-infrastructure-chart`
- Execute `helm install jenkins extensions/extensions-helm/aissemble-infrastructure-chart/ --values extensions/extensions-helm/aissemble-infrastructure-chart/values.yaml --set argo-cd.enabled=false,ingress-nginx.enabled=false,jenkins.controller.image.pullPolicy="IfNotPresent",jenkins.controller.serviceType=LoadBalancer`. This may take a few seconds for the Jenkins pod to initialize.
- In a browser, access Jenkins with the following URL http://localhost:8080/
  - Execute `kubectl exec --namespace jenkins -it svc/jenkins -c jenkins -- /bin/cat /run/secrets/additional/chart-admin-password && echo` to get the user `admin` password
  - Login with the `admin` username and password generated from the previous step
- Execute `docker run ghcr.io/boozallen/aissemble-jenkins-agent:1.10.0-SNAPSHOT`
- In another terminal, execute `docker ps | grep jenkins-agent`, take note of the container ID
- Execute `docker exec -it CONTAINER_ID bash`
  - In the jenkins-agent container, execute `java --version`. Verify the version is Java 17. 
  - Execute `exit` to exit out of the container 
- Execute `docker stop CONTAINER_ID`
- Execute `helm uninstall jenkins`

**Comment by cwoods-cpointe** [comment]
Final test passed. Jenkins comes up and exec shows java 17
