### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Data Access

### ISSUE THREAD

**Issue by cwoods-cpointe** [boozallen/aissemble#415]
## Description
Support for Java 11 has ended so we want to ensure aiSSEMBLE is compatible with Java 17. This ticket will focus on the Data Access modules.

## DOD
- [x] Ensure modules are compatible with JDK17
  - [x] foundation-data-access
  - [x] aissemble-data-access-chart (Uses quarkus chart and docker image)
- [x] Ensure downstream Data Access modules are JDK17 compatible
  - [x] Generated code
  - [x] Generate data-access Dockerfile
- [x] Downstream Data Access can be deployed and retrieve data

## Test Strategy/Script
- Create a downstream project
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.10.0-SNAPSHOT \
                          -DartifactId=test-project\
                          -DgroupId=org.test \
                          -DprojectName='Test' \
                          -DprojectGitUrl=test.org/test-project \
&& cd test-project
```
- Copy the resource folder into the pipeline models
  - [415-helper.zip](https://github.com/user-attachments/files/17415552/415-helper.zip)
- Build and resolve all manual actions
- Update the PersistData.java file in test-project-pipelines/spark-pipeline and build again
  - [415-helper.zip](https://github.com/user-attachments/files/17415552/415-helper.zip)
- Deploy the app with `tilt up`
- Verify Data Access successfully deploys
- Verify its using JDK 17
  - kubectl exec -it {pod} -- bash
  - java --version
- Run the pipeline
- Verify Data Access can successfully fetch data
  - Query url - `localhost:8081/graphql`
  - Query body - `query test {Person(table: "Person") {name}}`

## References/Additional Context
N/A

**Comment by cwoods-cpointe** [comment]
DoD completed with @ewilkins-csi

**Comment by chang-annie** [comment]
all tests steps are passing!
- created downstream project and copied resource folder into pipeline models
- built and resolved all manual actions
- updated `PersistData.java` file and built again
- tilted up
- verified data access successfully deploys
- verified data access is using jdk17
- ran spark pipeline and verified data access can successfully fetch data
