### ISSUE TITLE
Feature: JDK17 Upgrade Series: Data and Model Lineage

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#421]
## Description
In #133  we modified the core libraries t to use JDK 17. As part of upgrade to java 17 series, this ticket will focus on the data and model lineage functionality.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Upgrade data and model lineage to build with Java 17:
   - [x] Ensure all modules are compatible with java 17
      - [x] aissemble-nvidia
      - [x] foundation-lineage
         - [x] foundation-modle-lineage
         - [x] foundation-data-lineage-python
         - [x] foundation-data-lineage-consumer
         - [x] foundation-data-lineage-java
      - [x] extensions-data-lineage-http-consumer-service
      - [x] extensions-data-lineage-http-consumer
   - [x] Clean up pom to remove unnecessary dependencies
   - [x] Data lineage functionalities work as expected
      - [x] Spark Pipeline can send data-lineage message
      - [x] Model Training pipeline can send model-lineage message

## Test Strategy/Script
1. Using create a new aissemble-based project using the latest archetype snapshot.
```
mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                           '-DarchetypeArtifactId=foundation-archetype' \
                           '-DarchetypeVersion=1.10.0-SNAPSHOT' \
                           '-DgroupId=org.test' \
                           '-Dpackage=org.test' \
                           '-DprojectGitUrl=test.org/test.git' \
                           '-DprojectName=Final Test 421' \
                           '-DartifactId=test-421' \
    && cd test-421
```
2. Set your Java version to **_17_** if it is not currently
3. Under -model/src/main/resources/pipelines add both [ClassificationTraining.json](https://github.com/user-attachments/files/17482480/ClassificationTraining.json) and [SparkPipeline.json](https://github.com/user-attachments/files/17482481/SparkPipeline.json)
 files
4. Add below execution to the -deploy/pom.xml
```
                     <execution>
                        <id>lineage-http-consumer</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                        <configuration>
                            <basePackage>com.boozallen.aissemble.documentation</basePackage>
                            <profile>lineage-http-consumer-deploy-v2</profile>
                            <!-- The property variables below are passed to the Generation Context and utilized to customize the deployment artifacts. -->
                            <propertyVariables>
                                <appName>lineage-http-consumer-deploy-v2</appName>
                            </propertyVariables>
                        </configuration>
                    </execution>
```
5. Fully generate the project by running `mvn clean install` and following manual actions
6. Unzaip [marquez.zip](https://github.com/user-attachments/files/17482510/marquez.zip) and copy the `marquez` folder to the `test-421-deploy/src/main/resources/apps/` directory
7. Unzip the [marquezHelper.zip](https://github.com/user-attachments/files/17482524/marquezHelper.zip) and place the content under the `test-421` root directory
8. Uncomment the `mp.messaging.outgoing.lineage-event-out.*` configuration in the `-pipelines/spark-pipeline/src/main/resources/META-INF/microprofile-config.properties` file
9. Build the project without the cache and follow the last manual action.
    ```sh
    mvn clean install -Dmaven.build.cache.skipCache
    ```
10. Run `sh ./marquez_setup_helper.sh` at the root directory
11. Deploy the project and wait for all services ready
    ```sh
    tilt up; tilt down
    ```
12. Manually trigger the `spark-pipeline pod`, make sure all steps run completely without any error
13. Use postman or any rest client to trigger the training pipeline and verify a successful training pipeline id responded
    - Url : http://localhost:5001/training-jobs?pipeline_step=logistic-training
    - Method: Post
    - Body: {}
14. Copy the responded service id and run below command to verify the log without any errors. e.g.: `kubectl logs job.batch/"model-training-logistic-tr-24cd1662-5b62-4e3c-946f-6b9081e30017"`
```
kubectl logs job.batch/<PASTE OUTPUT>
```
15. Use Marquez (http://localhost:3000/events) to verify the lineage start and complete events are generated for both `spark-pipeline` and `ClassificationTraining`
![Screenshot 2024-10-23 at 7 50 17 AM](https://github.com/user-attachments/assets/318f9661-b517-4796-a47a-ea5181b01e15)

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi and @carter-cundiff

**Comment by carter-cundiff** [comment]
OTS passed

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/a007b406-2e53-4e77-8a24-6db7e1839db0)
