### ISSUE TITLE
BUG: Pyspark pipeline generates duplicated data records under pipeline with combine records

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#422]
## Description
When creating the pyspark pipeline project with combine records, the data records are generated under both `-pipelines/py-spark-pipeline` and the `-share` directories.

The same issue is also seen when generate the pyspark project with split data records.

## Steps to Reproduce
1. Create a new project on 1.10.0-SNAPSHOT.
    ```sh
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                           '-DarchetypeArtifactId=foundation-archetype' \
                           '-DarchetypeVersion=1.10.0-SNAPSHOT' \
                           '-DgroupId=org.test' \
                           '-Dpackage=org.test' \
                           '-DprojectGitUrl=test.org/test.git' \
                           '-DprojectName=Test combine records' \
                           '-DartifactId=test-combine-records' \
    && cd test-combine-records
    ```
2. Set your Java version to **_17_** if it is not currently
3. Unzip the [resources.zip](https://github.com/user-attachments/files/17437831/resources.zip) and replace the resources folder at the `-pipeline-models/src/main/` directory
4. Fully generate the project by running `mvn clean install` and following manual actions
5. Unzip the [krausening.zip](https://github.com/user-attachments/files/17437772/krausening.zip) and replace the krausening folder at the `-docker/test-combine-record-spark-worker-docker/src/main/resources` directory
7. Build the project without the cache and follow the last manual action.
    ```sh
    mvn clean install -Dmaven.build.cache.skipCache
    ```

## Expected Behavior
There should be no data records generated under the `-pipelines/py_spark_pipeline` directory

## Actual Behavior
The data records are generated under both `-pipelines/py_spark_pipeline` and `-shared` directories
Note: the same issues not be seen in the spark pipeline

## Definition of Done

- [x] Fix MDA to make sure data records should only generated under '-shared' directories.
- [x] make sure aissemble build is successful.
- [x] Make sure downstream project with pyspark pipeline can be stood up without any error.

## Testing Instructions

- [x] fetch latest dev branch of aissemble
- [x] do mvn clean install
- [x] Create a new project on 1.10.0-SNAPSHOT.
    ```
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                           '-DarchetypeArtifactId=foundation-archetype' \
                           '-DarchetypeVersion=1.10.0-SNAPSHOT' \
                           '-DgroupId=org.test' \
                           '-Dpackage=org.test' \
                           '-DprojectGitUrl=test.org/test.git' \
                           '-DprojectName=Test combine records' \
                           '-DartifactId=test-combine-records' \
    && cd test-combine-records
    ```
- [x] Set your Java version to **_17_** if it is not currently
- [x]  Unzip the [resources.zip](https://github.com/user-attachments/files/17779341/resources.zip)  and replace the resources folder at the `-pipeline-models/src/main/` directory
- [x] Fully generate the project by running `mvn clean install` and following manual actions
- [x] Unzip the [krausening.zip](https://github.com/user-attachments/files/17437772/krausening.zip) and replace the krausening folder at the `-docker/test-combine-record-spark-worker-docker/src/main/resources` directory
- [x]  Build the project without the cache and follow the last manual action
    ```
    mvn clean install -Dmaven.build.cache.skipCache
    ```
- [x] Check to make sure `-pipelines/pyspark_pipeline` directory doesn't have record code generated
it should include something like this:pyspark_pipeline package doesn't have dictonary or records directory.

<img width="418" alt="Screenshot 2024-11-19 at 4 47 36 PM" src="https://github.com/user-attachments/assets/3b6300db-49cd-4e54-b143-3987001162b0">

- [x] Check to make sure `-shared` directory  have record code generated

it should include something like this: shared package has dictonary and records directory.
<img width="414" alt="Screenshot 2024-11-19 at 4 48 15 PM" src="https://github.com/user-attachments/assets/9dfad90f-cb1f-412a-919a-e7d78404d1bc">

## Additional Context
This can be a documentation error. In the [semantic-data.html](https://boozallen.github.io/aissemble/aissemble/current/semantic-data.html), we can also instruction user to use the `data-delivery-pyspark-pipeline` profile in the `-pipeline/pom.xml` file. However, the issue not seeing in the spark-pipeline

**Comment by jaebchoi** [comment]
DOD Completed with @meliz19

**Comment by jaebchoi** [comment]
OTS Completed with @aaron-gary

**Comment by cwoods-cpointe** [comment]
Final test completed. Only seeing the records being generated in the shared
