### ISSUE TITLE
Feature: JDK 17 Upgrade Support Series - Remove Service Discovery 

### ISSUE THREAD

**Issue by jacksondelametter** [boozallen/aissemble#423]
## Description
The Service Discovery module is not being used in aiSSEMBLE. The module should be remove from the repository. 

## DOD
- [ ] Remove the foundation-service-discovery module from the aiSSEMBLE repository
- [ ] Remove all references to the Service Discovery module

## Test Strategy/Script
- Clone the aissemble repository (https://github.com/boozallen/aissemble). 
- In the project, verify the module **foundation/foundation-service-discovery** does not exist. 
- Verify all references to **foundation-service-discover** and **Service Discovery** do not exist using any appropriate search tool. Note: there will be a reference to **Service Discovery** in the Draft Release Notes that you can ignore.

**Comment by cpointe-ibllanos** [comment]
Was able to confirm this change.
