### ISSUE TITLE
Feature: Upgrade Drift Detection to Java 17

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#426]
## Description
Follow on to #133, where we want to migrate our whole repository to java 17. This issue will focus on migrating drift detection module to enable it within downstream projects.

## DOD
- [x] Update the following submodules to build with JDK 17 and ensure all tests pass
  - [x] foundation-drift-detection
  - [x] foundation-drift-detection-client-java
  - [x] foundation-drift-detection-core-java
  - [x] foundation-drift-detection-engine
  - [x] foundation-drift-detection-service 
- [x] Clean up pom files from the above modules to remove unnecessary dependencies and add undeclared transient dependencies 
  - [x] Use mvn dependency:analyze 

## Test Strategy/Script
- Go to GitHub Actions https://github.com/boozallen/aissemble/actions.
- Verify aiSSEMBLE build 307 passed.

**Comment by cpointe-ibllanos** [comment]
Confirmed over-the-shoulder
