### ISSUE TITLE
Feature: Build action should re-use the docker build cache

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#429]
## Description
We save the m2 repository, the maven build cache, and the poetry cache to GitHub caches so we can re-use them across builds. We should also do this with the docker build cache at `~/.docker/cache`.  Note that we are already consuming over the 10GB limit for GH caches.  The docker build cache is expected to be over 5GB and so could cause issues with our caches being purged too aggressively.  There will be a [feature early next year](https://github.com/orgs/community/discussions/42506#discussioncomment-10388640) to allow open source projects to pay for increased cache limits. Further, there is an [action available](https://github.com/marketplace/actions/fast-actions-cache-for-s3) that is a one-to-one replacement for the official cache action that allows writing to S3.

However, on further discussion, we realized that our current pattern of segregating the maven and poetry caches based on the contents of the projects POM files is unnecessary and causing a lot of excess cache usage.  If we remove this segregation and just use a constant cache, our cache usage should drop to 6GB.  This may be enough that we can get by floating right at the limit. So for the first pass at this, we'll just trim back our other cache usage and see if it becomes an issue. If it does, we can explore the options listed above.

## DOD
Acceptance criteria required to realize the requested feature
- [x] the `build.yaml` workflow is updated to create/use a `docker-cache` GH cache to prevent full docker image rebuilds
- ~the `build.yaml` workflow is updated to save the m2 repo, maven build cache, and poetry cache to a constant cache name~
  - This is not possible, as GH actions [does not allow](https://github.com/actions/toolkit/issues/505) a cache key to be updated
- [x] the `build.yaml` workflow is updated to use the `install-dependencies` reusable action to install necessary build tools
  - Note, we added the `install-dependencies` action in #3, but failed to use it in the build workflow as well

## Test Strategy/Script
1. Examine the logs for the most recent build
2. Verify there are stages for restoring the Docker cache and saving the Docker cache
3. Verify the "Install dependencies" action is used instead of individual steps for installing Java/Python/Helm/etc.
4. Ensure a cache named `docker-cache-*` is in [GH caches](https://github.com/boozallen/aissemble/actions/caches)

**Comment by ewilkins-csi** [comment]
**DOD/OTS** with @csun-cpointe

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/70d2bc13-8885-4a2b-b3a5-6554325ba18f)
![image](https://github.com/user-attachments/assets/326b5d58-e0f5-46aa-8f65-d34cae392676)
