### ISSUE TITLE
BUG: Delta Spark migrations fail for some YAML & POM files

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#442]
## Description
The migration to update YAML files with the new `delta-spark` dependencies as part of the Java 17 upgrade does not gracefully handle YAML files that do not have maps/objects as their root. (I.e. a YAML file which is a list.)

## Steps to Reproduce
1. Create a new project from the 1.10.0-SNAPSHOT archetype
2. Add a yaml file that is a list, e.g.:
    ```yaml
    - name: test1
      desc: "A test item"
    - name: test2
      desc: "Another test item"
    ```
3. Run the build: `mvn clean install`

## Expected Behavior
The migration should simply skip the inapplicable YAML file and finish successfully.

## Actual Behavior
The build fails at the root project.

## Additional Context
Error:
```
Execution default of goal org.technologybrewery.baton:baton-maven-plugin:1.1.1:baton-migrate failed: Could not complete migrations!: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
```
Stack trace:
```
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
    at com.boozallen.aissemble.upgrade.util.YamlUtils.loadYaml (YamlUtils.java:46)
    at com.boozallen.aissemble.upgrade.migration.v1_10_0.DeltaSparkYamlMigration.shouldExecuteOnFile (DeltaSparkYamlMigration.java:38)
    at org.technologybrewery.baton.AbstractMigration.execute (AbstractMigration.java:73)
    at org.technologybrewery.baton.BatonMojo.performMigration (BatonMojo.java:226)
    at org.technologybrewery.baton.BatonMojo.execute (BatonMojo.java:180)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
```

## Definition of Done
 - Following the steps to reproduce causes the expected behavior
 - The NPE caused by a missing `dependenciesManagement` section during the `DeltaSparkPomMigration` no longer occurs

## Test Steps
1. Create a new project from the 1.10.0-SNAPSHOT archetype
2. Add a yaml file that is a list, e.g.:
    ```yaml
    - name: test1
      desc: "A test item"
    - name: test2
      desc: "Another test item"
    ```
3. Update the root _pom.xml_ to remove the `dependencyManagement` section and add the following to the `dependencies` section:
    ```xml
        <dependency>
          <groupId>io.delta</groupId>
          <artifactId>delta-core_2.12</artifactId>
          <version>2.4.0</version>
        </dependency>
    ```
4. Run the build: `mvn clean install`
5. Validate that the build completes successfully
6. Validate that the `delta-core` dependency has been updated to `delta-spark` in the root _pom.xml_

**Comment by ewilkins-csi** [comment]
**OTS/DoD** with @carter-cundiff

**Comment by csun-cpointe** [comment]
Test passed!!

**Verified build success**
![Screenshot 2024-10-28 at 3 43 15 PM](https://github.com/user-attachments/assets/c6135850-c93b-4031-a56b-70be5df78f22)

**Verified `delta-core` dependency has been updated to `delta-spark` in the root `pom.xml`**
![Screenshot 2024-10-28 at 3 43 57 PM](https://github.com/user-attachments/assets/5a837f33-28ff-4d44-ad0d-b1542dc014c7)
