### ISSUE TITLE
Fix incorrect service name reference in generated ingress for Spark History Server

### ISSUE THREAD

**Issue by tianliang0038** [boozallen/aissemble#45]
[PysparkPipeline.json](https://github.com/boozallen/aissemble/files/15311001/PysparkPipeline.json)

**Context:**
  In our Spark infrastructure chart, which powers the Spark History Server, we create both an Ingress and a Service. The default configuration shows that the Ingress is set to target a Service called "spark-history." However, in the service.yaml template, the reference is hard-coded to "spark-infrastructure," which is incorrect for the Spark History Server.

If we test if ingress works by calling curl command `curl spark-history.p.uip.sh`, an error would pop up
`Could not resolve host: spark-history.p.uip.sh`
when we check ingress by running `kubectl describe ingress spark-infrastructure `
we'll get `spark-history:18080 (<error: endpoints "spark-history" not found>)` error.

**DOD**
1. Reproduce the error:
- Set up a pipeline containing a Spark application
- Run `tilt up` and wait till spark-infrastructure successfully runs
- Execute the command ` kubectl describe ingress spark-infrastructure `

2. Rectify the problem by modifying the `ingress.hosts.host.paths.backend.service.name` from "spark-history" to "spark-infrastructure".

**Test**
1. Pull the latest baseline project
2. Run
`mvn clean install -f foundation/foundation-mda`
3. Build a Pyspark pipeline
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.7.0-SNAPSHOT \
                          -DartifactId=test-ingress-svc\
                          -DgroupId=org.test \
                          -DprojectName='Test Ingress Service Functionning' \
                          -DprojectGitUrl=test.org/test-ingress-svc\
&& cd test-ingress-svc
```
4. Add the attached PysparkPipeline.json to <YOUR-PIPELINE-NAME>-pipeline-models/src/main/resources/pipelines
5. Run the following:
`mvn clean install`
6. Follow the manual action and then run till there's no more manual action updates popping up
`mvn clean generate-sources`
7. Remove `deployment.ingress.metadata.annotations` in `values.yaml`. Add `deployment.ingress.metadata.name` with value `ingress`. Change value of deployment.ingress.hosts.host to `spark-history.rancher.localhost`
 The deployment.ingress section should look like
{code}
ingress:
    enabled: true
    metadata: 
      name: ingress
    hosts:
      - host: spark-history.rancher.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spark-infrastructure
                port:
                  number: 18080
{code}

8. Run {code} Tilt up {code} and wait till spark-infrastructure pod successfully spins

9. Enter http://spark-history.rancher.localhost in the browser. (try chrome first, if not Firefox or safari)
11. Verify that it's error free (not 404)

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/boozallen/aissemble/assets/129905339/1377d116-1635-46f8-97c3-5127122cb567)
