### ISSUE TITLE
BUG: Update `booz-allen-licenses` to latest release for improved linting of header content

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#452]
Add the fix in https://github.com/boozallen/booz-allen-maven-licenses/issues/5 to aissemble by default.

## Test Steps:
- Ensure that `booz-allen-licenses` dependency in `build-parent/pom.xml` is:
```
<dependency>
    <groupId>com.boozallen.aissemble</groupId>
    <artifactId>booz-allen-licenses</artifactId>
    <version>1.2.1</version>
</dependency>
```
- Validate the last CI build passed

**Comment by jacksondelametter** [comment]
All tests passed!
