### ISSUE TITLE
Feature: Write build caches to S3

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#461]
## Description
In #429 we started saving the Docker build cache during the build workflow.  We discussed that the size of the Docker cache may end up causing issues and it has.  Because it's ~9GB, the docker cache will often cause all other caches to be purged and, at least once, has failed to save seemingly due to its size.  In addition, it takes about 9.75 mins to save the cache to GH caches.  We should go ahead and implement the Runs-On [S3 fast cache action](https://github.com/boozallen/aissemble/issues/429#:~:text=there%20is%20an-,action%20available,-that%20is%20a) to get around these issues.

## DOD
- [x] The build workflow authenticates with AWS and writes caches to S3
- [x] The S3 bucket is configured to delete objects a day after their creation
    - We could instead use the AWS authentication to delete the caches during the build itself, but that requires more permissions on S3 and is less straight-forward to implement

## Test Strategy/Script
1. View the latest build and verify the cache actions are from the `runs-on/cache` action
2. Confirm the caches saved to AWS are < 1 day old

**Comment by ewilkins-csi** [comment]
**DoD/OTS** with @csun-cpointe and @carter-cundiff

**Comment by csun-cpointe** [comment]
Test passed!
**Confirm the caches saved to AWS are < 1 day old**
![Screenshot 2024-11-08 at 11 44 28 AM](https://github.com/user-attachments/assets/4259bee6-ad78-4d4d-871b-5776cece81a1)
![Screenshot 2024-11-08 at 11 44 06 AM](https://github.com/user-attachments/assets/e75ee66b-a0ce-43c2-a4e9-42e6f5d39adf)
![Screenshot 2024-11-08 at 11 43 45 AM](https://github.com/user-attachments/assets/58743715-9005-4250-a685-a3412a3fa5a4)
![Screenshot 2024-11-08 at 11 43 33 AM](https://github.com/user-attachments/assets/9d51f86f-a761-4fee-a549-210c015e33d1)
![Screenshot 2024-11-08 at 11 40 40 AM](https://github.com/user-attachments/assets/2536c374-3034-40fa-a123-6fae5133727f)

**View the latest build and verify the cache actions are from the runs-on/cache action**
<img width="1137" alt="Screenshot 2024-11-08 at 11 38 33 AM" src="https://github.com/user-attachments/assets/14921e28-d66c-4746-a2e5-bfa42f324d8e">
<img width="1139" alt="Screenshot 2024-11-08 at 11 37 43 AM" src="https://github.com/user-attachments/assets/b5fff699-8270-48c4-a962-5a31e6986513">
<img width="1133" alt="Screenshot 2024-11-08 at 11 37 32 AM" src="https://github.com/user-attachments/assets/f2c0e8d6-e9d5-4207-abcf-cafc3b290705">
<img width="1134" alt="Screenshot 2024-11-08 at 11 37 00 AM" src="https://github.com/user-attachments/assets/4eec5125-6a56-466c-b4f5-b349bbfaadd5">
<img width="1136" alt="Screenshot 2024-11-08 at 11 36 53 AM" src="https://github.com/user-attachments/assets/1b2813f2-a0f0-4d96-800b-0c8f15b84c30">
