### ISSUE TITLE
Feature: Document the setup of custom GitHub action runners that can execute the aiSSEMBLE build.

### ISSUE THREAD

**Issue by ewilkins-csi** [boozallen/aissemble#467]
## Description
Our build has been failing recently due to disk pressure on the cluster that hosts our GHA runners.  During the process of expanding the disk size for the cluster, the [ARC](https://github.com/actions/actions-runner-controller) deployment responsible for provisioning runners on-demand for aiSSEMBLE stopped working.  It has been restored, but we should document the setup process and any caveats so that we can easily redeploy ARC for aiSSEMBLE if/when we need to.

## DOD
- [x] There is information in the `devops` directory of the repository that outlines ARC setup

## Test Strategy/Script
- Verify the README exists and describes the setup process
- Verify the latest build is passing

## References/Additional Context
We could create a chart for deploying ARC in a compatible way, but the focus of this ticket is largely to get the CI build working again so we can continue with normal operations.

**Comment by ewilkins-csi** [comment]
**DoD/OTS** with @csun-cpointe

**Comment by csun-cpointe** [comment]
Test passed!
**ARC ReadMe**
![Screenshot 2024-11-14 at 10 56 50 AM](https://github.com/user-attachments/assets/d30f6663-74c0-46f3-8fa9-815aac46d814)

**Latest Build Success**
![Screenshot 2024-11-14 at 10 57 28 AM](https://github.com/user-attachments/assets/c04d323c-473a-49a7-86c9-0ac217359653)
