### ISSUE TITLE
Retrieve configurations through configuration service with its relevant environment context

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#47]
[47Helper.zip](https://github.com/boozallen/aissemble/files/15355422/47Helper.zip)

**DOD**
- ensure that the Config Service can respond to a rest call to get a value
- create a docker image to house the service (also enables demo)
   - can build from the aissemble-quarkus docker image
   - implement startup script that does the following:
      - starts up the REST endpoint
      - calls on the config loader to load initial configurations

**BDD Scenario:**
```
Scenario: configuration service returns the configuration value
    Given configuration service starts
     When requests a configuration property
     Then configuration value is returned
```

**Technical Notes**
- do not need worry about the ConfigServiceClient
- do not need to worry about Helm Chart

**Test Steps:**

- **OTS Only:**

```
mvn clean install -pl :foundation-configuration-store  
mvn clean install -pl :aissemble-configuration-store-service 
```
- Run `mkdir test-issue-47 && cd test-issue-47`
- Unzip the attached 47Helper.zip file
- Place the docker-compose.yaml file in the `test-issue-47` directory
- Run `mkdir resources && cd resources`
- Place the configurations folder in the resources directory
- At the test-issue-47 root directory, run `docker-compose up`
- Verify the log that all yaml files are loading
- Verify http://localhost:8080/aissemble-properties/model-training-api/AWS_SECRET_ACCESS_KEY returns the property.

**Comment by ewilkins-csi** [comment]
**DoD** looks good ✅

**Comment by ewilkins-csi** [comment]
OTS test passed ✅

**Comment by tianliang0038** [comment]
The ticket auto closed. Reopened it and close again upon walking through test steps
