### ISSUE TITLE
Feature: Publish aggregated Cucumber report from cucumber-report-aggregator

### ISSUE THREAD

**Issue by habibimoiz** [boozallen/aissemble#474]
## Description
As part of [#447](https://github.com/boozallen/aissemble/issues/447) was to generate an aggregated report of the Cucumber tests for the entire aiSSEMBLE report. The next objective is to take the generated report and publish that to a public site such that the report can be accessible outside of aiSSEMBLE. Currently, the aggregated report is generated locally in the /target directory under /cucumber-reports/cucumber-html-reports/overview-features.html. Theoretically, this local HTML directory can be published.

### Approach 1: GitHub Pages (peaceiris)
Upon doing research, the [gh-actions-pages](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#getting-started) plugin from [peaceiris](https://github.com/peaceiris) appears to be a promising approach. This is a GitHub Action to deploy your static files to GitHub Pages. This deploy action can be combined simply and freely with [Static Site Generators](https://jamstack.org/generators/). (Hugo, MkDocs, Gatsby, mdBook, Next, Nuxt, and so on).

We can potentially use the [Deploy to Subdirectory destination_dir](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-deploy-to-subdirectory-destination_dir) option from their plugin to get the aggregated Cucumber report deployed to GitHub Pages.

### Approach 2: Explore the option on Publishing to Cucumber.io
Explore the ability to see if Cucumber allows an already generated report to be pushed to Cucumber.io; contact Cucumber support to see the possibility. 

### Approach 3: GitHub Pages (Jameslves)
Upon doing research, using the [github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) plugin from [Jameslves](https://github.com/JamesIves) appears to be an alternate approach to [gh-actions-pages](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#getting-started) plugin. The same concerns exist with the use of this plugin. The only thing that stands out with this plugin however is the parallel use of our Antora docs with this. 

### Approach 4: Spin up new GitHub branch (i.e. `gh-pages`) and upload the aggregated cucumber report there
Spin up a new branch called `gh-pages`. The aggregated Cucumber report will live in here. From there, we will configure GitHub pages to read from this branch. By doing it this way, we can view both the Antora docs (aiSSEMBLE) docs in one GitHub Pages environment without any conflict.  

#### Questions / Concerns
C: The aggregated report is generated every time the :cucumber-report-aggregator is ran. If the publishing happens in the CI build and then deployed to GitHub pages, will GitHub pages store the directory locally, or will it point to a target directory? If it does point to the target directory, this will fail. In this case, we will need to checkin the HTML directory such that the GitHub pages has a something concrete to point to.

C: By using GitHub pages, we have to ensure that the aiSSEMBLE docs are not disturbed. 

## DOD
Acceptance criteria required to realize the requested feature
- [x] Identify a solution to publish the aggregated Cucumber report to a publicly accessible site. 
- [x] Implement determined approach and publish the cucumber report. 
- [ ] ~~Update the [README.md](https://github.com/boozallen/aissemble/blob/dev/README.md) to link to the aggregated Cucumber report.~~

## Test Strategy/Script
**Test 1: View the `cucumber-html-reports` repo in the _new_ `gh-pages` branch.** 
- Step 1: Navigate to the [gh-pages](https://github.com/boozallen/aissemble/tree/gh-pages) branch.
- Step 2: Verify that there is a repo called `test-reports`.

**Test 2: Verify when CI runs, it doesn't override files, rather only updates the `test-reports` repo.**
- Step 1: Navigate to the [gh-pages](https://github.com/boozallen/aissemble/tree/gh-pages) branch.
- Step 2: Verify that there is a repo called `test-reports`.
- Step 3: Verify there is a file named `test.txt` and it has NOT been override (timestamp doesn't line up with `test-reports` modify date.

## References/Additional Context
- [GitHub Actions for GitHub pages](https://github.com/peaceiris/actions-gh-pages/blob/main/README.md)

**Comment by habibimoiz** [comment]
**Update:** There has been some complications with trying to deploy the aggregated cucumber report to GitHub Pages along side the Antora docs (aiSSEMBLE docs) by just using the stand alone [gh-actions-pages](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#getting-started) from [peaceiris](https://github.com/peaceiris). There are hand full of issues that we have to consider, some of them including the fact that the respective repos will write over each other and defeat the purpose of this ticket. The best option for accommodating both of these GitHub Pages instances is to spin up a `gh-pages` branch and leverage that. The only issue with that currently is that the Antora docs currently use the GitHub Actions to deploy the aiSSEMBLE docs to GitHub Pages. The solution that we will continue with is to deploy the aggregated cucumber report to this `gh-pages` branch and then create a follow-on issue that will switch over the aiSSEMBLE docs to push to the `gh-pages` branch and sunset the use of GitHub Actions for its deployment.

**Comment by chang-annie** [comment]
Final tests all passing! Verified new `gh_pages` branch and confirmed that reports do not override the `test.txt` file
