### ISSUE TITLE
Feature: Leverage build cache to accelerate development and test cycles

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#482]
## Description
Currently, when creating downstream project with cache, after resolving all `Manual Actions`, we still need to build one more time without cache in order to, first, prompt one last Manual Action and, second, make sure the `-spark-worker-docker` modules' target is built with correct files. 
The reason for the missing target files is because when we do `mvn clean install` the `clean` phase will remove the `target` folder but because no changes in the `-docker-module` or `-deploy` module, the execution will not run for the `copy-pipeline-artifacts` or `copy-resources` command because of cache, which results in the missing files in the `target` folder. This issue has slowed down our development/test cycles and this ticket specifically is to address the `-docker-module` build cache issue.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Fix the docker module incorrect built target issue
- [x] Enable docker image build for ArgoCD
- [x] Remove the Manual Action for the docker_build() and local_resource() in the Tiltfile?
- [x] Update release note for enabled the docker build in the maven build process
--- Stretch Goal ---
- [ ] Figure out how to show `Manual Action` when the build cache is used.

## Test Strategy/Script
How will this feature be verified?

**Test Cache/Docker Build**
Make sure archetype test passes thru without copying maven-build-cache-config.xml and the extensions.xml
1. Open the base `-foundation/foundation-archetype/test-project-archetype.sh` file and make sure there is no copying `maven-build-cache-config.xml` and the `extensions.xml` in the script
2. Run `./mvnw -B clean install -Parchetype-test -pl :foundation-archetype` and ensure the build is successful.
3. Run `docker images` to ensure that `test-generator-spark-worker-docker:1.0.0-SNAPSHOT ` and `test-generator-policy-decision-point-docker:1.0.0-SNAPSHOT` is present in the images list
**Note**: the successful docker image build represents cache is used correctly and there is no missing files in the build result.

**Migration**
1. Create a downstream project with release 1.10.0
   ```
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                       '-DarchetypeArtifactId=foundation-archetype' \
                       '-DarchetypeVersion=1.10.0' \
                       '-DgroupId=org.test' \
                       '-Dpackage=org.test' \
                       '-DprojectGitUrl=https://github.com/csun-cpointe/test-migration.git' \
                       '-DprojectName=Test Project' \
                       '-DartifactId=test-migration'
   ```
and Include the [PysparkPipeline.json](https://github.com/user-attachments/files/18157469/PysparkPipeline.json) and [SparkPipeline.json](https://github.com/user-attachments/files/18157470/SparkPipeline.json) to the `pipeline-models/src/main/resources/pipelines` folder

2. Run `mvn clean install` 
3. Resolve the first manual action and run `mvn clean install` again.
4. Verify spark worker image is configured with the `latest` tag in the `pyspark-pipeline` and `spark-pipeline` values templates:
e.g.: `-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-base-values.yaml` and `-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-debug-values.yaml`. 
```
image: "...test-migration-spark-worker-docker:latest"
```
5. Verify the fabric8 `docker-maven-plugin` is configured with `skip` tag in the -docker/pom.xml
6. Verify the pipeline dependency type is `pom` in the `-docker/test-migration-spark-worker-docker/pom.xml`. e.g.:
```
<dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>spark-pipeline</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>pyspark-pipeline</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
        </dependency>
```
7. Update the baseline version to `1.11.0-SNAPSHOT` in the root `pom.xml`
8. Run `mvn org.technologybrewery.baton:baton-maven-plugin:baton-migrate`
9. Verify spark worker image is updated with the `1.0.0-SNAPSHOT` tag in the `pyspark-pipeline` and `spark-pipeline` values templates:
e.g.: `-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-base-values.yaml` and `-pipelines/spark-pipeline/src/main/resources/apps/spark-pipeline-debug-values.yaml`. 
```
image: "...test-migration-spark-worker-docker:1.0.0-SNAPSHOT"
```
10. Verify the fabric8 `docker-maven-plugin` has no with `skip` configuration in the -docker/pom.xml
11. Verify the pipeline dependency type is updated in the `-docker/test-migration-spark-worker-docker/pom.xml`. e.g.:
```
<dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>spark-pipeline</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>pyspark-pipeline</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
```

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi

**Comment by csun-cpointe** [comment]
OTS completed with @carter-cundiff

**Comment by epwilkins** [comment]
**✅ Test Cache/Docker Build**
1. ✅ Open the base `foundation/foundation-archetype/test-project-archetype.sh` file and make sure there is no copying `maven-build-cache-config.xml` and the `extensions.xml` in the script
2. ✅ Run `./mvnw -B clean install -Parchetype-test -pl :foundation-archetype` and ensure the build is suc
    <img width="802" alt="Screenshot 2024-12-16 at 4 57 03 PM" src="https://github.com/user-attachments/assets/7c78a3db-f0f0-4e38-a24c-1c99555ab58b" />
cessful.
3. ✅ Run `docker images` to ensure that `test-generator-spark-worker-docker:1.0.0-SNAPSHOT ` and `test-generator-policy-decision-point-docker:1.0.0-SNAPSHOT` is present in the images list
    <img width="660" alt="Screenshot 2024-12-16 at 4 57 37 PM" src="https://github.com/user-attachments/assets/fbbc2f68-98ab-4808-803a-8cc5104a62ac" />

**✅ Migration**
1. ✅ Create a downstream project with release 1.10.0
   ```
    mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                       '-DarchetypeArtifactId=foundation-archetype' \
                       '-DarchetypeVersion=1.10.0' \
                       '-DgroupId=org.test' \
                       '-Dpackage=org.test' \
                       '-DprojectGitUrl=https://github.com/csun-cpointe/test-migration.git' \
                       '-DprojectName=Test Project' \
                       '-DartifactId=test-migration'
   ```
2. ✅ Run `mvn clean install` 
3. ✅ Resolve the first manual action and run `mvn clean install` again.
4. ✅ Verify spark worker image is configured with the `latest` tag in the `pyspark-pipeline` and `spark-pipeline` values templates:
    <img width="807" alt="Screenshot 2024-12-16 at 4 06 09 PM" src="https://github.com/user-attachments/assets/9f8fc54c-ddaf-4db1-9aca-1bd998206173" />
    <img width="807" alt="Screenshot 2024-12-16 at 4 06 56 PM" src="https://github.com/user-attachments/assets/9b80c314-0210-4403-bad8-9cd6c93d3399" />
    <img width="807" alt="Screenshot 2024-12-16 at 4 08 03 PM" src="https://github.com/user-attachments/assets/3e5b7baf-20d6-41f2-8c50-cde7f3e09f61" />
    <img width="807" alt="Screenshot 2024-12-16 at 4 08 26 PM" src="https://github.com/user-attachments/assets/9ef1b39d-6814-4570-a59d-1fa0be0a80a2" />
5. ✅ Verify the fabric8 `docker-maven-plugin` is configured with `skip` tag in the -docker/pom
    <img width="407" alt="Screenshot 2024-12-16 at 4 09 54 PM" src="https://github.com/user-attachments/assets/c8236e42-7645-4abe-8f11-52a8d855a2fe" />
.xml
6. ✅ Verify the pipeline dependency type is `pom` in the `-docker/test-migration-spark-worker-docker/pom.xml`. e.g.:
    <img width="483" alt="Screenshot 2024-12-16 at 4 10 50 PM" src="https://github.com/user-attachments/assets/3747f2a3-624e-4b50-ba55-68574668b3d0" />
7. Update the baseline version to `1.11.0-SNAPSHOT` in the root `pom.xml` and `Tilt`
8. ✅ Run `mvn org.technologybrewery.baton:baton-maven-plugin:baton-migrate`
9. ✅ Verify spark worker image is updated with the `1.0.0-SNAPSHOT` tag in the `pyspark-pipeline` and `spark-pipeline` values templates:
    <img width="876" alt="Screenshot 2024-12-16 at 4 20 48 PM" src="https://github.com/user-attachments/assets/724939c6-fbe5-46a0-8d93-bc04d289f577" />
    <img width="876" alt="Screenshot 2024-12-16 at 4 21 33 PM" src="https://github.com/user-attachments/assets/60bd0079-bd04-4398-8d67-cf5ce1bedbfa" />
    <img width="876" alt="Screenshot 2024-12-16 at 4 21 54 PM" src="https://github.com/user-attachments/assets/6e8eb0ce-bec2-4797-8a83-40ab3f7c84cf" />
    <img width="876" alt="Screenshot 2024-12-16 at 4 22 07 PM" src="https://github.com/user-attachments/assets/fb269ba0-b42e-4cc1-9850-b00926ec75db" />
10. ✅ Verify the fabric8 `docker-maven-plugin` has no with `skip` configuration in the -docker/pom.xml
    <img width="439" alt="Screenshot 2024-12-16 at 4 22 49 PM" src="https://github.com/user-attachments/assets/75b0d3ee-4b8b-4cc0-b68c-bb1012e2cdc7" />
11. ✅ Verify the pipeline dependency type is updated in the `-docker/test-migration-spark-worker-docker/pom.xml`. e.g.:
    <img width="461" alt="Screenshot 2024-12-16 at 4 24 10 PM" src="https://github.com/user-attachments/assets/335000b0-163e-4c67-95ec-329d52cac7a6" />
