### ISSUE TITLE
Feature: Align deployment mechanism from Development to Production

### ISSUE THREAD

**Issue by epwilkins** [boozallen/aissemble#483]
## Description
To reduce the risk of bugs when transitioning code from local testing to higher environments, we want to switch from Tilt-based deployment to ArgoCD deployment.

## DOD
- [x] Deployments should be simple for a general MLE/data scientist without expertise in the baseline
- [x] ArgoCD can be easily deployed locally
- [x] New local changes can be deployed with minimal steps. Changes could include the following artifacts:
  - [x] Changes pipeline wheel/jar
  - [x] Changes to docker images
  - [x] Changes to helm charts

## Test Strategy/Script
- Create a downstream project with baseline version 1.11.0-SNAPSHOT (**Note: the <<github_username>> in the following command must replaced with the actual value**)
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.11.0-SNAPSHOT \
                       -DgroupId=org.test \
                       -DartifactId=test-483-final \
                       -DprojectGitUrl=https://github.com/<<github_username>>/test-483-final.git \
                       -DprojectName="Verify ArgoCD local deploymebt" \
&& cd test-483-final
```
- Add [PysparkPipeline.json](https://github.com/user-attachments/files/17925373/PysparkPipeline.json) and [SparkPipeline.json](https://github.com/user-attachments/files/17925376/SparkPipeline.json) to the test-483-final-pipeline-models/src/main/resources/pipelines directory
- Run mvn clean install until all the manual actions are complete
- Config apps:
  - **Configuration-store:** delete the `test-483-final-deploy/src/main/resources/templates/configuration-store.yaml` to skip the configuration-store configuration
  - **Remote-Auth-Secret**: remove the `YOUR_SECRET_KEY: YOUR_SECRET_VALUE` in the `-deploy/src/main/resources/templates/remote-auth-secret.yaml` file and update with below values:
    ```
    AWS_ACCESS_KEY_ID: "123"
    AWS_SECRET_ACCESS_KEY: "456"
    ```
  - **Pipeline:** under `metadata`, add `namespace: test-483-final` config to both `pyspark-pipeline-base-dev-values.yaml` and `spark-pipeline-base-dev-values.yaml` file, e.g. :
    ```
    metadata:
         namespace: test-483-final
    ```
    and update the image version to `1.0.0-SNAPSHOT`, e.g.: `image: "test-483-final-spark-worker-docker:1.0.0-SNAPSHOT"`

  - **Pipeline Invocation Service:**: replace the content in the `-deploy/src/main/resources/apps/pipeline-invocation-service/values-dev.yaml` with below content
      ```
        aissemble-pipeline-invocation-chart:
          aissemble-quarkus-chart:
            image:
              imagePullPolicy: IfNotPresent
            service:
              type: NodePort
              ports:
                - name: "invocation-rest"
                  port: 8080
                  targetPort: 8080
                  nodePort: 30004
                - name: "quarkus-managed"
                  port: 9001
                  targetPort: 9000
            ingress:
              enabled: false
      ```
      Also, include below content in the `test-483-final-deploy/src/main/resources/templates/pipeline-invocation-service.yaml` file (ref: bugxxx to be created)
      ```
        {{ if .Values.spec.helm.valueFiles }}
        helm:
          valueFiles:
            {{- range .Values.spec.helm.valueFiles }}
            - {{ . }}
            {{- end }}
        {{ end }}
      ```
  - **Docker build:** in the `-docker/pom.xml` file, in the build -> pluginManagement -> plugins ->  `docker-maven-plugin` plugin, enable the docker build by set `<skip>` flag to `false`
    ```
                    <configuration>
                        <skip>false</skip>
                        <images>
                            <image>
                                <name>${project.artifactId}:${project.version}</name>
                            </image>
                        </images>
                    </configuration>
    ```
  - **Enable prune resource for testing:** append below content under `spec:` to the -deploy/src/main/resources/values-dev.yaml file
    ```
      syncPolicy:
        automated:
          prune: true
    ```
  - **Temp cache fix:** Unzip the [maven-build-cache-config.xml.zip](https://github.com/user-attachments/files/17938562/maven-build-cache-config.xml.zip) and replace the .mvn/maven-build-cache-config.xml file 
- Run `mvn clean install` once to get any remaining manual actions

- Create a repo for the project created 
   - Create a new test-483-final repository from the `https://github.com/<<username>>?tab=repositories` (Note: replace the <<username>> with your GitHub user name
   - Update the -deploy/src/main/resources/values.yaml file with the correct repo url and branch
       ```
         targetRevision: main
         repo: https://github.com/<username>/test-483-final.git
       ```
   - at the test-483-final root directory run below commands
       -  `git init `
       -  `git add .`
       -  `git add -f test-483-final-deploy/src/main/resources/apps/pipeline-invocation-service/target/`
       -  `git commit -m "init test-483-final base"`
       -  `git branch -M main`
       -  `git remote add origin git@github.com:<username>/test-483-final.git`
       -  `git push -u origin main`
    
- Local deployment
   -  At the project root directory, run `chmod +x deploy.sh`
   - Run `./deploy.sh up`
   - Verify all apps are running with healthy status
- Test changes to docker images
   - Run `touch test-483-final-docker/test-483-final-policy-decision-point-docker/src/main/resources/helloworld.properties`
   - Append below line to the `-docker/test-483-final-policy-decision-point-docker/src/main/resources/docker/Dockerfile
      ```
      COPY ./src/main/resources/helloworld.properties /deployments/krausening/

      ```
   - Run `mvn clean install -pl :test-483-final-policy-decision-point-docker`
   - Delete the existing policy decision point pod use [UI](http://localhost:30080/applications/argocd/policy-decision-point?view=tree&resource=) or Run `kubectl delete pod -n test-483-final -l app.kubernetes.io/name=policy-decision-point` from command line
   - Verify the new image is updated
     - Run `kubectl get pods -n test-483-final` and copy the policy-decision-point-xxx pod id
     - Run `kubectl exec -it <policy-decision-point-xxx> -n test-483-final -- sh`
     - Run`ls -al /deployments/krausening` and verify the `helloworld.properties` is listed
- Test changes to the helm charts
     - Update the app name to be `policy-decision-point-updated` in the `-deploy/src/main/resources/apps/policy-decision-point/values.yaml` file 
     - Commit and push the changes
     - Click on the `Refresh` button the policy-decision-point [UI](http://localhost:30080/applications/argocd/policy-decision-point?view=tree&resource=)
     - Verify the changes are updated
- Test `pipeline wheel/jar` changes 
   - Update Spark-Pipeline 
       1. Run below command to deploy pipeline
           ```
             curl -H 'Content-Type: application/json' -d '{ "applicationName": "spark-pipeline"}' -X POST http://localhost:30004/invoke-pipeline/start-spark-operator-job
           ```
       2. Run `kubectl logs -f spark-pipeline-driver -n test-483-final` to verify the pipeline run successfully
       3. In the `test-483-final-pipelines/spark-pipeline/src/main/java/org/test/Ingest.java file`, replace line 61 with  `logger.info("Verify updated successfully -------------------"); `  
       4. Run `mvn clean install -pl :spark-pipeline -amd`
       5. Repeat step a. & b. to verify the `Verify updated successfully -------------------` shown in the log

   - Update Pyspark-Pipeline
      1. Run below command to deploy pipeline
           ```
            curl -H 'Content-Type: application/json' -d '{ "applicationName": "pyspark-pipeline"}' -X POST http://localhost:30004/invoke-pipeline/start-spark-operator-job
           ```
       2. Run `kubectl logs -f pyspark-pipeline-driver -n test-483-final` to verify the pyspark pipeline run successfully
       3. In the `test-483-final-pipelines/pyspark-pipeline/src/pyspark_pipeline/step/ingest.py` file replace the line 52 with below content
          ```
          "Verify pipeline update successfully ---------------------------------!"
          ```
       4. Run `mvn clean install -pl :pyspark-pipeline -amd`
       5. Repeat step a. & b. to verify the `Verify pipeline update successfully ---------------------------------!` shown in the log

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi @nartieri @carter-cundiff

**Comment by csun-cpointe** [comment]
OTS completed with @carter-cundiff

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/5f0c5017-1938-4e43-802f-ab64273ceb27)
![image](https://github.com/user-attachments/assets/d44104bd-39c3-41ed-9d75-e7225aac5208)
![image](https://github.com/user-attachments/assets/b28ce8b2-a923-434d-a3c6-2123b8f563ca)
![image](https://github.com/user-attachments/assets/3cde6dd9-3ae2-477c-a16f-52c1c1e61012)

**Comment by epwilkins** [comment]
These changes were at least partially reverted in #513
