### ISSUE TITLE
Feature: integrate Universal Config store in the hive metastore service

### ISSUE THREAD

**Issue by jaebchoi** [boozallen/aissemble#484]
## Description
Given that aiSSEMBLE support Universal config store service, It is great to make use of this service for consumer in order to prevent duplication in configuration.
First step is to try with one service called Hive Metastore service.

## DOD

- [x] Enable overriding hive metastoreServiceConfig.baseProperties in metastoreServiceConfig.properties 
- [x] Replace Hive Username with Universal config store.
- [x] Generate hive properties file on appropriate location (I.e. -deploy/src/main/resources/configuration)
- [x] Prompt potential consumers that we shall encrypt password using krausening with the link.
- [x] Create Downstream project with hive meta service and verify correct config is fetched from universal config service.
- [x] Add unit test to make sure yaml file contains appropriate properties values set and labels.( Helpful doc in Reference) 
- [x] Add baton migration for this change.
- [x] BDD scenario for migrating projects from legacy way to new way. 

## Stretch Goal
- [ ] Add Archetype test to ensure helm ignore file is correctly added https://maven.apache.org/archetype/maven-archetype-plugin/integration-test-mojo.html

## Test Strategy/Script

- Create a downstream project with baseline version 1.11.0-SNAPSHOT
```
mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble \
  -DarchetypeArtifactId=foundation-archetype \
  -DarchetypeVersion=1.11.0-SNAPSHOT \
  -DgroupId=com.test \
  -DartifactId=test-hive1 \
  -DprojectGitUrl=https://github.com/{github-username}/test-hive1 \
  -DprojectName=test-hive1 \
  && cd test-hive1 
```

- Add the [SparkPipeline.json](https://github.com/user-attachments/files/16781488/SparkPipeline.json) file to the test-hive1-pipeline-models/src/main/resources/pipelines directory
- Run mvn clean install until all the manual actions are complete
- Once the manual actions are complete, run `mvn clean install -Dmaven.build.cache.skipCache=true` once to get any remaining manual actions
- Modify the helm templates for Argocd deployment:
       - Mac User: In the `-deploy/src/main/resources/apps/configuration-store/values-dev.yaml file` update the `volumePathOnNode` to be `/<pathToProject>/test-hive1-deploy/src/main/resources/configurations`
       - Window User: In the `-deploy/src/main/resources/values-dev.yaml file` update the `volumePathOnNode` to be `/mnt/c/Users/YOUR_USER/PATH/TO/test-hive1-deploy/src/main/resources/configurations`
- Create a repo for the project created 
   - create a new test-hive1 repository from the github website
   - at the test-hive1 root directory run below commands
   -  `git init `
   -  `git add .`
   -   `git commit -m "init test-hive1 base"`
   -  `git branch -M main`
   -  `git remote add origin https://github.com/<username>/<repo_name>.git`
   -  `git push -u origin main`

- on the root of your downstream project

- make deploy script executable permission
`chmod +x deploy.sh `

- change port fowarding  of argocd-server to 30080
i.e. go to Rancher desktop-> Click Portfowarding on left section
NOTE: we’re port forwarding to avoid bug with NodePort in RD on ARM Mac

- Run following to stand up argoCD
`./deploy.sh up`

- Go to localhost:30080 
- In Argo CD, Go to Configuration store pod log, and see that Read is injected for metastore.db.username
you can do that by clicking configuration-store -> click pod ->. click log
![Screenshot 2024-12-09 at 3 52 49 PM](https://github.com/user-attachments/assets/76ffa022-0a4a-4064-b271-7e155095433d)

- check hive-metastore-service configmap that configuration is injected. Out of Sync is expected
you can do that by clicking spark infractructure  -> hive-metastore-service CM-> see diff
![Screenshot 2024-12-09 at 3 51 02 PM](https://github.com/user-attachments/assets/2ef5542c-c6f9-4c3d-ac28-85fb4b298394)
- Also check hive-metastore-db STS that configuration is injected. Out of Sync is expected
you can do that by clicking spark infractructure  -> hive-metastore-db STS -> see diff
![Screenshot 2024-12-09 at 3 52 23 PM](https://github.com/user-attachments/assets/e7dbe017-f84d-4656-9e64-017007c6c058)

**Test for Baton Migration**

- In the downstream project, update -deploy/src/main/resources/apps/spark-infrastructure/values.yaml to add default values i.e.

- in the mysql/auth, add following
```
      username: hive
```

- Also add following in the configMap/metastoreServiceConfig/properties:
```
        - name: javax.jdo.option.ConnectionUserName
          value: hive
          description: Username to use against metastore database
```

- Run mvn clean install -Dmaven.build.cache.enabled=false

- Verify upon build, one that we added were deleted.

## References/Additional Context
Helm Unit Test (https://github.com/helm-unittest/helm-unittest?tab=readme-ov-file#dependent-subchart-testing)

**Comment by jaebchoi** [comment]
DoD Completed with @csun-cpointe @ewilkins-csi @carter-cundiff

**Comment by jaebchoi** [comment]
OTS completed with @carter-cundiff @csun-cpointe @ewilkins-csi

**Comment by meliz19** [comment]
Final test completed. 

*Lead Time:* 12 days

**Comment by epwilkins** [comment]
These changes were at least partially reverted in #513
