### ISSUE TITLE
Feature: Add functionality for extending foundation-mda so that I can modify existing metamodel schemas in a downstream project

### ISSUE THREAD

**Issue by carter-cundiff** [boozallen/aissemble#495]
## Description
[Fermenter Issue #78](https://github.com/TechnologyBrewery/fermenter/issues/78) fixed an issue with extending a projects existing metamodel repository. This new functionality needs to be incorporated into aiSSEMBLE, so that downstream projects can extend our metamodel repository.

Currently within aiSSEMBLE we get the metamodel repository with the following method call:
```
AIOpsModelInstanceRepostory metamodelRepository = ModelInstanceRepositoryManager
                .getMetamodelRepository(AIOpsModelInstanceRepostory.class);
```
This prevents downstream users from being able to extend our `AIOpsModelInstanceRepostory`, see [Fermenter Issue #78](https://github.com/TechnologyBrewery/fermenter/issues/78) for more details. With the new functionality added to Fermenter to resolve that issue, we need to replace our existing calls to get the metamodel repository with the following new method:
```
AIOpsModelInstanceRepostory metamodelRepository = generationContext.getModelInstanceRepository();
```

## DOD
- [x] Update all calls to get the metamodel repository within generator classes to use the new method
  - [x] Use the `GenerationContext` object which is available in all generators
- [x] Check for compilation warnings within build output of `foundation-mda` for issues that might cause bugs when extending classes
- [x] Update `mda-maven-plugin` to handle an extended metamodel repository
- [x] Rename and add to Release Notes:
  - [x] `AIOpsModelInstanceRepostory` :arrow_right: `AissembleModelInstanceRepository`
  - [x] `AiopsMdaJsonUtils` :arrow_right: `AissembleMdaJsonUtils`
- [x] Increase testing in `foundation-mda`
  - [x] Create new unit test for `extending foundation-mda` 
- [x] Create way in Fermenter to get metamodel repository without direct access to the generation context (i.e. within a `MetamodelElement`)
  - [x] Release next minor version of Fermenter

## Test Strategy/Script
- **OTS Only:**
  - Run the following on the [78-enable-metamodel-extension](https://github.com/TechnologyBrewery/fermenter/tree/78-enable-metamodel-extension) branch in Fermenter: `mvn clean install`
- Run the following within aiSSEMBLE:
```
mvn clean install -pl :foundation-mda,:mda-maven-plugin -am -Dmaven.build.cache.skipCache
```

## References/Additional Context
[Fermenter Issue #78](https://github.com/TechnologyBrewery/fermenter/issues/78)

**Comment by carter-cundiff** [comment]
DOD with @ewilkins-csi, @csun-cpointe

**Comment by carter-cundiff** [comment]
OTS with @ewilkins-csi

**Comment by ewilkins-csi** [comment]
[Build](https://github.com/boozallen/aissemble/actions/runs/12322723950) succeeded

**Comment by epwilkins** [comment]
[Build](https://github.com/boozallen/aissemble/actions/runs/12322723950) succeeded
