### ISSUE TITLE
Feature: Configuration Store injection should happen on update

### ISSUE THREAD

**Issue by epwilkins** [boozallen/aissemble#498]
## Description
Currently, the configuration store only injects values on object creation.  This means if an object is _updated_ with an injection point, it is not processed.  This especially causes issues in ArgoCD, where changing an non-injected field will lead to previously injected fields being replaced with their injection call.

This actually causes a pretty severe issue with `StatefulSets` and `DaemonSets`. Those objects [create revision](https://shivering-isles.com/til/2024/01/statefulset-revisions) objects called `ControllerRevisions` to track state. Without update functionality, the newly created revision gets injection performed but the actual workload object does not. This causes the set to see a difference between the current state and the recorded revision, so it redeploys a new revision to track the new state. But again, this newly created revision gets injection and does not match, leading to an infinite loop of creating `ControllerRevisions`.  We should ensure that after this feature is implemented this no longer happens.

## DOD
Acceptance criteria required to realize the requested feature
- [x] `MutatingWebhookConfiguration` for Config Store includes the `UPDATE` operation

## Test Strategy/Script
1. Deploy the config store helm chart
```sh
helm install aissemble-config oci://ghcr.io/boozallen/aissemble-configuration-store-chart --version 1.11.0-SNAPSHOT --set 'aissemble-quarkus-chart.deployment.env[0].name=BASE_PROPERTY' --set 'aissemble-quarkus-chart.deployment.env[0].value=/tmp'
```
2. Verify the webhook config includes `UPDATE` under `webhooks.rules.operations`. (You might need to wait a couple of minutes for the webhook config to be created)
```sh
kubectl get mutatingwebhookconfiguration boozallen.aissemble-configuration-store.webhook -o yaml
```
3. Uninstall the chart
```sh
helm uninstall aissemble-config
```

**Comment by epwilkins** [comment]
**DoD** with @csun-cpointe

**Comment by epwilkins** [comment]
**OTS** with @csun-cpointe

**Comment by carter-cundiff** [comment]
Testing passed:
![image](https://github.com/user-attachments/assets/85416e50-250e-4857-a13c-5f43daeb50dd)
