### ISSUE TITLE
BUG: Update image for `vectorized/redpanda:v24.1.7` -> `redpandadata/redpanda:v24.1.7`

### ISSUE THREAD

**Issue by meliz19** [boozallen/aissemble#499]
## Description
The aiSSEMBLE build broke in CI last night when building the `extensions-data-lineage` module due to `vectorized/redpanda:v24.1.7` image relocating to `redpandadata/redpanda:v24.1.7`.

## Steps to Reproduce
Attempt to build the `extensions-data-lineage` module locally.

## Expected Behavior
The module should build successfully. 

## Actual Behavior
```
ERROR [com.git.doc.api.asy.ResultCallbackTemplate] (docker-java-stream--1956978967) Error during callback: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"pull access denied for vectorized/redpanda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}
```

**Comment by cwoods-cpointe** [comment]
Build is now passing - https://github.com/boozallen/aissemble/actions/runs/12258646872
