### ISSUE TITLE
Clean up ConfigMap Logic in the Hive-metastore-service to improve space complexity

### ISSUE THREAD

**Issue by jaebchoi** [boozallen/aissemble#501]
## Description
Per [#484](https://github.com/boozallen/aissemble/pull/494), we had conversation regarding logic behind making properties values override base properties.

Instead of making two dictionaries, we should be cleaning up logic to make it more simple and readable.

## DOD
- [x] Update Configmap.yaml to just compare baseProperties and properties instead of making two dictionaries to achieve this logic
- [x] Make sure logic stays the same (No Regression)

## Test Strategy/Script
How will this feature be verified?
- Pull Latest dev branch of aissemble
- do `mvn clean install`
- Verify unit test for configmap in hive-metastore succeed.
i.e `[INFO] aiSSEMBLE::Extensions::Helm::Hive::Metastore Service SUCCESS [ 10.123 s]`

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by jaebchoi** [comment]
DoD Completed with @meliz19 @chang-annie

**Comment by jaebchoi** [comment]
OTS Completed @chang-annie @cwoods-cpointe

**Comment by cwoods-cpointe** [comment]
Unit tests pass locally and on the [build](https://github.com/boozallen/aissemble/actions/runs/12321017844)

**Comment by epwilkins** [comment]
These changes were at least partially reverted in #513
