### ISSUE TITLE
TASK: Remove gh-pages branch

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#507]
## Description
Based on past experience with the separated branch for handling documentation, we had a lot of confusion so to avoid the same thing happen again, we will remove this `gh-pages` branch and have other ways to publish the aggregated cucumber report. This quick task will revert the change made per [PR](https://github.com/boozallen/aissemble/pull/490/files).

## DOD
Acceptance criteria required to complete the work
- [x] Revert https://github.com/boozallen/aissemble/pull/490/files
- [x] Delete gh-pages branch
- [x] Verify new build after revert doesn’t re-create gh-pages

## Test Strategy/Script
How will this item be verified?
- Verify (latest build)[https://github.com/boozallen/aissemble/actions] success

**OTS:**
- Verify no files are pushed to the `gh-pages` branch

**Final Test:**
- Verify [gh-pages branch](https://github.com/boozallen/aissemble/branches) is deleted

## References/Additional Context
As needed

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi and @nartieri

**Comment by epwilkins** [comment]
**Final Test** passed ✅ 
Build passed:
    ![Screenshot 2024-12-17 at 11 16 39 AM](https://github.com/user-attachments/assets/284cca8b-b1f8-42e8-a6ed-b8278e321bbd)

No `gh-pages` branch:
    ![Screenshot 2024-12-17 at 11 16 13 AM](https://github.com/user-attachments/assets/eda8925c-871a-4bde-afff-860f711e1d32)
