### ISSUE TITLE
Feature: Migrate ML pipelines to work with non-Tilt deployments.

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#510]
## Description
Follow up #482, we have enable maven docker build for the most of the docker modules. For this ticket, we also want to enable the maven docker build for the ML pipelines so that it can be ready for non-Tilt deployments.

## DOD
Acceptance criteria required to realize the requested feature
- [x] Generate the ml pipelines with their step modules that already added to the parent pom
- [x] Include cucumber tests
---- **Note:** revisit below items after the above bullets finished
- [x] Enable maven docker build for ML pipelines
- [x] Add ml pipeline artifact to ML docker module checksum calculation
- [x] Remove the Tilt docker_build(), local_resources() Manual Action for ML pipelines
- [x] Add migration scripts to include the necessary changes

## Test Strategy/Script
**Test ML PipelineCache/Docker Build**

**OTS Only**
1. Run `./mvnw -B clean install -Parchetype-test -pl :foundation-archetype` and ensure the build is successful.
1. Run `docker images` to ensure that `test-generator-machine-learning-training-docker:1.0.0-SNAPSHOT ` and `test-generator-machine-learning-inference-docker:1.0.0-SNAPSHOT` is present in the images list
**Note**: the successful docker image build represents the ml pipelines with their step modules generated in the project model.

**Final Test**
1. Create a downstream project with baseline version 1.11.0-SNAPSHOT 
```
mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble \
                       -DarchetypeArtifactId=foundation-archetype \
                       -DarchetypeVersion=1.11.0-SNAPSHOT \
                       -DgroupId=org.test \
                       -DartifactId=test-510 \
                       -DprojectGitUrl=test/test-510.git \
                       -DprojectName="Test ML pipeline docker build" \
                       && cd test-510
```
2. Add [ClassificationTraining.json](https://github.com/user-attachments/files/18215535/ClassificationTraining.json)
to the test-510-pipeline-models/src/main/resources/pipelines directory
3. Run mvn clean install until all the manual actions are complete
4. In the `-pipelines/classification-training/logistic-training/src/logistic_training/classification_training_driver.py`, add below lines after `PipelineBase().record_pipeline_lineage_complete_event()` to trigger pipeline changes
```
print("------------ trigger logistic_training pipeline changes ----------.")
```
6. Run mvn clean install and verify the `test-510-logistic-training-docker` is re-build.

## References/Additional Context
Add any other context, links, or screenshots about the feature request here.

**Comment by csun-cpointe** [comment]
DoD completed with @ewilkins-csi

**Comment by epwilkins** [comment]
**OTS** test passed ✅

**Comment by carter-cundiff** [comment]
Testing passed
