### ISSUE TITLE
Feature:Remove in-flight changes that prevent immediate release

### ISSUE THREAD

**Issue by epwilkins** [boozallen/aissemble#513]
## Description
In our recent work on path to production alignment and baking in the universal config store, we've drifted away from our goal of always being ready to cut a release.  We want to get back to a good state and move any changes that requires further work to fully polish to feature branches so we can respond more quickly to demand.

## DOD
- [x] Path to production alignment changes that prevent deployment via Tilt or introduce files to support local ArgoCD deployment are moved to a feature branch
  - [x] New infrastructure module is removed
  - [x] New deploy shell script it removed
  - [x] Other changes are analyzed and removed as appropriate
  - [x] Remove any migrations specific to the removed changes
- [x] Universal config work that will force projects to setup the config store are moved to a feature branch
  - [x] Default usage of injection hooks in spark-infrastructure charts is removed
  - [x] Other changes are analyzed and removed as appropriate
  - [x] Remove any migrations specific to the removed changes
- [x] Ensure release notes do not include any instructions/information about changes that have been moved to feature branches
- [x] Ensure Antora docs do not contain information for changes moved to feature branches
- [x] For tickets that introduced the changes moved to feature branches, ensure a paper trail is left leading back to this ticket

## Test Strategy/Script
1. Create a new project
```sh
mvn archetype:generate '-DarchetypeGroupId=com.boozallen.aissemble' \
                       '-DarchetypeArtifactId=foundation-archetype' \
                       '-DarchetypeVersion=1.11.0-SNAPSHOT' \
                       '-DgroupId=org.test' \
                       '-Dpackage=org.test' \
                       '-DprojectGitUrl=test.org/test.git' \
                       '-DprojectName=Test Project' \
                       '-DartifactId=final-513'
```
2. Verify there is no _final-513-infrastructure_ module or a _deploy.sh_ script
3. Add [SparkPipeline.json](https://github.com/user-attachments/files/18203992/SparkPipeline.json) to _final-513-pipeline-models/src/main/resources/pipelines_
4. Build the project and resolve manual actions until none are printed
5. Run the build again with the cache disabled and apply final manual actions: `mvn clean install -Dmaven.build.cache.skipCache`
6. Deploy the project with `tilt up`
7. Verify all resource start successfully
8. Run the **spark-pipeline** resource and verify it completes successfully

**Comment by epwilkins** [comment]
**DoD** with @nartieri

**Comment by csun-cpointe** [comment]
OTS completed!

![Screenshot 2024-12-19 at 5 39 19 PM](https://github.com/user-attachments/assets/3110d91b-a3c9-4c69-a207-f82e82268d40)
![Screenshot 2024-12-19 at 5 41 29 PM](https://github.com/user-attachments/assets/b3e7f4dc-1ace-4792-9e8e-20e383e27f85)

**Comment by nartieri** [comment]
Verification: 

1. No final-513 module and no deploy.sh script: 
![image](https://github.com/user-attachments/assets/02803b02-9286-4dfb-a78f-d1032ee715d7)
2. Successful project build:
![image](https://github.com/user-attachments/assets/74a30f3d-79a0-484c-8306-2c3078edbe2d)
3. Successful pipeline run. 
![image](https://github.com/user-attachments/assets/db2e391c-a6e5-4628-87d8-25c6835c9295)
