### ISSUE TITLE
As a consumer of aiSSEMBLE, I want to accelerate my project builds by leveraging the build cache capability.

### ISSUE THREAD

**Issue by peter-mcclonski** [boozallen/aissemble#58]
## Definition of Done 

- [x] For all new and existing aissemble-based projects, the file `$PROJECT_ROOT/.mvn/maven-build-cache-config.xml` shall be generated with appropriate content to enable the build cache.
- [x] For all new and existing aissemble-based projects, the file `$PROJECT_ROOT/.mvn/extensions.xml` shall be generated with appropriate content to enable the build cache.
- [x] A baton migration shall exist such that for any Habushu-packaged module, the following content shall be present in the pom, if and only if the tag does not currently exist within the pom:
-- `<build><directory>dist</directory></build>`
- [x] All existing templates for pom files specifying Habushu packaging shall updated to include the following content:
-- `<build><directory>dist</directory></build>`
- [x] Release notes shall be updated to describe this new functionality, with a link to the official documentation for the Maven build cache.
- [x] Release notes shall be updated with the new baton migration.

### New Projects

1. Generate a new aiSSEMBLE based project using the following command:
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.7.0-SNAPSHOT \
                          -DartifactId=test-project-58\
                          -DgroupId=org.test \
                          -DprojectName='Test Cache' \
                          -DprojectGitUrl=test.org/test-project-58\
&& cd test-project-58
```
2. Execute `mvn clean install -pl :test-project-58-pipeline-models`
3. Ensure the command completes successfully.
4. Execute `mvn clean install -pl :test-project-58-pipeline-models | grep cache`
5. Ensure that you see the following output:
```
[INFO] Skipping plugin execution (cached): compiler:compile
[INFO] Skipping plugin execution (cached): build-helper:add-test-source
[INFO] Skipping plugin execution (cached): build-helper:add-test-resource
[INFO] Skipping plugin execution (cached): resources:testResources
[INFO] Skipping plugin execution (cached): compiler:testCompile
[INFO] Skipping plugin execution (cached): surefire:test
[INFO] Skipping plugin execution (cached): jar:jar
```
6. Delete the created project.

### Project Upgrades

1. Generate a new aiSSEMBLE based project using the following command:
```
mvn archetype:generate -B -DarchetypeGroupId=com.boozallen.aissemble \
                          -DarchetypeArtifactId=foundation-archetype \
                          -DarchetypeVersion=1.6.0\
                          -DartifactId=test-project-58\
                          -DgroupId=org.test \
                          -DprojectName='Test Cache' \
                          -DprojectGitUrl=test.org/test-project-58\
&& cd test-project-58
```
2. Add the following pipeline definition to `test-project-58-pipeline-models/src/main/resources/pipelines/PythonPipeline.json`:
```
{
  "name": "PythonPipeline",
  "package": "com.boozallen.example",
  "description": "Sample Pipeline",
  "type": {
    "name": "data-flow",
    "implementation": "data-delivery-pyspark"
  },
  "steps": [
    {
      "name": "ExecuteExample",
      "type": "synchronous",
      "dataProfiling": {
        "enabled": false
      }
    }
  ]
}
```
3. Execute `mvn clean install` a single time.
4. Update the contents of `test-project-58-pipelines/pom.xml` to include the following content:
```
    <modules>
        <module>python-pipeline</module>
    </modules>
```
5. Remove the following line from `test-project-58-pipelines/python-pipeline/pom.xml`:
```
        <directory>dist</directory>
```
6. Update the root `pom.xml` build-parent version to `1.7.0-SNAPSHOT`
7. Update the contents of `test-project-58-deploy/pom.xml` to remove any references to `${version.clean.plugin}`
8. Execute `mvn clean install`, with the expectation that a failure _will_ occur.  
9. Execute the following command: 
```
cat test-project-58-pipelines/python-pipeline/pom.xml | grep dist
```
11. Verify that you see the following output:
```
<directory>dist</directory>
```

**Comment by carter-cundiff** [comment]
OTS passed

**Comment by csun-cpointe** [comment]
Test passed!!
