### ISSUE TITLE
Improve downstream projects to more easily specify their project-specific pypi repository

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#65]
aissemble publishes PyPI artifacts to pypi.org and test.pypi.org.   While this may be a sensible choice for some users, others will want to publish their charts to a private PyPI repository.  This should be easy and _separate_ from aissemble PyPI artifact resolution (which can already be tailored to public or private PyPI repositories).

## Definition of Done

- [x] Update archetype to allow specification of project-specific PyPI repository
- [x] Ensure that project-specific PyPI repository is enabled for project-specific modules 
- [x] Update documentation to highlight how to specify a project-specific PyPI repository
- [x] Update release notes to manually add a private PyPI repository for projects migrating from a prior version of aissemble

## Test Steps
- Run the archetype plugin with the following commands:
```
cd ..

mvn archetype:generate \
    -DarchetypeGroupId=com.boozallen.aissemble \
    -DarchetypeArtifactId=foundation-archetype \
    -DarchetypeVersion=1.7.0-SNAPSHOT \
    -DgroupId=com.boozallen.test \
    -DartifactId=issue-65 \
    -DprojectGitUrl=url \
    -DprojectName=issue-65 \
    -DpypiProjectRepositoryUrl=https://private-pypi-base-url/repository/foo-pypi/

cd ./issue-65
```
- Run the following command to validate that the private pypi repository was configured into the project's `habushu-maven-plugin`'s `pypiRepoUrl` variable:
```
% cat pom.xml | grep private-pypi-base-url                
```
- Validate the response is:
```xml
<pypi.project.repository.url>https://private-pypi-base-url/repository/foo-pypi/</pypi.project.repository.url>
```
- Navigate to the aissemble docs [Creating a Project](https://boozallen.github.io/aissemble/aissemble/current/archetype.html) page
- Validate that instructions for `pypiProjectRepositoryUrl` exist and also point to the Habushu instructions for passing in credentials and note that other configuration options can also be found there.
- Validate that the release notes for 1.7.0 have instructions to manually update previously used private repositories

**Comment by colinpalmer-pro** [comment]
Test steps pass, closing issue.
