### ISSUE TITLE
[Design] As a devops engineer, I want a better pattern for managing python dependencies for docker images, so that I can easily bundle complex python dependencies for deployments

### ISSUE THREAD

**Issue by Cho-William** [boozallen/aissemble#74]
A pattern for installing python dependencies for a deployment setting is needed that fits the following:
  - Needs
    - pattern should be applicable for baseline docker images AND downstream aiSSEMBLE project docker images
    - flexible across architecture-specific caveats
    - able to handle monorepo dependencies
  - Nice-to-Have's
    - enables a shared cache for multiple docker images to leverage
      - ex. via a multi-stage build
    - does not "defeat the purpose" of the baseline build by rebuilding monorepo dependencies on the docker image
    - extend poetry's usage of its virtual environment cache and repository cache to streamline dependency retrieval and environment setup

The following pattern could provide a solution easy for users to leverage:
  - extend poetry's caching functionality to locally cache in Poetry's artifacts cache python dependencies that are locally developed
  - create a shared python module that depends on the collective set of aiSSEMBLE monorepo python dependencies that the various docker modules in the baseline depend on
  - utilize habushu/poetry to build this shared python module and thus generate a `poetry.lock` file that houses the hashes for the dependencies across all architectures/OS combinations)
  - prepend relevant docker images in the baseline with the following:
    -  an initial build stage that does the following:
      - copies the shared python module (which includes the `poetry.lock` file) into the container
      - leverages poetry + the `poetry-plugin-bundle` to: 
        - populate a mounted poetry cache
        - export the virtual environment
    - after the initial build stage, prepend the target stage with the following:
      - copy from the builder stage the exported virtual environment
  - ensure that the baseline is configured such that (for target images that leverage the shared cache) a multi-arch docker build is run to target both x86- and arm-based python dependencies

**DOD**
- [x] investigate Poetry's caching functionality
- [x] propose changes encapsulated in a design that covers the following:
  - [x] extend poetry's caching functionality to cache locally-built wheels in Poetry's artifacts cache
  - [x] ensure poetry can naturally retrieve the wheel from the artifacts cache
  - [x] ensure that the aiSSEMBLE baseline can leverage the extension and can retrieve monorepo dependencies

**Comment by Cho-William** [comment]
- Identified Poetry's logic for creating its cache's directory tree
  - simply uses OS with the following logic:
    - sets a specific mode for hashing (Poetry uses `0o777`)
    - if an available directory does not exist, generate a new directory path via OS's hashing method
    - return the hash path to Poetry's download method, which downloads the wheel and places it at that path
  -

**Comment by Cho-William** [comment]
Successfully replicated caching of wheel and manual retrieval. Next step is to test native Poetry retrieval of wheel, which may need to be facilitated by the monorepodependency plugin

**Comment by Cho-William** [comment]
The second round of the design's pink-team was completed, however a different pattern for installing dependencies was agreed upon to use instead.

**Comment by csun-cpointe** [comment]
Final test passed!!
