### ISSUE TITLE
Require Docker image build to fail if any Python requirement fails to install

### ISSUE THREAD

**Issue by Cho-William** [boozallen/aissemble#8]
We want to ensure that the docker image builds fails if any python dependency installation fails. In particular, when using `find` or `for-loops` in a dockerfile's instruction to install `requirements.txt` or `.tgz` or `.whl` files, a failed Python dependency installation will not cause the docker build to fail. This faulty behavior can be fixed by prefixing the relevant docker instruction with `set -e &&` and avoiding usage of the `find` command to ensure any non-zero exit code will cause the shell environment to exit. See below examples:

```dockerfile
# faulty behavior
RUN find /tmp/requirements -path '/tmp/requirements/*/*' -name requirements.txt -type f -exec python3 -m pip install --no-cache-dir -r '{}' ';'
RUN cd /modules/${trainingModule}; for x in *.whl; do pip install $x --no-cache-dir --no-deps; done

# fail fast behavior
RUN set -e && files=$(find /tmp/requirements -path '/tmp/requirements/*/*' -name requirements.txt -type f); for file in $files; do python3 -m pip install --no-cache-dir -r $file || exit 1; done;
RUN set -e && cd /modules/${trainingModule}; for x in *.whl; do pip install $x --no-cache-dir --no-deps; done
```

**Definition of Done**

- develop and test a docker modification that will cause the docker image build to fail if any python installation cannot be completed from the requirements.txt or wheels or tarballs 
- update the baseline so that all relevant docker files in other modules have this "fail fast" behavior
- identify all relevant dockerfile templates to also be updated
- write a baton migration to add to downstream docker files any needed changes to implement this behavior 
- update release notes to list the new baton migration

**Comment by csun-cpointe** [comment]
Test passed with test steps:

**Test New Project Dockerfile Generation**

1. Pull the latest branch and build the following:
```
mvn clean install -pl :foundation-mda -Dmaven.build.cache.enabled=false
mvn clean install -pl :foundation-upgrade -Dmaven.build.cache.enabled=false
```

2. Create a downstream project from the archetype using the following command:
`mvn archetype:generate -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.7.0-SNAPSHOT -DgroupId=com.example -DartifactId=example -DprojectGitUrl=url -DprojectName=example && cd example`

3. Add the attached PysparkPipeline.json to example-pipeline-models/src/main/resources/pipelines/

4. Run the following once:
```mvn clean install```

5. Run the following until all the manual actions are complete
```mvn clean generate-sources```

6. Modify the Pyspark pipeline's pyproject.toml file to point to local path dependency, similar to below:
```aissemble-extensions-data-delivery-spark-py = { path = "../../aissemble/extensions/extensions-data-delivery/aissemble-extensions-data-delivery-spark-py/dist/aissemble_extensions_data_delivery_spark_py-1.7.0.dev0.tar.gz"} ```

7. Run the following once:
```mvn clean install```

8. Tilt up your project
```tilt up;tilt down```

9. Verify that the spark-operator docker image fails to build

**Test Upgrading Project Dockerfile Migration**

10. Pull the latest dev aiSSEMBLE branch and build the following:
```mvn clean install -pl :foundation-mda -Dmaven.build.cache.enabled=false```

11. Create a downstream project from the archetype using the following command:
```mvn archetype:generate -U -DarchetypeGroupId=com.boozallen.aissemble -DarchetypeArtifactId=foundation-archetype -DarchetypeVersion=1.6.0-rc3 -DgroupId=com.example -DartifactId=example-upgrade -DprojectGitUrl=url -DprojectName=example-upgrade && cd example-upgrade```

12. Add the attached `PysparkPipeline.json` to `example-upgrade-pipeline-models/src/main/resources/pipelines/`
13. Run the following once:
```mvn clean install```
14. Run the following until all the manual actions are complete
```mvn clean generate-sources```
15. Update the root `pom.xml` build-parent version to `1.7.0-SNAPSHOT`
16. Run the following:
```mvn clean install```
17. Verify the following lines are present in the spark-worker dockerfile:
```RUN set -e && files=$(find /tmp/requirements -path '/tmp/requirements/*/*' -name requirements.txt -type f); for file in $files; do python3 -m pip install --no-cache-dir -r $file || exit 1; done;

RUN set -e && files=$(find /tmp/wheels -path '/tmp/wheels/*' -name '*.whl' -type f); for file in $files; do python3 -m pip install --no-cache-dir $file || exit 1; done;

RUN set -e && files=$(find /opt/spark/jobs -path '/opt/spark/jobs/pipelines/*/*' -name '*.tar.gz' -type f); for file in $files; do python3 -m pip install --no-deps --no-cache-dir $file || exit 1; done;```
