### ISSUE TITLE
Enable ConfigLoader to write/read config properties to vault server

### ISSUE THREAD

**Issue by csun-cpointe** [boozallen/aissemble#9]
A part of a series to implement the Universal Configurations, we want the foundation-configuration-store module ConfigLoader class be able to read/write loaded configuration properties to the vault server.

**Definition of Done:**
- Add to foundation-configuration-store the PropertyDAO class that abstracts away logic for writing properties to Vault
- Ensure that configurations loaded by the ConfigLoader class can write to the Vault server
- Ensure written configurations can be read from Vault by the ConfigLoader
- Add an unit test that stands up a vault test container as a vault server where we can write/read configuration properties
- BDD Scenario:
```
Feature: Configuration can be stored to Vault
  
  Scenario: The ConfigLoader can read and write to the Vault server
    Given set of properties to be loaded
    When the configurations are loaded
    And the properties can be read from the vault server
```

**Comment by carter-cundiff** [comment]
Testing passed

**Comment by carter-cundiff** [comment]
![image](https://github.com/boozallen/aissemble/assets/129905339/096fa7e1-24f2-4a91-ba37-b2aa3aca6f96)
![image](https://github.com/boozallen/aissemble/assets/129905339/f17dc218-ac7a-4d47-943b-447c33d67529)
