### ISSUE TITLE
Update aissemble to use habushu 2.15.0

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#97]
## Definition of Done
Upgrade to the latest version of Habushu to gain in-project virtual environments (eases Python debugging) and publish retries.

## Test Steps
* Run the build:
```
mvn clean install
```
* Validate the build completes normally
* Python modules should all now have an ignored `.venv` folder directly in the module for their virtual environment

**Comment by chang-annie** [comment]
all tests passing! closing issue as done

- [x] build is successful
- [x] python modules have `.venv` ignored folder
