### ISSUE TITLE
Update to use latest `docker-py` and `requests` verisons

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [boozallen/aissemble#98]
Follows up on #85 now that community fixes are available.

## Definition of Done
* Update `requests` to now use version 2.32.2
* Ensure that `docker` is now version 7.1.0

## Test Steps
* Execute the build
```
mvn clean install
```
* Builds successfully
* In `aissemble-extensions-encryption-vault-python/poetry.lock`, ensure the following versions are being used:
  * `requests` 2.32.2
  * `docker` 7.1.0

**Comment by chang-annie** [comment]
all tests are passing! closing issue as done

- [x] build is successful
- [x] requests version is set to 2.32.2
- [x] docker version is set to 7.1.0
